/**
 * 会话域埋点的**事实**（`session.prompt-accepted` / `session.turn-completed`）。
 *
 * emit 侧是 `AgentSession`。payload 是一份契约，订阅方的 CEL `when` 是按这份形状写的 ——
 * 抽成独立模块，是为了让「什么算一轮」「尾部截多长」只有一处定义，而不是散在 emit 点里。
 *
 * 这里只答「会话此刻是什么样」，与任何具体 hook 无关 —— 谁订阅、订阅去做什么，都不是
 * 埋点该知道的事。
 */
import { sessionDao } from '../dao/sessionDao'
import { messageService } from './messageService'
import { t } from '../i18n'

/** 对话末尾文本的上限（`session.turn-completed` 的 recentText） */
const RECENT_TEXT_MAX_CHARS = 1000

export interface TurnCompletedFacts {
  title: string
  isDefaultTitle: boolean
  titleAutoGenerated: boolean
  turnCount: number
  textMessageCount: number
  recentText: string
}

/** 标题是否仍是当前语言下的通用默认值 */
export function isDefaultTitle(title: string): boolean {
  return title === t('agent.defaultTitle')
}

/** 一轮结束时的会话事实；会话行不存在返回 null（删除与本次埋点竞态） */
export async function buildTurnCompletedFacts(
  sessionId: string
): Promise<TurnCompletedFacts | null> {
  const picked = sessionDao.pick(sessionId, ['title', 'settings'])
  if (!picked) return null
  const messages = await messageService.listBySession(sessionId)
  const textMessages = messages.filter(
    (m) => (m.role === 'user' || m.role === 'assistant') && !!m.content.trim()
  )
  const recentText = textMessages
    .map((m) => `${m.role === 'user' ? 'User' : 'Assistant'}: ${m.content}`)
    .join('\n')
    .slice(-RECENT_TEXT_MAX_CHARS)

  return {
    title: picked.title,
    isDefaultTitle: isDefaultTitle(picked.title),
    titleAutoGenerated: picked.settings?.titleOrigin === 'auto',
    turnCount: textMessages.filter((m) => m.role === 'user').length,
    textMessageCount: textMessages.length,
    recentText
  }
}
