/**
 * 会话域埋点的**事实**（`session.prompt-accepted` / `session.turn-completed`）。
 *
 * emit 侧是 `AgentSession`。payload 是一份契约，订阅方的 CEL `when` 是按这份形状写的 ——
 * 抽成独立模块，是为了让「什么算一轮」「尾部截多长」只有一处定义，而不是散在 emit 点里。
 *
 * 这里只答「会话此刻是什么样」，与任何具体 hook 无关 —— 谁订阅、订阅去做什么，都不是
 * 埋点该知道的事。
 *
 * 转写按存储类型分流（`transcriptSource`）：旧格式会话照旧读冻结投影 —— 系统写的 user 消息（后台完成通知）
 * 照旧算一条 user；durable 会话读当前对话的转写摘要，**通知一律不算**（裁决 PIN-02：通知不是一轮，跨过午夜的
 * 日期通知也不该把 refine 的 `turnCount == 2` 窗口顶掉）。durable 会话的存储还不存在（从未发过消息）= 零计数。
 */
import { sessionRecords } from './sessionRecords'
import { readSessionTranscript, type TranscriptItem } from './transcriptSource'
import { t } from '../i18n'

/** 对话末尾文本的上限（`session.turn-completed` 的 recentText） */
const RECENT_TEXT_MAX_CHARS = 1000

export interface TurnCompletedFacts {
  title: string
  isDefaultTitle: boolean
  titleAutoGenerated: boolean
  turnCount: number
  textMessageCount: number
  recentText: string
}

/** 标题是否仍是当前语言下的通用默认值 */
export function isDefaultTitle(title: string): boolean {
  return title === t('agent.defaultTitle')
}

/** 一轮结束时的会话事实；会话行不存在返回 null（删除与本次埋点竞态） */
export async function buildTurnCompletedFacts(
  sessionId: string
): Promise<TurnCompletedFacts | null> {
  const picked = sessionRecords.pick(sessionId, ['title', 'settings'])
  if (!picked) return null
  const items = await readSessionTranscript(sessionId)
  // 有字的 user / assistant 正文（压缩摘要算 assistant；ask 的回答、错误事件不算）
  const textMessages = items.filter(
    (item): item is Extract<TranscriptItem, { kind: 'user' | 'assistant' }> =>
      (item.kind === 'user' || item.kind === 'assistant') && !!item.text.trim()
  )
  const recentText = textMessages
    .map((item) => `${item.kind === 'user' ? 'User' : 'Assistant'}: ${item.text}`)
    .join('\n')
    .slice(-RECENT_TEXT_MAX_CHARS)

  return {
    title: picked.title,
    isDefaultTitle: isDefaultTitle(picked.title),
    titleAutoGenerated: picked.settings?.titleOrigin === 'auto',
    turnCount: textMessages.filter((item) => item.kind === 'user').length,
    textMessageCount: textMessages.length,
    recentText
  }
}
