/**
 * 原生消息宿主的安装 —— 让 Chrome 知道「ShuviX 扩展要连本地组件时，拉起哪个程序」。
 *
 * 两样东西，桌面**每次启动**都重写一遍（幂等；内容没变就不碰文件）：
 *
 *  1. **启动脚本** `~/.shuvix/chrome-bridge/native-host`（Windows 为 `native-host.cmd`）：写死当前
 *     Electron 与 cli.js 的绝对路径，以 node 模式跑 `cli.js native-host`。不复用
 *     `resources/cli/shuvix` —— 那个 shim 依赖 bash 工具注入的环境变量，Chrome 拉起的进程没有。
 *     路径写死意味着 app 挪了位置、换了版本也会在下次启动时自愈。
 *  2. **宿主清单** `com.shuvix.chrome_bridge.json`：`path` 指向启动脚本，`allowed_origins` 只有
 *     ShuviX 扩展。macOS / Linux 写进每个**已安装**的 Chromium 系浏览器的 `NativeMessagingHosts`
 *     目录（浏览器的用户数据目录不存在就跳过，不替没装的浏览器建目录）；Windows 写一份到
 *     `~/.shuvix/chrome-bridge/`，再由 `HKCU\Software\<vendor>\NativeMessagingHosts\<name>` 注册表项指过去。
 *
 * 纯函数（算目标、算内容）与有副作用的执行分开，前者单测覆盖三个平台。
 */
import { execFile } from 'child_process'
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import {
  CHROME_BRIDGE_HOST_NAME,
  CHROME_EXTENSION_ID,
  type ChromeNativeHostInstall
} from '@shuvix/chat-protocol/chromeBridge'
import { createLogger } from '../../logger'

const log = createLogger('ChromeBridge:Install')

export type HostPlatform = 'darwin' | 'linux' | 'win32'

/** 一个浏览器的清单落点（macOS / Linux：目录；Windows：注册表项） */
export interface NativeHostTarget {
  /** 展示名 */
  browser: string
  /** 浏览器用户数据目录（macOS / Linux 据此判断装没装）；Windows 为空串 */
  baseDir: string
  /** 清单所在目录（macOS / Linux） */
  manifestDir?: string
  /** 注册表项（Windows，HKCU 下） */
  registryKey?: string
}

/** macOS：~/Library/Application Support 下各浏览器的用户数据目录 */
const MAC_BROWSERS: ReadonlyArray<[string, string]> = [
  ['Google Chrome', 'Google/Chrome'],
  ['Google Chrome Beta', 'Google/Chrome Beta'],
  ['Google Chrome Dev', 'Google/Chrome Dev'],
  ['Google Chrome Canary', 'Google/Chrome Canary'],
  ['Google Chrome for Testing', 'Google/Chrome for Testing'],
  ['Chromium', 'Chromium'],
  ['Microsoft Edge', 'Microsoft Edge'],
  ['Microsoft Edge Beta', 'Microsoft Edge Beta'],
  ['Microsoft Edge Dev', 'Microsoft Edge Dev'],
  ['Microsoft Edge Canary', 'Microsoft Edge Canary'],
  ['Brave', 'BraveSoftware/Brave-Browser'],
  ['Brave Beta', 'BraveSoftware/Brave-Browser-Beta'],
  ['Brave Nightly', 'BraveSoftware/Brave-Browser-Nightly'],
  ['Vivaldi', 'Vivaldi'],
  ['Arc', 'Arc/User Data']
]

/** Linux：~/.config 下各浏览器的用户数据目录 */
const LINUX_BROWSERS: ReadonlyArray<[string, string]> = [
  ['Google Chrome', 'google-chrome'],
  ['Google Chrome Beta', 'google-chrome-beta'],
  ['Google Chrome Dev', 'google-chrome-unstable'],
  ['Google Chrome for Testing', 'google-chrome-for-testing'],
  ['Chromium', 'chromium'],
  ['Microsoft Edge', 'microsoft-edge'],
  ['Microsoft Edge Beta', 'microsoft-edge-beta'],
  ['Microsoft Edge Dev', 'microsoft-edge-dev'],
  ['Brave', 'BraveSoftware/Brave-Browser'],
  ['Vivaldi', 'vivaldi']
]

/** Windows：HKCU\Software 下各浏览器读取原生消息宿主的注册表路径 */
const WIN_BROWSERS: ReadonlyArray<[string, string]> = [
  ['Google Chrome', 'Google\\Chrome'],
  ['Chromium', 'Chromium'],
  ['Microsoft Edge', 'Microsoft\\Edge'],
  ['Brave', 'BraveSoftware\\Brave-Browser'],
  ['Vivaldi', 'Vivaldi']
]

/** 各平台的清单落点（不判断装没装 —— 那是执行时的事） */
export function nativeHostTargets(platform: HostPlatform, home: string): NativeHostTarget[] {
  if (platform === 'win32') {
    return WIN_BROWSERS.map(([browser, vendor]) => ({
      browser,
      baseDir: '',
      registryKey: `HKCU\\Software\\${vendor}\\NativeMessagingHosts\\${CHROME_BRIDGE_HOST_NAME}`
    }))
  }
  const root =
    platform === 'darwin' ? join(home, 'Library', 'Application Support') : join(home, '.config')
  const table = platform === 'darwin' ? MAC_BROWSERS : LINUX_BROWSERS
  return table.map(([browser, rel]) => {
    const baseDir = join(root, ...rel.split('/'))
    return { browser, baseDir, manifestDir: join(baseDir, 'NativeMessagingHosts') }
  })
}

/** 启动脚本与清单所在的 ShuviX 自有目录 */
export function nativeHostHome(home: string): string {
  return join(home, '.shuvix', 'chrome-bridge')
}

export function launcherPath(platform: HostPlatform, home: string): string {
  return join(nativeHostHome(home), platform === 'win32' ? 'native-host.cmd' : 'native-host')
}

/** 启动脚本内容。去掉用户的 NODE_OPTIONS（与 resources/cli/shuvix 同一个理由：别污染内嵌 node） */
export function launcherContent(
  platform: HostPlatform,
  paths: { electron: string; cliJs: string }
): string {
  if (platform === 'win32') {
    // 批处理文件里 `%` 引出变量展开；路径里的字面 `%`（Windows 用户名里合法）要写成 `%%`
    const bat = (s: string): string => s.replace(/%/g, '%%')
    return [
      '@echo off',
      'rem Generated by ShuviX at every start: launches the Chrome native messaging host.',
      'set NODE_OPTIONS=',
      'set ELECTRON_RUN_AS_NODE=1',
      `"${bat(paths.electron)}" "${bat(paths.cliJs)}" native-host %*`,
      ''
    ].join('\r\n')
  }
  const q = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`
  return [
    '#!/bin/sh',
    '# Generated by ShuviX at every start: launches the Chrome native messaging host.',
    'unset NODE_OPTIONS',
    `ELECTRON_RUN_AS_NODE=1 exec ${q(paths.electron)} ${q(paths.cliJs)} native-host "$@"`,
    ''
  ].join('\n')
}

/** 宿主清单内容 */
export function manifestContent(launcher: string): string {
  return (
    JSON.stringify(
      {
        name: CHROME_BRIDGE_HOST_NAME,
        description: 'ShuviX desktop bridge for the ShuviX Chrome extension',
        path: launcher,
        type: 'stdio',
        allowed_origins: [`chrome-extension://${CHROME_EXTENSION_ID}/`]
      },
      null,
      2
    ) + '\n'
  )
}

/** 一次安装的结果（设置页「修复本地组件」展示用） */
export type NativeHostInstallResult = ChromeNativeHostInstall

/** 内容不同才写（不动 mtime、不在只读挂载上白报错） */
function writeIfChanged(path: string, content: string, mode?: number): void {
  let current: string | undefined
  try {
    current = readFileSync(path, 'utf-8')
  } catch {
    current = undefined
  }
  if (current !== content) writeFileSync(path, content, 'utf-8')
  if (mode !== undefined) chmodSync(path, mode)
}

function regAdd(key: string, value: string): Promise<void> {
  return new Promise((resolve, reject) => {
    execFile(
      'reg',
      ['add', key, '/ve', '/t', 'REG_SZ', '/d', value, '/f'],
      { windowsHide: true },
      (err) => (err ? reject(err) : resolve())
    )
  })
}

/**
 * 装一遍：启动脚本 + 每个已安装浏览器的清单。失败不抛（逐个记在结果里）——
 * 装不上只影响 Chrome 扩展这一条路，不能拦 app 启动。
 */
export async function installNativeHost(opts: {
  platform: HostPlatform
  home: string
  electron: string
  cliJs: string
}): Promise<NativeHostInstallResult> {
  const launcher = launcherPath(opts.platform, opts.home)
  const result: NativeHostInstallResult = { launcher, installed: [], failed: [] }
  try {
    mkdirSync(nativeHostHome(opts.home), { recursive: true })
    writeIfChanged(
      launcher,
      launcherContent(opts.platform, { electron: opts.electron, cliJs: opts.cliJs }),
      opts.platform === 'win32' ? undefined : 0o755
    )
  } catch (err) {
    result.failed.push({ browser: '*', error: (err as Error).message })
    log.warn(`writing the launcher failed: ${(err as Error).message}`)
    return result
  }

  const manifest = manifestContent(launcher)
  if (opts.platform === 'win32') {
    const manifestPath = join(nativeHostHome(opts.home), `${CHROME_BRIDGE_HOST_NAME}.json`)
    try {
      writeIfChanged(manifestPath, manifest)
    } catch (err) {
      result.failed.push({ browser: '*', error: (err as Error).message })
      return result
    }
    for (const target of nativeHostTargets('win32', opts.home)) {
      try {
        await regAdd(target.registryKey!, manifestPath)
        result.installed.push(target.browser)
      } catch (err) {
        result.failed.push({ browser: target.browser, error: (err as Error).message })
      }
    }
    return result
  }

  for (const target of nativeHostTargets(opts.platform, opts.home)) {
    // 浏览器没装（用户数据目录不在）就跳过：不替它建目录
    if (!existsSync(target.baseDir)) continue
    try {
      mkdirSync(target.manifestDir!, { recursive: true })
      writeIfChanged(join(target.manifestDir!, `${CHROME_BRIDGE_HOST_NAME}.json`), manifest)
      result.installed.push(target.browser)
    } catch (err) {
      result.failed.push({ browser: target.browser, error: (err as Error).message })
    }
  }
  return result
}
