/**
 * 内置 hook（builtinHooks/）—— 目前只有 auto-title。
 *
 * md 是唯一事实源（`?raw` 内联），所以断言打在**解析后的 hook** 与盘上原文上：结构钉板
 * （agent / 绑定 / 条件）、三语言只动显示名与描述、语言回落、条件真值表，以及经真 runner 的
 * 端到端派发（首条 prompt 起快标题 / 第二轮结束后精修一次）。
 */
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import {
  AUTO_TITLE_HOOK_SPEC,
  BUILTIN_HOOK_SPECS,
  buildBuiltinHooks,
  getBuiltinHookSource
} from '../builtinHooks'
import { parseHookDefinitionFile, type ParsedHookFile } from '../hookFile'
import { evaluateWhen } from '../when'
import { createInlineMdReader } from '../../subagent/builtinAgents/inlineSources'
import { BASE_PROFILE_NAMES, buildBuiltinProfiles } from '../../subagent/builtinAgents'
import type { InProcessAgentType } from '../../subagent/types'
import { PROFILE, entryOf, makeRunner, promptPayload, settle, turnPayload } from './harness'

/** 盘上原文（不经 `?raw`） */
const onDisk = (file: string): string =>
  readFileSync(new URL(`../builtinHooks/md/${file}`, import.meta.url), 'utf-8')

const LANGS = ['en', 'zh', 'ja'] as const
const DISK: Record<(typeof LANGS)[number], string> = {
  en: onDisk('auto-title.md'),
  zh: onDisk('auto-title.zh.md'),
  ja: onDisk('auto-title.ja.md')
}

const QUICK_WHEN = 'event.isDefaultTitle'
const REFINE_WHEN =
  'event.titleAutoGenerated && event.turnCount == 2 && event.textMessageCount >= 3'
const EN_TITLE = 'Automatic Session Titles'
const ZH_TITLE = '自动生成会话标题'
const JA_TITLE = 'セッション名の自動生成'

type Unlocalized = Omit<ParsedHookFile, 'displayName' | 'description'>
const unlocalized = ({
  displayName: _displayName,
  description: _description,
  ...rest
}: ParsedHookFile): Unlocalized => rest

const parseSource = (raw: string): ParsedHookFile => {
  const parsed = parseHookDefinitionFile(raw, 'auto-title')
  expect(parsed).not.toBeNull()
  return parsed!
}

describe('内置 hook 清单与交付', () => {
  it('HB-1 只有 auto-title；三语言源与盘上文件逐字一致；buildBuiltinHooks 恰一份', () => {
    expect(BUILTIN_HOOK_SPECS.map((spec) => spec.name)).toEqual(['auto-title'])
    expect(BUILTIN_HOOK_SPECS[0]).toBe(AUTO_TITLE_HOOK_SPEC)
    expect(Object.keys(AUTO_TITLE_HOOK_SPEC.sources).sort()).toEqual(['en', 'ja', 'zh'])
    for (const lang of LANGS) expect(AUTO_TITLE_HOOK_SPEC.sources[lang]).toBe(DISK[lang])

    const built = buildBuiltinHooks({})
    expect(built).toHaveLength(1)
    expect(built[0].name).toBe('auto-title')
  })

  it('HB-2 en 结构钉板：派 titler、两条绑定与条件、显示名与描述、正文点名字段且无模板语法', () => {
    const [autoTitle] = buildBuiltinHooks({ language: 'en' })
    expect(autoTitle.name).toBe('auto-title')
    expect(autoTitle.agent).toBe('titler')
    expect(autoTitle.bindings).toStrictEqual([
      { trigger: 'session.prompt-accepted', when: QUICK_WHEN },
      { trigger: 'session.turn-completed', when: REFINE_WHEN }
    ])
    expect(autoTitle.displayName).toBe(EN_TITLE)
    expect(autoTitle.description).toBe(
      'Names a session on its first prompt and refines the title once after the second turn.'
    )
    expect(autoTitle.prompt).toContain('`session`')
    expect(autoTitle.prompt).toContain('promptText')
    expect(autoTitle.prompt).toContain('recentText')
    expect(autoTitle.prompt).not.toContain('{{')
  })

  it.each(LANGS)('HB-3 %s：零告警解析；带 shuvix-builtin 与 name 行', (lang) => {
    const warns: string[] = []
    expect(
      parseHookDefinitionFile(AUTO_TITLE_HOOK_SPEC.sources[lang], 'auto-title', (m) =>
        warns.push(m)
      )
    ).not.toBeNull()
    expect(warns).toEqual([])
    const lines = DISK[lang].split(/\r?\n/)
    expect(lines).toContain('shuvix-builtin: true')
    expect(lines).toContain('name: auto-title')
  })

  it('HB-4 本地化只动 displayName / description：其余字段（含正文）与 en 深相等', () => {
    const en = parseSource(AUTO_TITLE_HOOK_SPEC.sources.en)
    const zh = parseSource(AUTO_TITLE_HOOK_SPEC.sources.zh)
    const ja = parseSource(AUTO_TITLE_HOOK_SPEC.sources.ja)
    expect(unlocalized(zh)).toStrictEqual(unlocalized(en))
    expect(unlocalized(ja)).toStrictEqual(unlocalized(en))
    expect(zh.prompt).toBe(en.prompt)
    expect(ja.prompt).toBe(en.prompt)

    expect(zh.displayName).toBe(ZH_TITLE)
    expect(ja.displayName).toBe(JA_TITLE)
    expect(new Set([en.displayName, zh.displayName, ja.displayName]).size).toBe(3)
    expect(new Set([en.description, zh.description, ja.description]).size).toBe(3)
  })

  it.each<[string | undefined, string]>([
    ['zh-CN', ZH_TITLE],
    ['ja-JP', JA_TITLE],
    ['fr', EN_TITLE],
    [undefined, EN_TITLE],
    ['ZH', ZH_TITLE]
  ])('HB-5 language %s → %s（精确 → 基础语言 → en 整文件回落）', (language, displayName) => {
    expect(buildBuiltinHooks({ language })[0].displayName).toBe(displayName)
  })

  it('HB-6 getBuiltinHookSource：按语言回原文；未知名 null；原文重解析即 buildBuiltinHooks 的结果', () => {
    expect(getBuiltinHookSource('auto-title')).toBe(DISK.en)
    expect(getBuiltinHookSource('auto-title', { language: 'zh' })).toBe(DISK.zh)
    expect(getBuiltinHookSource('nope')).toBeNull()
    for (const language of ['en', 'zh', 'ja', 'zh-CN', 'fr']) {
      const raw = getBuiltinHookSource('auto-title', { language })
      expect(raw).not.toBeNull()
      expect(parseSource(raw!)).toStrictEqual(buildBuiltinHooks({ language })[0])
    }
  })

  it('HB-9 派发的 agent 是内置档案，且不是基座', () => {
    const [autoTitle] = buildBuiltinHooks({})
    expect(
      buildBuiltinProfiles({ readMd: createInlineMdReader() }).map((profile) => profile.name)
    ).toContain(autoTitle.agent)
    expect(BASE_PROFILE_NAMES.has(autoTitle.agent)).toBe(false)
  })
})

describe('HB-7 条件真值表（经 evaluateWhen，event 带 trigger）', () => {
  const [autoTitle] = buildBuiltinHooks({})
  const [quick, refine] = autoTitle.bindings
  const env = { host: 'desktop', platform: 'darwin' }

  it.each([true, false])('HB-7 快标题 isDefaultTitle=%s → %s', (isDefaultTitle) => {
    const event = { ...promptPayload({ isDefaultTitle }), trigger: quick.trigger }
    expect(evaluateWhen(quick.when!, { event, env })).toBe(isDefaultTitle)
  })

  it.each<[boolean, number, number, boolean]>([
    [true, 2, 3, true],
    [true, 2, 2, false],
    [true, 1, 3, false],
    [true, 3, 3, false],
    [false, 2, 3, false],
    [true, 2, 10, true]
  ])(
    'HB-7 精修 titleAutoGenerated=%s turnCount=%i textMessageCount=%i → %s',
    (titleAutoGenerated, turnCount, textMessageCount, expected) => {
      const event = {
        ...turnPayload({ titleAutoGenerated, turnCount, textMessageCount }),
        trigger: refine.trigger
      }
      expect(evaluateWhen(refine.when!, { event, env })).toBe(expected)
    }
  )
})

describe('HB-8 端到端：auto-title 经真 runner 派发 titler', () => {
  it('HB-8 快标题 / 精修各在该跑的时候跑一次，不该跑的时候不跑', async () => {
    const [autoTitle] = buildBuiltinHooks({ language: 'en' })
    const titler: InProcessAgentType = {
      ...PROFILE,
      name: 'titler',
      displayName: 'Titler',
      tools: ['session']
    }
    const h = makeRunner({
      entries: [entryOf(autoTitle, 'builtin')],
      resolveAgentProfile: (name) => (name === 'titler' ? titler : null)
    })
    const fence = (prompt: string): string => prompt.slice(prompt.indexOf('<hook_event'))

    // 首条 prompt、标题仍是默认值 → 快标题
    h.runner.fire(
      'session.prompt-accepted',
      promptPayload({ isDefaultTitle: true, promptText: 'hello' })
    )
    await h.waitEnd(1)
    expect(h.runTask).toHaveBeenCalledTimes(1)
    const quick = h.call(0)
    expect(quick.agentType.name).toBe('titler')
    expect(quick.description).toBe(EN_TITLE)
    expect(quick.parentSessionId).toBe('s1')
    expect(fence(quick.prompt)).toContain('<hook_event trigger="session.prompt-accepted">')
    expect(fence(quick.prompt)).toContain('promptText: hello')
    expect(fence(quick.prompt)).not.toContain('recentText')

    // 标题已不是默认值 → 不跑
    h.runner.fire('session.prompt-accepted', promptPayload({ isDefaultTitle: false }))
    await settle()
    expect(h.runTask).toHaveBeenCalledTimes(1)

    // 第二轮结束、标题出自自动化、对话够长 → 精修
    h.runner.fire(
      'session.turn-completed',
      turnPayload({
        titleAutoGenerated: true,
        turnCount: 2,
        textMessageCount: 3,
        recentText: 'User: hello\nAssistant: hi there'
      })
    )
    await h.waitEnd(2)
    expect(h.runTask).toHaveBeenCalledTimes(2)
    expect(fence(h.call(1).prompt)).toContain('<hook_event trigger="session.turn-completed">')
    expect(fence(h.call(1).prompt)).toContain('recentText: |-')

    // 第三轮 → 不再精修
    h.runner.fire(
      'session.turn-completed',
      turnPayload({ titleAutoGenerated: true, turnCount: 3, textMessageCount: 3 })
    )
    await settle()
    expect(h.runTask).toHaveBeenCalledTimes(2)

    // 前一个 run 收尾之后，连续两次命中各起一个 run（不被 busy 吞掉）
    h.runner.fire('session.prompt-accepted', promptPayload({ isDefaultTitle: true }))
    await h.waitEnd(3)
    h.runner.fire('session.prompt-accepted', promptPayload({ isDefaultTitle: true }))
    await h.waitEnd(4)
    expect(h.runTask).toHaveBeenCalledTimes(4)
    expect(h.skips()).toEqual([])
  })
})
