/**
 * Hook runner 测试的共享夹具（**非 .test.ts —— 不被 vitest 收集**）。
 *
 * hookRunner.test.ts、hookDecide.test.ts 与 builtinHooks.test.ts 共用同一套 fake deps（照 workflow
 * 引擎测试 harness 的做法，去掉了脚本 / lane / journal 那几块）。观测面 = onRun 事件 + logger 行。
 *
 * 时序约定（用例据此选「立即断言」还是「等」）：
 *  - 去重判定、unknown-agent 跳过与占坑都在 fire 的**同步段**（launch 首个 await 之前）；
 *    decide 同理：匹配、unknown-agent 跳过与占坑都在 `decide()` 调用返回之前；
 *  - start 在模型解析之后，end 在 runTask 落定之后 —— 要等（waitEnd / vi.waitFor）；
 *  - 负向断言（「什么都没发生」）先 settle() 一个宏任务，让已排队的微任务链全部落定。
 *
 * 判定型的夹具（permissionPayload / verdict / scriptedRunTask）在文件末尾：派发按 hook 名
 * （`resultContract.sourceLabel`）分派脚本，所以同一次 decide 里几个 hook 可以各给各的结论、
 * 各自挂起或失败。
 */
import { expect, vi, type Mock } from 'vitest'
import type {
  PermissionDecision,
  PermissionVerdict
} from '@shuvix/chat-protocol/types/permissionReview'
import {
  createHookRunner,
  type HookRegistryEntry,
  type HookRunEvent,
  type HookRunner,
  type HookRunnerDeps
} from '../hookRunner'
import type { ParsedHookFile } from '../hookFile'
import type { TriggerPayloadMap } from '../triggerPoints'
import type { RunTaskParams } from '../../subagent/manager'
import type { InProcessAgentType, SubAgentModelConfig } from '../../subagent/types'

export type RunTaskResult = { result: string; structured?: unknown; error?: string }
export type RunTaskFn = (params: RunTaskParams) => Promise<RunTaskResult>

export type StartEvent = Extract<HookRunEvent, { type: 'start' }>
export type EndEvent = Extract<HookRunEvent, { type: 'end' }>
export type SkipEvent = Extract<HookRunEvent, { type: 'skip' }>

export const PROFILE: InProcessAgentType = {
  name: 'worker',
  displayName: 'Worker',
  description: '',
  tools: ['read', 'session'],
  systemPrompt: 'S'
}

export const MODEL: SubAgentModelConfig = { provider: 'p', model: 'm', capabilities: {} }

export const fileOf = (over: Partial<ParsedHookFile> = {}): ParsedHookFile => ({
  name: 'hk',
  displayName: 'Hook K',
  description: '',
  agent: 'worker',
  bindings: [{ trigger: 'session.prompt-accepted' }],
  prompt: 'Body.',
  ...over
})

export const entryOf = (
  file: ParsedHookFile,
  source: HookRegistryEntry['source'] = 'builtin'
): HookRegistryEntry => ({ file, source })

export const promptPayload = (
  over: Partial<TriggerPayloadMap['session.prompt-accepted']> = {}
): TriggerPayloadMap['session.prompt-accepted'] => ({
  sessionId: 's1',
  profileName: 'work',
  title: 'New Chat',
  isDefaultTitle: true,
  promptText: 'hi',
  ...over
})

export const turnPayload = (
  over: Partial<TriggerPayloadMap['session.turn-completed']> = {}
): TriggerPayloadMap['session.turn-completed'] => ({
  sessionId: 's1',
  profileName: 'work',
  title: 'Quick title',
  isDefaultTitle: false,
  turnCount: 2,
  textMessageCount: 3,
  titleAutoGenerated: true,
  recentText: 'User: a\nAssistant: b',
  ...over
})

export interface LogLine {
  level: 'info' | 'warn' | 'error'
  msg: string
}

export interface RunnerOptions {
  entries?: HookRegistryEntry[]
  listHooks?: HookRunnerDeps['listHooks']
  runTask?: RunTaskFn
  resolveAgentProfile?: HookRunnerDeps['resolveAgentProfile']
  resolveRunModel?: HookRunnerDeps['resolveRunModel']
  env?: HookRunnerDeps['env']
  timeoutMs?: number
  /** 判定型派发的墙钟上限（缺省走 runner 的 DEFAULT_DECIDE_TIMEOUT_MS） */
  decideTimeoutMs?: number
  /** 在事件被收集之后调用（HR-21 用它模拟观测回调抛错） */
  onRun?: (event: HookRunEvent) => void
  /** false = 不给 logger（HR-21：无 logger 的 runner 各路径都不抛） */
  logger?: boolean
}

export interface RunnerHarness {
  runner: HookRunner
  events: HookRunEvent[]
  logs: LogLine[]
  runTask: Mock<RunTaskFn>
  listHooks: Mock<HookRunnerDeps['listHooks']>
  resolveAgentProfile: Mock<HookRunnerDeps['resolveAgentProfile']>
  resolveRunModel: Mock<HookRunnerDeps['resolveRunModel']>
  starts: () => StartEvent[]
  ends: () => EndEvent[]
  skips: () => SkipEvent[]
  infos: () => string[]
  warns: () => string[]
  /** runTask 第 index 次调用的入参（缺省第一次） */
  call: (index?: number) => RunTaskParams
  /** 至少 n 个 end 事件 */
  waitEnd: (n?: number) => Promise<void>
}

export function makeRunner(opts: RunnerOptions = {}): RunnerHarness {
  const events: HookRunEvent[] = []
  const logs: LogLine[] = []
  const runTask = vi.fn<RunTaskFn>(opts.runTask ?? (async () => ({ result: 'ok' })))
  const listHooks = vi.fn<HookRunnerDeps['listHooks']>(
    opts.listHooks ?? ((): HookRegistryEntry[] => opts.entries ?? [])
  )
  const resolveAgentProfile = vi.fn<HookRunnerDeps['resolveAgentProfile']>(
    opts.resolveAgentProfile ?? ((name) => (name === 'worker' ? PROFILE : null))
  )
  const resolveRunModel = vi.fn<HookRunnerDeps['resolveRunModel']>(
    opts.resolveRunModel ?? (async () => MODEL)
  )

  const deps: HookRunnerDeps = {
    manager: { runTask },
    listHooks,
    resolveAgentProfile,
    resolveRunModel,
    env: opts.env ?? { host: 'desktop', platform: 'darwin' },
    onRun: (event) => {
      events.push(event)
      opts.onRun?.(event)
    }
  }
  if (opts.timeoutMs !== undefined) deps.timeoutMs = opts.timeoutMs
  if (opts.decideTimeoutMs !== undefined) deps.decideTimeoutMs = opts.decideTimeoutMs
  if (opts.logger !== false) {
    deps.logger = {
      info: (msg) => logs.push({ level: 'info', msg }),
      warn: (msg) => logs.push({ level: 'warn', msg }),
      error: (msg) => logs.push({ level: 'error', msg })
    }
  }
  const runner = createHookRunner(deps)

  const starts = (): StartEvent[] => events.filter((e): e is StartEvent => e.type === 'start')
  const ends = (): EndEvent[] => events.filter((e): e is EndEvent => e.type === 'end')
  const skips = (): SkipEvent[] => events.filter((e): e is SkipEvent => e.type === 'skip')

  return {
    runner,
    events,
    logs,
    runTask,
    listHooks,
    resolveAgentProfile,
    resolveRunModel,
    starts,
    ends,
    skips,
    infos: () => logs.filter((l) => l.level === 'info').map((l) => l.msg),
    warns: () => logs.filter((l) => l.level === 'warn').map((l) => l.msg),
    call: (index = 0) => {
      const call = runTask.mock.calls[index]
      expect(call, `runTask call #${index}`).toBeDefined()
      return call[0]
    },
    waitEnd: (n = 1) =>
      vi.waitFor(() => {
        expect(ends().length).toBeGreaterThanOrEqual(n)
      })
  }
}

/** 让已排队的微任务链全部落定（真计时器下用；fake timers 用 vi.advanceTimersByTimeAsync） */
export const settle = (): Promise<void> => new Promise((resolve) => setTimeout(resolve, 0))

export interface Deferred<T> {
  promise: Promise<T>
  resolve: (value: T) => void
  reject: (reason: unknown) => void
}

export function deferred<T>(): Deferred<T> {
  let resolve!: (value: T) => void
  let reject!: (reason: unknown) => void
  const promise = new Promise<T>((res, rej) => {
    resolve = res
    reject = rej
  })
  return { promise, resolve, reject }
}

export interface Gate {
  params: RunTaskParams
  release: (value?: RunTaskResult) => void
}

/** gate 版 runTask：每次调用挂起，测试端显式放行（去重 / 生命周期用例） */
export function gatedRunTask(): { runTask: RunTaskFn; gates: Gate[] } {
  const gates: Gate[] = []
  return {
    gates,
    runTask: (params) =>
      new Promise((resolve) => {
        gates.push({ params, release: (value = { result: 'ok' }) => resolve(value) })
      })
  }
}

/**
 * hang 型 runTask：挂到 signal 落下为止，然后 **resolve** 交回半截结果 ——
 * 真 manager 的收法（abort 之后交回已产出的文本，不 reject）。
 */
export function hangUntilAbort(): RunTaskFn {
  return (params) =>
    new Promise((resolve) => {
      const done = (): void => resolve({ result: 'partial' })
      if (params.signal?.aborted) return done()
      params.signal?.addEventListener('abort', done, { once: true })
    })
}

/** reject 型 runTask：abort 落下时以给定消息 reject（manager 抛错收尾的那一格） */
export function rejectOnAbort(message = 'dispatch aborted'): RunTaskFn {
  return (params) =>
    new Promise((_resolve, reject) => {
      const fail = (): void => reject(new Error(message))
      if (params.signal?.aborted) return fail()
      params.signal?.addEventListener('abort', fail, { once: true })
    })
}

// ─── 判定型（decide）夹具 ────────────────────────────────────────────────

/** 一份 `permission.request` payload：根会话里的一条沙箱外命令（嵌套字段各有一份） */
export const permissionPayload = (
  over: Partial<TriggerPayloadMap['permission.request']> = {}
): TriggerPayloadMap['permission.request'] => ({
  sessionId: 's1',
  agent: { profile: 'work', kind: 'root' },
  operation: {
    tool: 'bash',
    action: 'execute',
    objectType: 'command',
    target: 'rm -rf build',
    facts: { channel: 'bash', sandboxed: false, workingDirectory: '/ws' }
  },
  policy: {
    names: ['ask-on-command'],
    prompt: 'Commands outside the sandbox can touch anything.'
  },
  userMessages: ['clean the build directory'],
  delegatedTasks: [],
  recentOperations: [{ target: 'npm test', outcome: 'allowed' }],
  ...over
})

/** 一份合格判决；summary / reason 缺省带上 decision，便于区分是谁交的卷 */
export const verdict = (
  decision: PermissionDecision = 'allow',
  over: Partial<PermissionVerdict> = {}
): PermissionVerdict => ({
  decision,
  risk: 'low',
  summary: `${decision} it`,
  reason: `because ${decision}`,
  ...over
})

/** 契约捕获成功时 runTask 的交回形状（与真 manager 的 finishTurn 同形） */
export const verdictResult = (value: unknown): RunTaskResult => ({
  result: JSON.stringify(value, null, 2),
  structured: value
})

/**
 * 一次派发的脚本：
 *  - RunTaskResult 对象：立即交回它；
 *  - `{ reject }`：以这句话 reject（manager 抛错收尾）；
 *  - `'gate'`：挂到 `release(key)`；signal 落下时 resolve 半截结果（真 manager 的收法：
 *    中止之后交回已产出的文本，不 reject）—— 永远不 release 就是「挂到中止为止」；
 *  - `'stuck'`：挂到 `release(key)`；中止也不理（不配合中止的派发，如模型请求还在路上）。
 */
export type DecideBehavior = RunTaskResult | { reject: string } | 'gate' | 'stuck'

export interface ScriptedRunTask {
  runTask: RunTaskFn
  /** 某个键第一次派发的入参（键见 scriptedRunTask） */
  paramsOf: (key: string) => RunTaskParams
  /** 放行某个键最早一个还挂着的 gate / stuck 派发 */
  release: (key: string, value?: RunTaskResult) => void
  /** 某个键还挂着（没被放行、也没因中止收尾）的派发数 */
  pending: (key: string) => number
}

/** 观察型派发（没有结果契约）的键：`observe:<displayName>` */
export const observeKey = (description: string): string => `observe:${description}`

/**
 * 按 hook 分派的 runTask。键 = 判定派发的 `resultContract.sourceLabel`（即 hook 名）；没有契约的
 * 观察型派发键为 `observe:<description>`，一律走 `script.observe`。没写脚本的交回 `{result: 'ok'}`
 * （没有 structured —— 对判定型而言就是「没有意见」）。
 */
export function scriptedRunTask(
  script: { decide?: Record<string, DecideBehavior>; observe?: DecideBehavior } = {}
): ScriptedRunTask {
  const calls: Array<{ key: string; params: RunTaskParams }> = []
  const waiting: Array<{ key: string; settle: (value: RunTaskResult) => void }> = []

  const behave = (
    behavior: DecideBehavior,
    key: string,
    params: RunTaskParams
  ): Promise<RunTaskResult> => {
    if (typeof behavior === 'object' && 'reject' in behavior) {
      return Promise.reject(new Error(behavior.reject))
    }
    if (typeof behavior === 'object') return Promise.resolve(behavior)
    return new Promise<RunTaskResult>((resolve) => {
      const entry = {
        key,
        settle: (value: RunTaskResult): void => {
          const index = waiting.indexOf(entry)
          if (index < 0) return
          waiting.splice(index, 1)
          resolve(value)
        }
      }
      waiting.push(entry)
      if (behavior === 'stuck') return
      const signal = params.signal
      const onAbort = (): void => entry.settle({ result: 'partial' })
      if (signal?.aborted) onAbort()
      else signal?.addEventListener('abort', onAbort, { once: true })
    })
  }

  return {
    runTask: (params) => {
      const label = params.resultContract?.sourceLabel
      const key = label ?? observeKey(params.description)
      calls.push({ key, params })
      const behavior = label === undefined ? script.observe : script.decide?.[label]
      return behave(behavior ?? { result: 'ok' }, key, params)
    },
    paramsOf: (key) => {
      const call = calls.find((c) => c.key === key)
      expect(call, `runTask call for "${key}"`).toBeDefined()
      return call!.params
    },
    release: (key, value = { result: 'ok' }) => {
      const entry = waiting.find((w) => w.key === key)
      expect(entry, `a pending dispatch for "${key}"`).toBeDefined()
      entry!.settle(value)
    },
    pending: (key) => waiting.filter((w) => w.key === key).length
  }
}
