/**
 * 派发给 hook agent 的任务文本 = 正文 + `<hook_event>` 围栏（renderHookPrompt）。
 *
 * 契约：`<body>\n\n<hook_event trigger="<id>">\n<payload as YAML>\n</hook_event>`，YAML 用
 * `lineWidth: 0`（多行文本走 `|` 块、长行不折）。没有模板语法 —— 所以这里既钉形状，也钉
 * 「payload 原样进 YAML、agent 读回来的就是 emit 侧给的事实」这条往返性质。
 */
import { describe, expect, it } from 'vitest'
import { parse as parseYaml } from 'yaml'
import { HOOK_EVENT_TAG, renderHookPrompt } from '../hookPrompt'

const CLOSE = '</hook_event>'

/** 围栏里的 YAML 原文。闭合标签取末尾那个 —— payload 自己可以含 `</hook_event>` 字样（HP-9） */
function fenceYaml(text: string, trigger: string): string {
  const open = `<hook_event trigger="${trigger}">\n`
  const start = text.indexOf(open)
  expect(start).toBeGreaterThanOrEqual(0)
  expect(text.endsWith(`\n${CLOSE}`)).toBe(true)
  return text.slice(start + open.length, text.length - CLOSE.length - 1)
}

describe('renderHookPrompt — 形状', () => {
  it('HP-1 正文 + 空行 + 围栏，payload 按键序渲染为 YAML；标签名 hook_event', () => {
    expect(HOOK_EVENT_TAG).toBe('hook_event')
    expect(
      renderHookPrompt('Do it.', 'session.prompt-accepted', { sessionId: 's1', promptText: 'hi' })
    ).toBe(
      'Do it.\n\n<hook_event trigger="session.prompt-accepted">\nsessionId: s1\npromptText: hi\n</hook_event>'
    )
  })

  it('HP-2 正文为空 / 纯空白 → 只有围栏；正文尾部空行收成恰一个空行；结尾无换行', () => {
    for (const body of ['', '  \n ']) {
      const text = renderHookPrompt(body, 'x', { a: 1 })
      expect(text.startsWith('<hook_event')).toBe(true)
      expect(text).toBe('<hook_event trigger="x">\na: 1\n</hook_event>')
    }
    const padded = renderHookPrompt('Do it.\n\n\n', 'x', { a: 1 })
    expect(padded).toBe('Do it.\n\n<hook_event trigger="x">\na: 1\n</hook_event>')
    expect(padded.endsWith('\n')).toBe(false)
  })

  it('HP-3 多行文本 → `|-` 块（以换行结尾 → `|`）；长行不折', () => {
    expect(fenceYaml(renderHookPrompt('', 't', { recentText: 'User: a\nAssistant: b' }), 't')).toBe(
      'recentText: |-\n  User: a\n  Assistant: b'
    )
    expect(
      fenceYaml(renderHookPrompt('', 't', { recentText: 'User: a\nAssistant: b\n' }), 't')
    ).toBe('recentText: |\n  User: a\n  Assistant: b')

    const long = `${'word '.repeat(48)}x`
    expect(long).toHaveLength(241)
    expect(fenceYaml(renderHookPrompt('', 't', { long }), 't')).toBe(`long: ${long}`)
  })

  it('HP-4 布尔 / 数字不加引号；长得像别的类型的字符串加引号；键序保持插入序', () => {
    const yaml = fenceYaml(
      renderHookPrompt('', 't', {
        isDefaultTitle: true,
        titleAutoGenerated: false,
        turnCount: 3,
        ratio: 1.5,
        s1: 'true',
        s2: '123',
        s3: 'null',
        s4: '',
        s5: 'User: hi',
        s6: '- item',
        s7: '#hash',
        plain: 'plain text'
      }),
      't'
    )
    expect(yaml.split('\n')).toEqual([
      'isDefaultTitle: true',
      'titleAutoGenerated: false',
      'turnCount: 3',
      'ratio: 1.5',
      's1: "true"',
      's2: "123"',
      's3: "null"',
      's4: ""',
      's5: "User: hi"',
      's6: "- item"',
      's7: "#hash"',
      'plain: plain text'
    ])
  })

  it('HP-6 trigger 只在围栏属性上，不进 YAML；【钉现状】payload 自带的 trigger 键照常渲染', () => {
    const text = renderHookPrompt('Body', 'session.prompt-accepted', { sessionId: 's1' })
    expect(text).toContain('<hook_event trigger="session.prompt-accepted">')
    expect(text).not.toMatch(/^trigger:/m)

    const carried = renderHookPrompt('Body', 'session.prompt-accepted', {
      sessionId: 's1',
      trigger: 'spoofed'
    })
    expect(fenceYaml(carried, 'session.prompt-accepted').split('\n')).toEqual([
      'sessionId: s1',
      'trigger: spoofed'
    ])
  })

  it('HP-7 空 payload → 围栏里是 {}', () => {
    expect(renderHookPrompt('', 'x', {})).toBe('<hook_event trigger="x">\n{}\n</hook_event>')
  })
})

describe('renderHookPrompt — 往返（agent 读回来的就是 emit 侧的事实）', () => {
  it('HP-5 真实形状的 payload（unicode / emoji / ~1000 字、首尾带空格的行）往返后深相等', () => {
    const recentText = [
      '  User: leading spaces',
      'Assistant: trailing spaces   ',
      '',
      '    deeply indented line',
      ...Array.from(
        { length: 18 },
        (_, i) => `User: 第${i}轮 — naïve café 🚀 lorem ipsum lorem ipsum`
      )
    ].join('\n')
    expect(recentText.length).toBeGreaterThan(900)
    const payload = {
      sessionId: '019a2b3c-sess',
      profileName: 'work',
      title: '新しいチャット 🎉',
      isDefaultTitle: false,
      turnCount: 2,
      textMessageCount: 3,
      titleAutoGenerated: true,
      recentText
    }
    const text = renderHookPrompt('Body.', 'session.turn-completed', payload)
    expect(parseYaml(fenceYaml(text, 'session.turn-completed'))).toEqual(payload)
  })

  it('HP-8 嵌套值渲染为嵌套 YAML 并往返', () => {
    const payload = {
      sessionId: 's1',
      meta: { a: 1, b: { c: 'x' } },
      list: [1, 'two', { k: true }]
    }
    const yaml = fenceYaml(renderHookPrompt('', 't', payload), 't')
    expect(yaml).toBe(
      'sessionId: s1\nmeta:\n  a: 1\n  b:\n    c: x\nlist:\n  - 1\n  - two\n  - k: true'
    )
    expect(parseYaml(yaml)).toEqual(payload)
  })

  it('HP-9 【钉现状】不做转义：payload 里的 </hook_event> 原样进块；CRLF 文本走双引号转义并往返', () => {
    const text = renderHookPrompt('', 't', { recentText: '</hook_event>\nafter' })
    expect(text).toBe(
      '<hook_event trigger="t">\nrecentText: |-\n  </hook_event>\n  after\n</hook_event>'
    )
    expect(parseYaml(fenceYaml(text, 't'))).toEqual({ recentText: '</hook_event>\nafter' })

    const crlf = renderHookPrompt('', 't', { recentText: 'User: a\r\nAssistant: b' })
    expect(fenceYaml(crlf, 't')).toBe('recentText: "User: a\\r\\nAssistant: b"')
    expect(parseYaml(fenceYaml(crlf, 't'))).toEqual({ recentText: 'User: a\r\nAssistant: b' })
  })
})
