/**
 * 触发绑定的 CEL `when`（compileWhen / evaluateWhen）。
 *
 * 两个时机：解析期 compileWhen 只查语法（语法错 → 整份文件非法）；fire 时 evaluateWhen
 * 严格求值 —— 缺失属性、未知变量、非布尔结果一律 throw，由 runner 兜成「不命中 + 告警」。
 * 这里钉的是「严格」本身：宽松一步（缺属性当 false、非布尔按真值）就会让写错字段名的 hook
 * 静默地永远不跑或永远在跑。
 */
import { describe, expect, it } from 'vitest'
import { compileWhen, evaluateWhen } from '../when'

/** 内置 auto-title 精修绑定的条件（最复杂的真实表达式） */
const REFINE = 'event.titleAutoGenerated && event.turnCount == 2 && event.textMessageCount >= 3'

describe('compileWhen — 解析期只查语法', () => {
  it.each([
    'event.isDefaultTitle',
    REFINE,
    'has(event.x)',
    "event.p in ['work', 'chat']",
    "event.t.contains('x')",
    'size(event.t) > 0',
    "env.host == 'desktop'"
  ])('HW-1 合法表达式 %s → null', (expression) => {
    expect(compileWhen(expression)).toBeNull()
  })

  it.each(['event.', 'event.a &&', '', '   ', 'event.a === 1'])(
    'HW-2 语法错 %j → 非空错误消息',
    (expression) => {
      const error = compileWhen(expression)
      expect(typeof error).toBe('string')
      expect(error!.trim().length).toBeGreaterThan(0)
    }
  )
})

describe('evaluateWhen — fire 时严格求值', () => {
  it('HW-3 布尔结果原样返回（字段 true / false，字面量 true）', () => {
    expect(evaluateWhen('event.isDefaultTitle', { event: { isDefaultTitle: true } })).toBe(true)
    expect(evaluateWhen('event.isDefaultTitle', { event: { isDefaultTitle: false } })).toBe(false)
    expect(evaluateWhen('true', { event: {}, env: {} })).toBe(true)
  })

  it('HW-4 非布尔结果 throw（字符串 → got string；1 + 1 是 BigInt → got bigint）', () => {
    expect(() => evaluateWhen('event.title', { event: { title: 'New Chat' } })).toThrow(
      'when expression must evaluate to a boolean, got string'
    )
    expect(() => evaluateWhen('1 + 1', { event: {}, env: {} })).toThrow(
      'when expression must evaluate to a boolean, got bigint'
    )
  })

  it('HW-5 严格访问：缺失属性 / 未知顶层变量 / event 为 null 都 throw', () => {
    expect(() => evaluateWhen('event.nope', { event: {} })).toThrow(/No such key: nope/)
    expect(() => evaluateWhen('vars.a == 1', { event: {}, env: {} })).toThrow(
      /Unknown variable: vars/
    )
    expect(() => evaluateWhen('event.isDefaultTitle', { event: null })).toThrow()
  })

  it('HW-6 has() 是探测缺失字段的正路 → false，不 throw', () => {
    expect(evaluateWhen('has(event.nope)', { event: {} })).toBe(false)
  })

  it('HW-7 上下文 {event, env} 都可达（event.trigger 与 env.platform）', () => {
    expect(
      evaluateWhen("event.trigger == 'session.prompt-accepted' && env.platform == 'darwin'", {
        event: { trigger: 'session.prompt-accepted' },
        env: { host: 'desktop', platform: 'darwin' }
      })
    ).toBe(true)
  })

  it('HW-8 短路：false && event.nope → false（右侧缺失属性不求值）', () => {
    expect(evaluateWhen('false && event.nope', { event: {} })).toBe(false)
  })

  it('HW-9 编译缓存不冻结上下文：同一表达式换 payload 结论跟着变', () => {
    const expression = 'event.turnCount == 2'
    expect(evaluateWhen(expression, { event: { turnCount: 2 } })).toBe(true)
    expect(evaluateWhen(expression, { event: { turnCount: 3 } })).toBe(false)
    expect(evaluateWhen(expression, { event: { turnCount: 2 } })).toBe(true)
  })

  it("HW-10 类型严格：'2' == 2 为 false；数字比较照常", () => {
    expect(evaluateWhen('event.turnCount == 2', { event: { turnCount: '2' } })).toBe(false)
    expect(evaluateWhen('event.turnCount >= 3', { event: { turnCount: 3 } })).toBe(true)
    expect(evaluateWhen('event.turnCount >= 3', { event: { turnCount: 2 } })).toBe(false)
  })
})
