/**
 * 内置工作流 auto-title 的钉板 + 真脚本端到端。
 *
 * 与 builtinAgents 的 registry.test.ts 同一哲学：md 是唯一事实源，断言一律打在
 * **解析后的产物**上 —— frontmatter/脚本/schema 块任何一处写坏，buildBuiltinWorkflow
 * 返回 null，下面的用例立刻失败。端到端一节把真实 md 的真脚本放进 AsyncFunction 引擎
 * 真跑：两条绑定（quick/refine）的 when 条件、titler 派发的 prompt 组装、结果契约
 * 透传与 journal 落点全部走真代码，只有 manager 与档案解析是 fake。
 */
import { describe, expect, it, vi } from 'vitest'
import { botReplyToMarkdown, type BotReply } from '@shuvix/chat-protocol/botReply'
import {
  AUTO_TITLE_WORKFLOW_SPEC,
  BUILTIN_WORKFLOW_SPECS,
  buildBuiltinWorkflow,
  buildBuiltinWorkflows,
  getBuiltinWorkflowSource
} from '../builtinWorkflows'
import { createWorkflowEngine, type WorkflowScriptEngine } from '../engine'
import type { WorkflowRegistryEntry } from '../engine'
import { agentSlotsOf } from '../agentSlots'
import type { TriggerPayloadMap } from '../triggerPoints'
import type { RunTaskParams, SubAgentManager } from '../../subagent/manager'
import type { InProcessAgentType } from '../../subagent/types'
import type { ParsedWorkflowFile } from '../workflowFile'

const autoTitle = (): NonNullable<ReturnType<typeof buildBuiltinWorkflow>> =>
  buildBuiltinWorkflow(AUTO_TITLE_WORKFLOW_SPEC, {})!

describe('auto-title — 结构钉板', () => {
  it('buildBuiltinWorkflows({}) 的内置清单是钉板：auto-title + bot-chat，都解析非 null', () => {
    // 保持 toEqual 的严格性 —— 内置清单多一条少一条都该在这里现形
    const all = buildBuiltinWorkflows({})
    expect(all.map((w) => w.name)).toEqual(['auto-title', 'bot-chat'])
    expect(autoTitle()).not.toBeNull()
  })

  it('绑定钉板：恰两条 —— quick（prompt-accepted + isDefaultTitle）与 refine（turn-completed + 三条件）', () => {
    const bindings = autoTitle().bindings
    expect(bindings).toHaveLength(2)
    expect(bindings[0].trigger).toBe('session.prompt-accepted')
    expect(bindings[0].when).toBe('event.isDefaultTitle')
    expect(bindings[1].trigger).toBe('session.turn-completed')
    expect(bindings[1].when).toContain('titleAutoGenerated')
    expect(bindings[1].when).toContain('turnCount == 2')
    expect(bindings[1].when).toContain('textMessageCount >= 3')
  })

  it('schemas.result：顶层 object 且 required=[title]', () => {
    const schema = autoTitle().schemas.result
    expect(schema.type).toBe('object')
    expect(schema.required).toEqual(['title'])
  })

  it('结构缺省钉板：concurrency skip、无 limits（模型跟随会话/被派发 agent 的声明）', () => {
    const wf = autoTitle()
    expect(wf.concurrency).toBe('skip')
    expect(wf.limits).toEqual({})
  })
})

// ── 真脚本端到端：AsyncFunction 引擎 + fake manager/档案 ──

const AsyncFunction = Object.getPrototypeOf(async () => {}).constructor as new (
  ...args: string[]
) => (...vals: unknown[]) => Promise<unknown>
const scriptEngine: WorkflowScriptEngine = {
  compile: () => ({ ok: true }),
  execute: async (source, api) =>
    new AsyncFunction(...Object.keys(api), source)(...Object.values(api))
}

const TITLER: InProcessAgentType = {
  name: 'titler',
  displayName: 'Titler',
  description: '',
  tools: ['session'],
  systemPrompt: 'You name chat sessions.'
}

function makeAutoTitleEngine(
  overrideRunTask?: (p: RunTaskParams) => Promise<{ result: string; structured?: unknown }>
): {
  engine: ReturnType<typeof createWorkflowEngine>
  runTask: ReturnType<typeof vi.fn>
  records: Array<Record<string, unknown>>
  metas: () => Array<Record<string, unknown>>
  waitEnd: (n?: number) => Promise<void>
} {
  const records: Array<Record<string, unknown>> = []
  const runTask = vi.fn(
    overrideRunTask ??
      (async () => ({
        result: JSON.stringify({ title: 'X' }),
        structured: { title: 'X' }
      }))
  )
  const entries: WorkflowRegistryEntry[] = [{ file: autoTitle(), source: 'builtin' }]
  const engine = createWorkflowEngine({
    manager: { runTask } as unknown as SubAgentManager,
    script: scriptEngine,
    listWorkflows: () => entries,
    resolveAgentProfile: (ref) => (ref === 'titler' ? TITLER : null),
    resolveRunModel: async () => ({ provider: 'p', model: 'm', capabilities: {} }),
    onRecord: (_name, _runId, rec) => records.push(rec),
    env: { host: 'desktop', platform: 'darwin' }
  })
  return {
    engine,
    runTask,
    records,
    metas: () => records.filter((r) => r.type === 'meta'),
    waitEnd: (n = 1) =>
      vi.waitFor(() => {
        expect(records.filter((r) => r.type === 'end').length).toBeGreaterThanOrEqual(n)
      })
  }
}

const promptPayload = (
  over: Partial<TriggerPayloadMap['session.prompt-accepted']> = {}
): TriggerPayloadMap['session.prompt-accepted'] => ({
  sessionId: 's1',
  profileName: 'default',
  title: 'New Chat',
  isDefaultTitle: true,
  promptText: 'hello',
  ...over
})

const turnPayload = (
  over: Partial<TriggerPayloadMap['session.turn-completed']> = {}
): TriggerPayloadMap['session.turn-completed'] => ({
  sessionId: 's1',
  profileName: 'default',
  title: 'Quick title',
  isDefaultTitle: false,
  titleAutoGenerated: true,
  turnCount: 2,
  textMessageCount: 3,
  recentText: 'User: a\nAssistant: b',
  ...over
})

describe('auto-title — quick 端到端（真脚本）', () => {
  it('prompt-accepted + isDefaultTitle → 派发 titler 恰一次，契约/描述/归属逐项落位，end ok:true', async () => {
    const { engine, runTask, records, waitEnd } = makeAutoTitleEngine()
    engine.fire('session.prompt-accepted', promptPayload())
    await waitEnd()

    expect(runTask).toHaveBeenCalledTimes(1)
    const params = runTask.mock.calls[0][0] as RunTaskParams
    expect(params.agentType.name).toBe('titler')
    expect(params.prompt).toContain('hello')
    expect(params.prompt).toContain('<conversation>')
    expect(params.description).toBe('session title')
    expect(params.resultContract?.schema).toEqual(autoTitle().schemas.result)
    expect(params.resultContract?.sourceLabel).toBe('auto-title')
    expect(params.parentSessionId).toBe('s1')

    const end = records.find((r) => r.type === 'end')!
    expect(end.ok).toBe(true)
    expect(end.output).toEqual({ title: 'X' })
    expect(records.some((r) => r.type === 'log' && r.message === 'title applied: X')).toBe(true)
  })

  it('quick 反例：isDefaultTitle:false → 零派发', async () => {
    const { engine, runTask, records } = makeAutoTitleEngine()
    engine.fire('session.prompt-accepted', promptPayload({ isDefaultTitle: false }))
    expect(records).toEqual([])
    expect(runTask).not.toHaveBeenCalled()
  })
})

describe('auto-title — refine 端到端（真脚本）', () => {
  it('turn-completed 三条件齐 → 派发且 prompt 含 recentText', async () => {
    const { engine, runTask, waitEnd } = makeAutoTitleEngine()
    engine.fire('session.turn-completed', turnPayload())
    await waitEnd()
    expect(runTask).toHaveBeenCalledTimes(1)
    expect((runTask.mock.calls[0][0] as RunTaskParams).prompt).toContain('User: a\nAssistant: b')
  })

  it.each([
    ['titleAutoGenerated:false', { titleAutoGenerated: false }],
    ['turnCount 1', { turnCount: 1 }],
    ['turnCount 3', { turnCount: 3 }],
    ['textMessageCount 2', { textMessageCount: 2 }]
  ])('refine 反例 %s → 零派发', (_label, over) => {
    const { engine, runTask, records } = makeAutoTitleEngine()
    engine.fire('session.turn-completed', turnPayload(over))
    expect(records).toEqual([])
    expect(runTask).not.toHaveBeenCalled()
  })
})

describe('auto-title — 摘录裁尾', () => {
  it('promptText 2000 字 → 发出的 prompt 里 <conversation> 摘录 ≤1000 字', async () => {
    const { engine, runTask, waitEnd } = makeAutoTitleEngine()
    engine.fire('session.prompt-accepted', promptPayload({ promptText: 'x'.repeat(2000) }))
    await waitEnd()
    const prompt = (runTask.mock.calls[0][0] as RunTaskParams).prompt
    const excerpt = /<conversation>\n([\s\S]*?)\n<\/conversation>/.exec(prompt)?.[1]
    expect(excerpt).toBeDefined()
    expect(excerpt!.length).toBeLessThanOrEqual(1000)
  })
})

describe('auto-title — 分道（M2′ 顺带修掉的既有缺陷）', () => {
  /** 挂起的 titler 派发：测试端显式放行 */
  const gatedTitler = (
    gates: Array<() => void>
  ): (() => Promise<{ result: string; structured?: unknown }>) => {
    return () =>
      new Promise((resolve) =>
        gates.push(() =>
          resolve({ result: JSON.stringify({ title: 'X' }), structured: { title: 'X' } })
        )
      )
  }

  it('迁移承诺：md 一字未改 —— 两条绑定都没有 key，缺省键由埋点 scope 推导', () => {
    expect(autoTitle().bindings.every((b) => b.key === undefined)).toBe(true)
  })

  it('两个会话同时 turn-completed → 各起一个 run（refine 是一次性窗口，被 skip 即永久丢标题）', async () => {
    const gates: Array<() => void> = []
    const { engine, runTask, metas, waitEnd } = makeAutoTitleEngine(gatedTitler(gates))

    engine.fire('session.turn-completed', turnPayload({ sessionId: 's1' }))
    engine.fire('session.turn-completed', turnPayload({ sessionId: 's2' }))
    await vi.waitFor(() => expect(gates).toHaveLength(2))

    expect(metas().map((m) => m.lane)).toEqual(['auto-title\u0000s1', 'auto-title\u0000s2'])
    expect(runTask).toHaveBeenCalledTimes(2)

    gates.forEach((release) => release())
    await waitEnd(2)
  })

  it('同一会话内 quick 与 refine 仍互斥（同道按文件策略 skip）', async () => {
    const gates: Array<() => void> = []
    const { engine, metas, waitEnd } = makeAutoTitleEngine(gatedTitler(gates))

    engine.fire('session.prompt-accepted', promptPayload({ sessionId: 's1' }))
    await vi.waitFor(() => expect(gates).toHaveLength(1))
    engine.fire('session.turn-completed', turnPayload({ sessionId: 's1' }))

    expect(metas()).toHaveLength(1)
    gates[0]()
    await waitEnd()
  })
})

describe('bot-chat — 骨架管线的结构钉板', () => {
  const botChat = (): ParsedWorkflowFile =>
    buildBuiltinWorkflows({}).find((w) => w.name === 'bot-chat')!

  it('没有任何埋点绑定 —— 它只由会话按名 invoke', () => {
    expect(botChat().bindings).toEqual([])
  })

  it('concurrency 为 parallel：引擎重入彻底让位，独占由宿主的 turn() 提供', () => {
    // 这两件事是**两个粒度**：引擎重入管「要不要起 run」，mailbox 管「已在跑的 run
    // 何时进独占段」。声明 parallel 才不会让两者打架
    expect(botChat().concurrency).toBe('parallel')
  })

  it('三个契约块齐全且都是 type:object（M5′/M8′ 直接消费，此刻已是最终形态）', () => {
    const schemas = botChat().schemas
    expect(Object.keys(schemas).sort()).toEqual(['intent', 'recheck', 'reply'])
    for (const [name, schema] of Object.entries(schemas)) {
      expect((schema as { type?: string }).type, name).toBe('object')
    }
  })

  it('intent 没有 ignore —— 一对一会话里每条消息都是说给这个 bot 的，沉默不在契约上', () => {
    const enumOf = (n: string): string[] =>
      (botChat().schemas[n] as Record<string, Record<string, Record<string, string[]>>>).properties
        .decision.enum ?? []
    expect(enumOf('intent')).toEqual(['reply', 'task', 'clarify'])
    // 群聊时代的第二份契约（点名版）随 directed 一起退役
    expect(botChat().schemas.intentDirected).toBeUndefined()
    // task 一旦给出必带 objective：脚本以 `intent.task || { objective: intent.reason }` 回落，
    // 一个没有 objective 的空 task 对象会让任务段拿到一个没有目标的活
    const task = (
      botChat().schemas.intent as { properties: Record<string, { required?: string[] }> }
    ).properties.task
    expect(task.required).toEqual(['objective'])
  })

  it('脚本一律读 input.* —— 脚本作用域不平铺 input（裸名是 ReferenceError）', () => {
    const script = botChat().script
    // 平铺只发生在提示词块的渲染作用域；脚本 global 只有基础 API + 调用方装配的那几个
    for (const field of [
      'window',
      'agents.intent',
      'agents.task',
      'agents.recheck',
      'message.attachments'
    ]) {
      expect(script, field).toContain(`input.${field}`)
    }
    // 群聊时代的成员语义一个都不再读：directed（点名）/ members / others（其它成员）
    for (const gone of ['session.directed', 'session.members', 'session.others']) {
      expect(script, gone).not.toContain(gone)
    }
    // 退役的入参一个都不再读：occasion（场合分流）/ notes / since（笔记材料）——
    // 笔记场合没了，bot 的档案经 systemContext 进系统提示词，脚本连碰都不碰
    for (const gone of ['occasion', 'notes', 'since']) {
      expect(script, gone).not.toContain(`input.${gone}`)
    }
    // 反过来：新消息的正文脚本一次都不碰 —— 它经模板的 {{message.text}} 进提示词，
    // 那里的作用域才是平铺的。脚本只挑材料，不拼文案
    expect(script).not.toContain('input.message.text')
    expect(botChat().prompts.gate).toContain('{{message.text}}')
    // 两个装配进来的函数都用上了 —— 它们正是「这份 md 是 bot 管线」的全部含义。
    // v2 取消仲裁后 claim 一并消失：没有竞争就没有「这条归谁」要裁
    for (const api of ['turn(', 'say(']) expect(script).toContain(api)
    expect(script).not.toContain('claim(')
  })

  it('脚本不接住任何错误：没有 try/catch、没有错误码分支、不替失败出声', () => {
    // 失败原样上抛：引擎把 errorCode / errorStep 交回宿主，文案（i18n）与门控健康记账
    // 都在 botService。脚本里若重新长出 catch 分支，就是把「宿主替它说」又搬回了脚本
    const script = botChat().script
    expect(script).not.toMatch(/\btry\s*\{/)
    expect(script).not.toMatch(/\bcatch\s*\(e\)/)
    for (const code of ['step_aborted', 'next_not_called', 'step_timeout', 'unknown_agent']) {
      expect(script, code).not.toContain(code)
    }
    expect(script).not.toContain('error: true')
    // 唯一的一处吞错是复核：它只可能省掉一次重复，失败即照常干活
    expect(script.match(/\.catch\(\(\) => null\)/g)).toHaveLength(1)
    // 也不再自报 gate：门控健康由宿主从失败归类推
    expect(script).not.toMatch(/gate:\s*'/)
  })

  it('脚本里每个 prompt(…) 用到的块名都真有对应的块（改名漏一处 = 运行时抛）', () => {
    const wf = botChat()
    // 收集实参表达式里的全部字符串字面量（第一个实参若是表达式也能一并收进来）
    const used = [...wf.script.matchAll(/prompt\(([^,)]+)/g)].flatMap((m) =>
      [...m[1].matchAll(/'([A-Za-z][\w-]*)'/g)].map((n) => n[1])
    )
    expect(new Set(used)).toEqual(new Set(['gate', 'recheck', 'recheckSkipped', 'task']))
    for (const name of new Set(used)) {
      expect(Object.keys(wf.prompts), name).toContain(name)
    }
  })

  it('可选上下文是被引用的块（{{>name}}），标题住在块里，脚本不再预拼 xxxBlock', () => {
    // 被引用的块占位符全空即整块消失（promptTemplate）——「有内容才出现的一段」直接住在 md 里
    const wf = botChat()
    expect(wf.prompts.gate).toContain('{{>window}}')
    expect(wf.prompts.task).toContain('{{>window}}')
    expect(wf.prompts.task).toContain('{{>since}}')
    expect(wf.prompts.task).toContain('{{>boundaries}}')
    expect(wf.prompts.recheck).toContain('{{>since}}')
    // 群聊时代的两个块（点名说明 / 其它成员）退役：一对一没有「别人」，也没有「点名」
    expect(wf.prompts.gateDirected).toBeUndefined()
    expect(wf.prompts.others).toBeUndefined()
    for (const titled of ['window', 'since', 'boundaries']) {
      expect(wf.prompts[titled], titled).toContain('##')
    }
    for (const gone of [
      'othersBlock',
      'windowBlock',
      'sinceBlock',
      'boundariesBlock',
      'addressed'
    ]) {
      expect(wf.script, gone).not.toContain(gone)
    }
    // notes 块随笔记场合退役 —— bot 的档案经 systemContext 进系统提示词，不再是可选上下文
    expect(Object.keys(wf.prompts)).not.toContain('notes')
    expect(wf.script).not.toContain("prompt('notes'")
  })
})

/**
 * 任务段（M8′）落地之后 bot-chat 的结构面。行为面在 botChatTask.test.ts 真跑，这里只钉
 * **md 上肉眼可查、改了就该有人知道**的那几处：默认值、契约形状、以及两条刻意的「不写」
 * （任务段不给 tools、提示词不宣告附件）——「刻意不写」是最容易在下一次编辑里被好心补上的。
 */
describe('bot-chat —— 任务段与 BotReply 的结构钉板', () => {
  const botChat = (): ParsedWorkflowFile =>
    buildBuiltinWorkflows({}).find((w) => w.name === 'bot-chat')!

  it('BC-1 vars 数值钉板：两个窗口、两个墙钟与出队复核开关（notes* 三项随笔记场合退役）', () => {
    // 数值本身没有神圣性，但它们是 e2e 与单测里一堆断言的依据（切片条数、超时秒数），
    // 改一个就该在这里显形一次
    expect(botChat().vars).toEqual({
      gateWindow: 8,
      taskWindow: 20,
      gateTimeoutSec: 60,
      taskTimeoutSec: 1800,
      recheckStale: true
    })
  })

  it('BC-2 limits：agent 上限 4、墙钟 2400s —— 必须宽于最长的单步（taskTimeoutSec）', () => {
    const wf = botChat()
    expect(wf.limits).toEqual({ maxAgents: 4, maxDurationSec: 2400 })
    // run 级墙钟若短于单步墙钟，任务段永远等不到自己的超时，出声的就成了笼统的 run 失败
    expect(wf.limits.maxDurationSec!).toBeGreaterThan(wf.vars.taskTimeoutSec as number)
  })

  it('BC-3 reply 契约恰六键，required 只有 headline（结论先行是唯一的硬要求）', () => {
    const reply = botChat().schemas.reply as {
      required?: string[]
      properties?: Record<string, unknown>
    }
    expect(reply.required).toEqual(['headline'])
    expect(Object.keys(reply.properties!).sort()).toEqual([
      'body',
      'followups',
      'headline',
      'points',
      'status',
      'table'
    ])
  })

  it('BC-4 【契约↔投影闭环】reply 契约里的每个键都能在 markdown 投影里留下痕迹', () => {
    // 契约多出一个投影不认识的键，模型就会去填一个既不进 content 也不上屏的字段 ——
    // 让它填等于骗它。这条把 md 那份 JSON Schema 与 chat-protocol 的投影拴在一起，
    // 两边任何一侧单方面加键都在这里现形
    const sample: Record<string, unknown> = {
      headline: '结论一句',
      body: '一段解释',
      points: ['要点甲'],
      table: { columns: ['列甲'], rows: [['格甲']] },
      status: 'warn',
      followups: ['接着问什么']
    }
    const traces: Record<string, string> = {
      headline: '结论一句',
      body: '一段解释',
      points: '要点甲',
      table: '列甲',
      status: 'Status: warn',
      followups: '接着问什么'
    }
    const reply = botChat().schemas.reply as { properties: Record<string, unknown> }
    for (const key of Object.keys(reply.properties)) {
      expect(Object.keys(sample), key).toContain(key)
      const single = { headline: '结论一句', [key]: sample[key] } as BotReply
      expect(botReplyToMarkdown(single), key).toContain(traces[key])
    }
    // table 的行列都得声明出来，否则模型会交回半张表而投影只能整段丢掉它
    const table = reply.properties.table as { required?: string[] }
    expect(table.required).toEqual(['columns', 'rows'])
  })

  it('BC-5 【刻意不写】任务段的 run 没有 tools 选项 —— 门控与复核才有', () => {
    // 收窄任务段的工具等于推翻 bot md 关于它自己的说法（它的正文就是按那份清单写的）；
    // 门控是共享内置件，锁成零工具才防得住用户覆盖它之后长出工具
    const script = botChat().script
    const at = (marker: string): number => {
      const i = script.indexOf(marker)
      expect(i, marker).toBeGreaterThanOrEqual(0)
      return i
    }
    const gateCall = script.slice(at('1 ── Intent'), at('2 ── Answerable in one line'))
    const taskCall = script.slice(at('4 ── The task agent'))
    expect(gateCall).toContain('tools: []')
    expect(taskCall).not.toContain('tools:')
    expect(taskCall).toContain('schema: schemas.reply')
    // 散文兜底只给任务段：有人在等答案。门控与复核要的是裁决，散文对它们没有意义
    expect(taskCall).toContain("fallback: 'prose'")
    expect(gateCall).not.toContain('fallback')
  })

  it('BC-6 【刻意不写】没有 attached 提示词块，也没有任何一句宣告附件张数', () => {
    // 取不到附件时那句话就是在诱导幻觉，而图片本来就以 user 消息的形式在上下文里
    const wf = botChat()
    expect(Object.keys(wf.prompts)).not.toContain('attached')
    for (const [name, body] of Object.entries(wf.prompts)) {
      expect(body, name).not.toMatch(/attach|image/i)
    }
    // 转交本身仍在：句柄经 run 的 attach 选项走，不经提示词
    expect(wf.script).toContain('attach: input.message.attachments')
  })

  it('BC-7 【刻意不写】没有任何提示词带 notesBlock —— bot 的档案不在 prompt 里，它经 systemContext 走', () => {
    // 门控段曾被单独喂一份截断过的笔记；现在人设与记忆整篇追加在每一段的系统提示词末尾
    // （renderBotContext），提示词里再拼一份等于让模型看到同一批事实两次、还是截断过的那份
    const wf = botChat()
    expect(wf.script).not.toContain('notesBlock')
    expect(wf.script).not.toContain('trimNotes')
    for (const [name, body] of Object.entries(wf.prompts)) {
      expect(body, name).not.toContain('notesBlock')
      expect(body, name).not.toMatch(/remembers/i)
    }
    // 提示词里给门控的只有身份两项：显示名 + 描述（判相关性的材料），档案本身不在
    expect(wf.prompts.gate).toContain('{{bot.displayName}} — {{bot.description}}')
  })

  it('BC-8 失败文案不在 md 里：五个失败块已退役，文案归宿主 i18n（bot.gateBroken 等）', () => {
    // 「配置错」「超时」「跑挂了」对用户的意味仍然不同 —— 区分的责任在 botService.failureCopy
    // （按引擎交回的 errorCode / errorStep 选句），不在脚本。md 里再长出这些块就是两处各说一套
    for (const name of ['taskNoAgent', 'taskTimeout', 'taskFailed', 'gateBroken', 'gateTimeout']) {
      expect(Object.keys(botChat().prompts), name).not.toContain(name)
    }
  })

  it('BC-9 入参 schema 钉板：四个 required 键，agents 声明 intent/task 必填、recheck 可选', () => {
    // 这是宿主（botService 的 invoke input）与管线之间的接线契约；引擎按它做 required 校验
    // （含沿 properties 递归的嵌套 required —— 漏填必填槽位在起跑前就被拦下并按路径点名）
    type Prop = { type?: string; required?: string[]; properties?: Record<string, unknown> }
    const schema = botChat().inputSchema as { required: string[]; properties: Record<string, Prop> }
    expect(schema.required).toEqual(['bot', 'agents', 'session', 'message'])
    expect(schema.properties.bot.required).toEqual(['name', 'displayName', 'description', 'file'])
    expect(schema.properties.agents.type).toBe('object')
    expect(schema.properties.agents.required).toEqual(['intent', 'task'])
    expect(Object.keys(schema.properties.agents.properties!)).toEqual(['intent', 'task', 'recheck'])
    expect(schema.properties.session.required).toEqual(['id'])
    expect(schema.properties.message.required).toEqual(['id', 'text'])
    expect(schema.properties.window.type).toBe('array')
    // 退役入参不在 schema 里
    for (const gone of ['occasion', 'notes', 'since']) {
      expect(Object.keys(schema.properties), gone).not.toContain(gone)
    }
  })

  it('BC-10 槽位表（agentSlotsOf）：intent / task 必填、recheck 可选，各带一句提示语', () => {
    // 设置页的槽位下拉与宿主的 resolvePipeline 都读这一张表 —— 没有宿主侧的缺省表，
    // 哪些槽位存在、哪些必填，管线文件说了算
    const slots = agentSlotsOf(botChat())
    expect(slots.map((s) => [s.role, s.required])).toEqual([
      ['intent', true],
      ['task', true],
      ['recheck', false]
    ])
    for (const slot of slots) expect(slot.description, slot.role).toBeTruthy()
    // recheck 的提示语要说明缺省回落 intent（脚本里 `input.agents.recheck || input.agents.intent`）
    expect(slots.find((s) => s.role === 'recheck')!.description).toMatch(/defaults to intent/)
  })
})

/**
 * 内置工作流的**多语言交付面** —— 逐份内置 × 三门语言扫一遍，守的是「每份内置都真有三种
 * 语言、每种语言都真有一个人读的名字」。逐份的逐字节纪律（脚本/schema 同 en）归各自的
 * `*Localization.test.ts`；这里只管交付面，不重复那边的钉板。
 *
 * 两条写法上的纪律，都是为了不让用例空转：
 *  - 语言表**硬编码** `['en','zh','ja']`，不取 `Object.keys(spec.sources)` —— 后者会让一份
 *    只有 en 的内置「按自己声明的语言全绿」，而漏交的两门语言正是本节要抓的东西；
 *  - 一律 `buildBuiltinWorkflow(spec, …)` 逐份构建并断非 null，不遍历 `buildBuiltinWorkflows()`
 *    的结果 —— 后者 filter 掉解析失败的项，一份写坏的本地化 md 会直接从数组里消失，
 *    循环于是照样全绿。
 *
 * 用例清单（WD-4/WD-5 为读实现后的白盒补充）：
 *  - WD-1 每份内置 × 每门语言都有真名字：构建非 null、displayName 非空且不等于 slug
 *  - WD-2 名字确实翻译过：zh / ja 的 displayName 各自与 en 不同
 *  - WD-3 每份内置都齐三门语言：sources 键恰 {en, ja, zh}
 *  - WD-4（白盒）设置页那条读取路径也吃本地化：getBuiltinWorkflowSource 回的正是该语言原文
 *  - WD-5（白盒）语言回退：zh-CN → zh，未知语言 / 缺省 → en
 */
describe('内置工作流 —— 三语言交付面（逐份 × 逐语言）', () => {
  /** 硬编码：这就是本节要守的清单本身，绝不从 spec.sources 反推（见上方注释） */
  const LANGS = ['en', 'zh', 'ja'] as const

  /** 逐份构建并断非 null → {内置名: displayName}；language 省略即走缺省路径 */
  const displayNames = (language?: string): Record<string, string> =>
    Object.fromEntries(
      BUILTIN_WORKFLOW_SPECS.map((spec) => {
        const wf = buildBuiltinWorkflow(spec, language === undefined ? {} : { language })
        expect(wf, `${spec.name} @ ${language ?? '(缺省)'} 构建失败`).not.toBeNull()
        return [spec.name, wf!.displayName]
      })
    )

  it('WD-1 每份内置 × 每门语言都有一个真名字（非空且不等于 slug）', () => {
    // 解析器对「缺 shuvix-displayName」「写了空串」「只有空白」一律回落到 slug，
    // 所以这一条断言就把三种漏译形态一起抓了
    for (const spec of BUILTIN_WORKFLOW_SPECS) {
      for (const language of LANGS) {
        const wf = buildBuiltinWorkflow(spec, { language })
        expect(wf, `${spec.name} 的 ${language} 版构建失败`).not.toBeNull()
        expect(wf!.displayName.trim(), `${spec.name} @ ${language} 的 displayName 为空`).not.toBe(
          ''
        )
        expect(wf!.displayName, `${spec.name} @ ${language} 的 displayName 回落成了 slug`).not.toBe(
          spec.name
        )
      }
    }
  })

  it('WD-2 名字确实翻译过：zh / ja 的 displayName 与 en 不同', () => {
    // 这条正是「只放了一份 .md 就交差」的破绽：整文件回落会把 en 那份原样发给 zh，
    // WD-1 仍然全绿（名字非空、也不等于 slug），只有这里能看出没翻
    const en = displayNames('en')
    for (const language of ['zh', 'ja'] as const) {
      const localized = displayNames(language)
      for (const spec of BUILTIN_WORKFLOW_SPECS) {
        expect(
          localized[spec.name],
          `${spec.name} 的 ${language} displayName 与 en 相同（多半是漏了 ${language} 那份 md）`
        ).not.toBe(en[spec.name])
      }
    }
  })

  it('WD-3 每份内置都齐三门语言：sources 键恰 en / ja / zh', () => {
    // 恰等而非包含：应用就三门语言，多出第四个键应当是一次有意的编辑，顺手改这里
    for (const spec of BUILTIN_WORKFLOW_SPECS) {
      expect(Object.keys(spec.sources).sort(), `${spec.name} 的语言集合漂移`).toEqual([
        'en',
        'ja',
        'zh'
      ])
    }
  })

  it('WD-4（白盒）设置页的原文读取路径也吃本地化：getBuiltinWorkflowSource 回该语言原文', () => {
    // 这是第二条读取路径：工作流设置页只读展示内置正文、并以它做「创建覆盖副本」的初值。
    // 它与 buildBuiltinWorkflow 各走各的 pickLocalizedSource，可以单独退化成恒取 en
    for (const spec of BUILTIN_WORKFLOW_SPECS) {
      for (const language of LANGS) {
        expect(
          getBuiltinWorkflowSource(spec.name, { language }),
          `${spec.name} @ ${language} 的原文读取路径没跟上本地化`
        ).toBe(spec.sources[language])
      }
    }
    expect(getBuiltinWorkflowSource('nope'), '未知内置名应回 null').toBeNull()
  })

  it('WD-5（白盒）语言回退：zh-CN → zh，未知语言 / 缺省 → en', () => {
    // 精确 → 基础语言 → en（pickLocalizedSource）。界面语言真实取值就是 i18next.language，
    // 带地区码的 zh-CN 是常态，回退塌成 en 会让整个中文安装看见英文名字
    expect(displayNames('zh-CN'), 'zh-CN 没有回退到 zh').toEqual(displayNames('zh'))
    const en = displayNames('en')
    expect(displayNames('fr'), '未知语言没有回落到 en').toEqual(en)
    expect(displayNames(), '缺省语言没有回落到 en').toEqual(en)
  })
})
