/**
 * 内置工作流 auto-title 的钉板 + 真脚本端到端。
 *
 * 与 builtinAgents 的 registry.test.ts 同一哲学：md 是唯一事实源，断言一律打在
 * **解析后的产物**上 —— frontmatter/脚本/schema 块任何一处写坏，buildBuiltinWorkflow
 * 返回 null，下面的用例立刻失败。端到端一节把真实 md 的真脚本放进 AsyncFunction 引擎
 * 真跑：两条绑定（quick/refine）的 when 条件、titler 派发的 prompt 组装、结果契约
 * 透传与 journal 落点全部走真代码，只有 manager 与档案解析是 fake。
 */
import { describe, expect, it, vi } from 'vitest'
import {
  AUTO_TITLE_WORKFLOW_SPEC,
  BUILTIN_WORKFLOW_NAMES,
  buildBuiltinWorkflow,
  buildBuiltinWorkflows
} from '../builtinWorkflows'
import { createWorkflowEngine, type WorkflowScriptEngine } from '../engine'
import type { WorkflowRegistryEntry } from '../engine'
import type { TriggerPayloadMap } from '../triggerPoints'
import type { RunTaskParams, SubAgentManager } from '../../subagent/manager'
import type { InProcessAgentType } from '../../subagent/types'

const autoTitle = (): NonNullable<ReturnType<typeof buildBuiltinWorkflow>> =>
  buildBuiltinWorkflow(AUTO_TITLE_WORKFLOW_SPEC, {})!

describe('auto-title — 结构钉板', () => {
  it('buildBuiltinWorkflows({}) 恰含 auto-title 且解析非 null；BUILTIN_WORKFLOW_NAMES 含之', () => {
    const all = buildBuiltinWorkflows({})
    expect(all.map((w) => w.name)).toEqual(['auto-title'])
    expect(BUILTIN_WORKFLOW_NAMES.has('auto-title')).toBe(true)
    expect(autoTitle()).not.toBeNull()
  })

  it('绑定钉板：恰两条 —— quick（prompt-accepted + isDefaultTitle）与 refine（turn-completed + 三条件）', () => {
    const bindings = autoTitle().bindings
    expect(bindings).toHaveLength(2)
    expect(bindings[0].trigger).toBe('session.prompt-accepted')
    expect(bindings[0].when).toBe('event.isDefaultTitle')
    expect(bindings[1].trigger).toBe('session.turn-completed')
    expect(bindings[1].when).toContain('titleAutoGenerated')
    expect(bindings[1].when).toContain('turnCount == 2')
    expect(bindings[1].when).toContain('textMessageCount >= 3')
  })

  it('schemas.result：顶层 object 且 required=[title]', () => {
    const schema = autoTitle().schemas.result
    expect(schema.type).toBe('object')
    expect(schema.required).toEqual(['title'])
  })

  it('结构缺省钉板：concurrency skip、无 model、无 limits', () => {
    const wf = autoTitle()
    expect(wf.concurrency).toBe('skip')
    expect(wf.model).toBeUndefined()
    expect(wf.limits).toEqual({})
  })
})

// ── 真脚本端到端：AsyncFunction 引擎 + fake manager/档案 ──

const AsyncFunction = Object.getPrototypeOf(async () => {}).constructor as new (
  ...args: string[]
) => (...vals: unknown[]) => Promise<unknown>
const scriptEngine: WorkflowScriptEngine = {
  compile: () => ({ ok: true }),
  execute: async (source, api) =>
    new AsyncFunction(...Object.keys(api), source)(...Object.values(api))
}

const TITLER: InProcessAgentType = {
  name: 'titler',
  displayName: 'Titler',
  description: '',
  tools: ['session-config'],
  systemPrompt: 'You name chat sessions.'
}

function makeAutoTitleEngine(): {
  engine: ReturnType<typeof createWorkflowEngine>
  runTask: ReturnType<typeof vi.fn>
  records: Array<Record<string, unknown>>
  waitEnd: () => Promise<void>
} {
  const records: Array<Record<string, unknown>> = []
  const runTask = vi.fn(async () => ({
    result: JSON.stringify({ title: 'X' }),
    structured: { title: 'X' }
  }))
  const entries: WorkflowRegistryEntry[] = [
    { file: autoTitle(), source: 'builtin', autorunEnabled: true }
  ]
  const engine = createWorkflowEngine({
    manager: { runTask } as unknown as SubAgentManager,
    script: scriptEngine,
    listWorkflows: () => entries,
    resolveAgentProfile: (ref) => (ref === 'titler' ? TITLER : null),
    resolveRunModel: async () => ({ provider: 'p', model: 'm', capabilities: {} }),
    onRecord: (_name, _runId, rec) => records.push(rec),
    env: { host: 'desktop', platform: 'darwin' }
  })
  return {
    engine,
    runTask,
    records,
    waitEnd: () =>
      vi.waitFor(() => {
        expect(records.some((r) => r.type === 'end')).toBe(true)
      })
  }
}

const promptPayload = (
  over: Partial<TriggerPayloadMap['session.prompt-accepted']> = {}
): TriggerPayloadMap['session.prompt-accepted'] => ({
  sessionId: 's1',
  profileName: 'default',
  title: 'New Chat',
  isDefaultTitle: true,
  promptText: 'hello',
  ...over
})

const turnPayload = (
  over: Partial<TriggerPayloadMap['session.turn-completed']> = {}
): TriggerPayloadMap['session.turn-completed'] => ({
  sessionId: 's1',
  profileName: 'default',
  title: 'Quick title',
  isDefaultTitle: false,
  titleAutoGenerated: true,
  turnCount: 2,
  textMessageCount: 3,
  recentText: 'User: a\nAssistant: b',
  ...over
})

describe('auto-title — quick 端到端（真脚本）', () => {
  it('prompt-accepted + isDefaultTitle → 派发 titler 恰一次，契约/描述/归属逐项落位，end ok:true', async () => {
    const { engine, runTask, records, waitEnd } = makeAutoTitleEngine()
    engine.fire('session.prompt-accepted', promptPayload())
    await waitEnd()

    expect(runTask).toHaveBeenCalledTimes(1)
    const params = runTask.mock.calls[0][0] as RunTaskParams
    expect(params.agentType.name).toBe('titler')
    expect(params.prompt).toContain('hello')
    expect(params.prompt).toContain('<conversation>')
    expect(params.description).toBe('session title')
    expect(params.resultContract?.schema).toEqual(autoTitle().schemas.result)
    expect(params.resultContract?.sourceLabel).toBe('auto-title')
    expect(params.parentSessionId).toBe('s1')

    const end = records.find((r) => r.type === 'end')!
    expect(end.ok).toBe(true)
    expect(end.output).toEqual({ title: 'X' })
    expect(records.some((r) => r.type === 'log' && r.message === 'title applied: X')).toBe(true)
  })

  it('quick 反例：isDefaultTitle:false → 零派发', async () => {
    const { engine, runTask, records } = makeAutoTitleEngine()
    engine.fire('session.prompt-accepted', promptPayload({ isDefaultTitle: false }))
    expect(records).toEqual([])
    expect(runTask).not.toHaveBeenCalled()
  })
})

describe('auto-title — refine 端到端（真脚本）', () => {
  it('turn-completed 三条件齐 → 派发且 prompt 含 recentText', async () => {
    const { engine, runTask, waitEnd } = makeAutoTitleEngine()
    engine.fire('session.turn-completed', turnPayload())
    await waitEnd()
    expect(runTask).toHaveBeenCalledTimes(1)
    expect((runTask.mock.calls[0][0] as RunTaskParams).prompt).toContain('User: a\nAssistant: b')
  })

  it.each([
    ['titleAutoGenerated:false', { titleAutoGenerated: false }],
    ['turnCount 1', { turnCount: 1 }],
    ['turnCount 3', { turnCount: 3 }],
    ['textMessageCount 2', { textMessageCount: 2 }]
  ])('refine 反例 %s → 零派发', (_label, over) => {
    const { engine, runTask, records } = makeAutoTitleEngine()
    engine.fire('session.turn-completed', turnPayload(over))
    expect(records).toEqual([])
    expect(runTask).not.toHaveBeenCalled()
  })
})

describe('auto-title — 摘录裁尾', () => {
  it('promptText 2000 字 → 发出的 prompt 里 <conversation> 摘录 ≤1000 字', async () => {
    const { engine, runTask, waitEnd } = makeAutoTitleEngine()
    engine.fire('session.prompt-accepted', promptPayload({ promptText: 'x'.repeat(2000) }))
    await waitEnd()
    const prompt = (runTask.mock.calls[0][0] as RunTaskParams).prompt
    const excerpt = /<conversation>\n([\s\S]*?)\n<\/conversation>/.exec(prompt)?.[1]
    expect(excerpt).toBeDefined()
    expect(excerpt!.length).toBeLessThanOrEqual(1000)
  })
})
