/**
 * 内置工作流 auto-title 的钉板 + 真脚本端到端。
 *
 * 与 builtinAgents 的 registry.test.ts 同一哲学：md 是唯一事实源，断言一律打在
 * **解析后的产物**上 —— frontmatter/脚本/schema 块任何一处写坏，buildBuiltinWorkflow
 * 返回 null，下面的用例立刻失败。端到端一节把真实 md 的真脚本放进 AsyncFunction 引擎
 * 真跑：两条绑定（quick/refine）的 when 条件、titler 派发的 prompt 组装、结果契约
 * 透传与 journal 落点全部走真代码，只有 manager 与档案解析是 fake。
 */
import { describe, expect, it, vi } from 'vitest'
import {
  AUTO_TITLE_WORKFLOW_SPEC,
  buildBuiltinWorkflow,
  buildBuiltinWorkflows
} from '../builtinWorkflows'
import { createWorkflowEngine, type WorkflowScriptEngine } from '../engine'
import type { WorkflowRegistryEntry } from '../engine'
import type { TriggerPayloadMap } from '../triggerPoints'
import type { RunTaskParams, SubAgentManager } from '../../subagent/manager'
import type { InProcessAgentType } from '../../subagent/types'
import type { ParsedWorkflowFile } from '../workflowFile'

const autoTitle = (): NonNullable<ReturnType<typeof buildBuiltinWorkflow>> =>
  buildBuiltinWorkflow(AUTO_TITLE_WORKFLOW_SPEC, {})!

describe('auto-title — 结构钉板', () => {
  it('buildBuiltinWorkflows({}) 的内置清单是钉板：auto-title + bot-chat，都解析非 null', () => {
    // 保持 toEqual 的严格性 —— 内置清单多一条少一条都该在这里现形
    const all = buildBuiltinWorkflows({})
    expect(all.map((w) => w.name)).toEqual(['auto-title', 'bot-chat'])
    expect(autoTitle()).not.toBeNull()
  })

  it('绑定钉板：恰两条 —— quick（prompt-accepted + isDefaultTitle）与 refine（turn-completed + 三条件）', () => {
    const bindings = autoTitle().bindings
    expect(bindings).toHaveLength(2)
    expect(bindings[0].trigger).toBe('session.prompt-accepted')
    expect(bindings[0].when).toBe('event.isDefaultTitle')
    expect(bindings[1].trigger).toBe('session.turn-completed')
    expect(bindings[1].when).toContain('titleAutoGenerated')
    expect(bindings[1].when).toContain('turnCount == 2')
    expect(bindings[1].when).toContain('textMessageCount >= 3')
  })

  it('schemas.result：顶层 object 且 required=[title]', () => {
    const schema = autoTitle().schemas.result
    expect(schema.type).toBe('object')
    expect(schema.required).toEqual(['title'])
  })

  it('结构缺省钉板：concurrency skip、无 limits（模型跟随会话/被派发 agent 的声明）', () => {
    const wf = autoTitle()
    expect(wf.concurrency).toBe('skip')
    expect(wf.limits).toEqual({})
  })
})

// ── 真脚本端到端：AsyncFunction 引擎 + fake manager/档案 ──

const AsyncFunction = Object.getPrototypeOf(async () => {}).constructor as new (
  ...args: string[]
) => (...vals: unknown[]) => Promise<unknown>
const scriptEngine: WorkflowScriptEngine = {
  compile: () => ({ ok: true }),
  execute: async (source, api) =>
    new AsyncFunction(...Object.keys(api), source)(...Object.values(api))
}

const TITLER: InProcessAgentType = {
  name: 'titler',
  displayName: 'Titler',
  description: '',
  tools: ['session-config'],
  systemPrompt: 'You name chat sessions.'
}

function makeAutoTitleEngine(
  overrideRunTask?: (p: RunTaskParams) => Promise<{ result: string; structured?: unknown }>
): {
  engine: ReturnType<typeof createWorkflowEngine>
  runTask: ReturnType<typeof vi.fn>
  records: Array<Record<string, unknown>>
  metas: () => Array<Record<string, unknown>>
  waitEnd: (n?: number) => Promise<void>
} {
  const records: Array<Record<string, unknown>> = []
  const runTask = vi.fn(
    overrideRunTask ??
      (async () => ({
        result: JSON.stringify({ title: 'X' }),
        structured: { title: 'X' }
      }))
  )
  const entries: WorkflowRegistryEntry[] = [{ file: autoTitle(), source: 'builtin' }]
  const engine = createWorkflowEngine({
    manager: { runTask } as unknown as SubAgentManager,
    script: scriptEngine,
    listWorkflows: () => entries,
    resolveAgentProfile: (ref) => (ref === 'titler' ? TITLER : null),
    resolveRunModel: async () => ({ provider: 'p', model: 'm', capabilities: {} }),
    onRecord: (_name, _runId, rec) => records.push(rec),
    env: { host: 'desktop', platform: 'darwin' }
  })
  return {
    engine,
    runTask,
    records,
    metas: () => records.filter((r) => r.type === 'meta'),
    waitEnd: (n = 1) =>
      vi.waitFor(() => {
        expect(records.filter((r) => r.type === 'end').length).toBeGreaterThanOrEqual(n)
      })
  }
}

const promptPayload = (
  over: Partial<TriggerPayloadMap['session.prompt-accepted']> = {}
): TriggerPayloadMap['session.prompt-accepted'] => ({
  sessionId: 's1',
  profileName: 'default',
  title: 'New Chat',
  isDefaultTitle: true,
  promptText: 'hello',
  ...over
})

const turnPayload = (
  over: Partial<TriggerPayloadMap['session.turn-completed']> = {}
): TriggerPayloadMap['session.turn-completed'] => ({
  sessionId: 's1',
  profileName: 'default',
  title: 'Quick title',
  isDefaultTitle: false,
  titleAutoGenerated: true,
  turnCount: 2,
  textMessageCount: 3,
  recentText: 'User: a\nAssistant: b',
  ...over
})

describe('auto-title — quick 端到端（真脚本）', () => {
  it('prompt-accepted + isDefaultTitle → 派发 titler 恰一次，契约/描述/归属逐项落位，end ok:true', async () => {
    const { engine, runTask, records, waitEnd } = makeAutoTitleEngine()
    engine.fire('session.prompt-accepted', promptPayload())
    await waitEnd()

    expect(runTask).toHaveBeenCalledTimes(1)
    const params = runTask.mock.calls[0][0] as RunTaskParams
    expect(params.agentType.name).toBe('titler')
    expect(params.prompt).toContain('hello')
    expect(params.prompt).toContain('<conversation>')
    expect(params.description).toBe('session title')
    expect(params.resultContract?.schema).toEqual(autoTitle().schemas.result)
    expect(params.resultContract?.sourceLabel).toBe('auto-title')
    expect(params.parentSessionId).toBe('s1')

    const end = records.find((r) => r.type === 'end')!
    expect(end.ok).toBe(true)
    expect(end.output).toEqual({ title: 'X' })
    expect(records.some((r) => r.type === 'log' && r.message === 'title applied: X')).toBe(true)
  })

  it('quick 反例：isDefaultTitle:false → 零派发', async () => {
    const { engine, runTask, records } = makeAutoTitleEngine()
    engine.fire('session.prompt-accepted', promptPayload({ isDefaultTitle: false }))
    expect(records).toEqual([])
    expect(runTask).not.toHaveBeenCalled()
  })
})

describe('auto-title — refine 端到端（真脚本）', () => {
  it('turn-completed 三条件齐 → 派发且 prompt 含 recentText', async () => {
    const { engine, runTask, waitEnd } = makeAutoTitleEngine()
    engine.fire('session.turn-completed', turnPayload())
    await waitEnd()
    expect(runTask).toHaveBeenCalledTimes(1)
    expect((runTask.mock.calls[0][0] as RunTaskParams).prompt).toContain('User: a\nAssistant: b')
  })

  it.each([
    ['titleAutoGenerated:false', { titleAutoGenerated: false }],
    ['turnCount 1', { turnCount: 1 }],
    ['turnCount 3', { turnCount: 3 }],
    ['textMessageCount 2', { textMessageCount: 2 }]
  ])('refine 反例 %s → 零派发', (_label, over) => {
    const { engine, runTask, records } = makeAutoTitleEngine()
    engine.fire('session.turn-completed', turnPayload(over))
    expect(records).toEqual([])
    expect(runTask).not.toHaveBeenCalled()
  })
})

describe('auto-title — 摘录裁尾', () => {
  it('promptText 2000 字 → 发出的 prompt 里 <conversation> 摘录 ≤1000 字', async () => {
    const { engine, runTask, waitEnd } = makeAutoTitleEngine()
    engine.fire('session.prompt-accepted', promptPayload({ promptText: 'x'.repeat(2000) }))
    await waitEnd()
    const prompt = (runTask.mock.calls[0][0] as RunTaskParams).prompt
    const excerpt = /<conversation>\n([\s\S]*?)\n<\/conversation>/.exec(prompt)?.[1]
    expect(excerpt).toBeDefined()
    expect(excerpt!.length).toBeLessThanOrEqual(1000)
  })
})

describe('auto-title — 分道（M2′ 顺带修掉的既有缺陷）', () => {
  /** 挂起的 titler 派发：测试端显式放行 */
  const gatedTitler = (
    gates: Array<() => void>
  ): (() => Promise<{ result: string; structured?: unknown }>) => {
    return () =>
      new Promise((resolve) =>
        gates.push(() =>
          resolve({ result: JSON.stringify({ title: 'X' }), structured: { title: 'X' } })
        )
      )
  }

  it('迁移承诺：md 一字未改 —— 两条绑定都没有 key，缺省键由埋点 scope 推导', () => {
    expect(autoTitle().bindings.every((b) => b.key === undefined)).toBe(true)
  })

  it('两个会话同时 turn-completed → 各起一个 run（refine 是一次性窗口，被 skip 即永久丢标题）', async () => {
    const gates: Array<() => void> = []
    const { engine, runTask, metas, waitEnd } = makeAutoTitleEngine(gatedTitler(gates))

    engine.fire('session.turn-completed', turnPayload({ sessionId: 's1' }))
    engine.fire('session.turn-completed', turnPayload({ sessionId: 's2' }))
    await vi.waitFor(() => expect(gates).toHaveLength(2))

    expect(metas().map((m) => m.lane)).toEqual(['auto-title\u0000s1', 'auto-title\u0000s2'])
    expect(runTask).toHaveBeenCalledTimes(2)

    gates.forEach((release) => release())
    await waitEnd(2)
  })

  it('同一会话内 quick 与 refine 仍互斥（同道按文件策略 skip）', async () => {
    const gates: Array<() => void> = []
    const { engine, metas, waitEnd } = makeAutoTitleEngine(gatedTitler(gates))

    engine.fire('session.prompt-accepted', promptPayload({ sessionId: 's1' }))
    await vi.waitFor(() => expect(gates).toHaveLength(1))
    engine.fire('session.turn-completed', turnPayload({ sessionId: 's1' }))

    expect(metas()).toHaveLength(1)
    gates[0]()
    await waitEnd()
  })
})

describe('bot-chat — 骨架管线的结构钉板', () => {
  const botChat = (): ParsedWorkflowFile =>
    buildBuiltinWorkflows({}).find((w) => w.name === 'bot-chat')!

  it('没有任何埋点绑定 —— 它只由会话按名 invoke', () => {
    expect(botChat().bindings).toEqual([])
  })

  it('concurrency 为 parallel：引擎重入彻底让位，独占由宿主的 turn() 提供', () => {
    // 这两件事是**两个粒度**：引擎重入管「要不要起 run」，mailbox 管「已在跑的 run
    // 何时进独占段」。声明 parallel 才不会让两者打架
    expect(botChat().concurrency).toBe('parallel')
  })

  it('四个契约块齐全且都是 type:object（M5′/M8′ 直接消费，此刻已是最终形态）', () => {
    const schemas = botChat().schemas
    expect(Object.keys(schemas).sort()).toEqual(['intent', 'intentSolo', 'recheck', 'reply'])
    for (const [name, schema] of Object.entries(schemas)) {
      expect((schema as { type?: string }).type, name).toBe('object')
    }
  })

  it('intent 有 ignore、intentSolo 没有 —— 1:1 会话里沉默与坏掉分不开', () => {
    const enumOf = (n: string): string[] =>
      (botChat().schemas[n] as Record<string, Record<string, Record<string, string[]>>>).properties
        .decision.enum ?? []
    expect(enumOf('intent')).toContain('ignore')
    expect(enumOf('intentSolo')).not.toContain('ignore')
  })

  it('脚本一律读 input.* —— 脚本作用域不平铺 input（裸名是 ReferenceError）', () => {
    const script = botChat().script
    // 平铺只发生在提示词块的渲染作用域；脚本 global 只有基础 API + 调用方装配的那几个。
    // 逐个钉住骨架用到的字段都带 input. 前缀
    for (const field of ['occasion', 'skeletonDecision', 'bot.displayName', 'message.text']) {
      expect(script, field).toContain(`input.${field}`)
    }
    // 三个装配进来的函数都用上了 —— 它们正是「这份 md 是 bot 管线」的全部含义
    for (const api of ['claim(', 'turn(', 'say(']) expect(script).toContain(api)
  })

  it('刻意不含 md prompt 块：提示词随 M5′ 的真意图段一起落，不留死文本', () => {
    expect(botChat().prompts).toEqual({})
  })
})
