/**
 * 图表契约文件（`shuvix: chart v1`）—— 可视化智能体创建/维护的单图表 markdown 的机器可读契约。
 *
 * 契约形态：YAML frontmatter（与 agent 定义文件同形）+ 正文恰好一个 mermaid 代码块，
 * 除此之外不含任何内容：
 *
 *   ---
 *   shuvix: chart v1
 *   description: MANAGED BY VISUALIZATION AGENT. ...
 *   shuvix-chart-requirement: <用户绘图需求>
 *   ---
 *
 *   ```mermaid
 *   flowchart TD ...
 *   ```
 *
 * 设计取舍：
 *   - frontmatter 载体 —— 与 agent 定义文件（`shuvix: agent v1`）共用一套元数据词汇表
 *     （`shuvix` 类型标记 + `description` 人读说明），全仓一种文件格式而非两种。
 *     ShuviX 自己的预览（FilePreview / ChartView / previewTool）只提取 mermaid 单独渲染，
 *     frontmatter 不进视图；代价是把图表文件提交进 git 后，GitHub 等通用渲染器会把
 *     frontmatter 显示成元数据表 —— 这是换取格式统一的已知代价（旧载体 HTML 注释
 *     在通用渲染器中不可见，但要为图表单独维护第二套元数据形态）。
 *   - 判别只做正则、不引 YAML 解析器 —— chat-protocol 是零依赖叶子包，判别在每次文件
 *     预览时都跑，且没有任何消费方需要读 `shuvix-chart-requirement` / `description` 的值。
 *   - frontmatter 必须落在文件开头 —— 正文里的 `---` 分隔线加一行 `shuvix: chart`
 *     不会被误判为图表文件（frontmatter 提取与标记读取收敛在 shuvixMdContract.ts）。
 *   - 兼容旧载体 —— 契约初版用的是 HTML 注释（`<!-- shuvix:chart v1`），用户磁盘上的
 *     既有图表文件仍按图表识别；写入恒用 frontmatter，旧文件经智能体下一次修订自动
 *     转换（与 agent md 的「写入恒有、读取可选」同策）。
 *   - 文件名 `*-graph.md` 只是约定（可发现性），身份认定只看标记 —— 改名不破坏，
 *     无标记的同名文件按普通 markdown 处理，零误伤。
 *
 * 消费方：app-shell FilePreview/ChartView、agent-runtime previewTool（检测 + 提取渲染）
 * 与 visualization 系统提示模板 —— 单一真源，UI 与提示词不漂移。
 */
import { detectShuvixMarker } from './shuvixMdContract'

/**
 * 文件类型标记的 frontmatter key 与值 —— `shuvix: chart v1`
 * （与 agent 定义文件的 `shuvix: agent v1` 同形；判别本身版本无关，为未来演进留位）。
 */
export const CHART_FILE_MARKER_KEY = 'shuvix'
export const CHART_FILE_MARKER = 'chart v1'

/** 人读管理横幅 —— 写在 frontmatter 的 `description` 字段：读到原始文件的智能体/人类都会看到改道指引 */
export const CHART_FILE_BANNER =
  'MANAGED BY VISUALIZATION AGENT. Do not edit this file by hand — dispatch the `agent` tool with name "visualization" for any change.'

/**
 * 绘图需求字段 —— ShuviX 自有字段带 `shuvix-` 前缀（与 agent md 的 `shuvix-tools` 等同策：
 * 语义只对 ShuviX 成立，带前缀避免文件流转到其他应用时被误读）。仅供人与智能体阅读，
 * 无消费方解析其值。
 */
export const CHART_FILE_REQUIREMENT_KEY = 'shuvix-chart-requirement'

/** 旧载体：标记注释首行；同样只认文件开头 */
const LEGACY_MARKER_RE = /^<!--\s*shuvix:chart\b/

/** 该文本是否为图表契约文件（新旧两种载体都认） */
export function isChartFile(text: string): boolean {
  const head = text.replace(/^\uFEFF/, '').replace(/^\s+/, '')
  if (LEGACY_MARKER_RE.test(head)) return true
  return detectShuvixMarker(head)?.type === 'chart'
}

/** mermaid 围栏块（m 标志下按行首/行尾锚定；容忍围栏缩进与 \r\n） */
const MERMAID_FENCE_RE = /^[ \t]*```[ \t]*mermaid[ \t]*\r?\n([\s\S]*?)\r?\n[ \t]*```[ \t]*$/gim

/**
 * 提取图表源码：仅当文本带契约标记且**恰好一个** mermaid 块时返回其内容，
 * 否则返回 null —— 调用方以此优雅降级回普通 markdown 预览（永远有兜底显示）。
 */
export function extractChartMermaid(text: string): string | null {
  if (!isChartFile(text)) return null
  const matches = [...text.matchAll(MERMAID_FENCE_RE)]
  if (matches.length !== 1) return null
  const code = matches[0][1].trim()
  return code || null
}
