/**
 * 图表契约文件（shuvix:chart）—— 可视化智能体创建/维护的单图表 markdown 的机器可读契约。
 *
 * 契约形态（v1）：文件首个非空字节必须是标记注释，首行携带判别 token；
 * 注释体内保留人读横幅（其它 Agent/人类读原始文件时的改道指引）与 requirement 行；
 * 正文恰好一个 mermaid 代码块，除此之外不含任何内容：
 *
 *   <!-- shuvix:chart v1
 *   MANAGED BY VISUALIZATION AGENT. ...
 *   requirement: <用户绘图需求>
 *   -->
 *
 *   ```mermaid
 *   flowchart TD ...
 *   ```
 *
 * 设计取舍：
 *   - HTML 注释载体 —— 在所有通用渲染器（GitHub / 编辑器 / 静态站点）中不可见，
 *     且 ShuviX 自己的 live-preview 已有注释隐藏（atomic-editor comment-blocks）；
 *     frontmatter 会被 GitHub 渲染成元数据表，违背「渲染后只有一个图表」。
 *   - 首行前缀判别 —— O(1)、零解析、只认文件开头：正文/代码块里出现同样字符串不会误判；
 *     `shuvix:` 命名空间避免与普通注释撞车；`v1` 为未来演进留位。
 *   - 文件名 `*-graph.md` 只是约定（可发现性），身份认定只看标记 —— 改名不破坏，
 *     无标记的同名文件按普通 markdown 处理，零误伤。
 *
 * 消费方：app-shell FilePreview/ChartView（检测 + 提取渲染）与 agent-runtime 的
 * visualization 系统提示模板（嵌入同一批常量）—— 单一真源，UI 与提示词不漂移。
 */

/** 判别 token（命名空间化；出现在标记注释首行） */
export const CHART_FILE_MARKER = 'shuvix:chart'

/** 标记注释的规范首行（智能体创建文件时逐字写入；`-->` 在注释体末行独立收尾） */
export const CHART_FILE_MARKER_LINE = '<!-- shuvix:chart v1'

/** 人读管理横幅 —— 注释体第二行；任何读到原始文件的 Agent/人类都会看到改道指引 */
export const CHART_FILE_BANNER =
  'MANAGED BY VISUALIZATION AGENT. Do not edit this file by hand — dispatch the Agent tool with agent "visualization" for any change.'

/** 首行判别：容忍 BOM 与前导空白；只认文件开头（检测窗口取前 256 字符足矣） */
const MARKER_RE = /^\uFEFF?\s*<!--\s*shuvix:chart\b/

/** 该文本是否为图表契约文件 */
export function isChartFile(text: string): boolean {
  return MARKER_RE.test(text.slice(0, 256))
}

/** mermaid 围栏块（m 标志下按行首/行尾锚定；容忍围栏缩进与 \r\n） */
const MERMAID_FENCE_RE = /^[ \t]*```[ \t]*mermaid[ \t]*\r?\n([\s\S]*?)\r?\n[ \t]*```[ \t]*$/gim

/**
 * 提取图表源码：仅当文本带契约标记且**恰好一个** mermaid 块时返回其内容，
 * 否则返回 null —— 调用方以此优雅降级回普通 markdown 预览（永远有兜底显示）。
 */
export function extractChartMermaid(text: string): string | null {
  if (!isChartFile(text)) return null
  const matches = [...text.matchAll(MERMAID_FENCE_RE)]
  if (matches.length !== 1) return null
  const code = matches[0][1].trim()
  return code || null
}
