/**
 * session-config 工具 —— auto-title 业务的执行侧收口。
 *
 * 钉住的是三条硬边界：
 *   - **目标会话恒取 ToolContext.sessionId、不收 sessionId 参数** —— schema 层就没有
 *     这个洞（LLM 抄 uuid 会抄错，「只能动自己所属会话」是比参数校验更硬的边界）；
 *   - 写入必经 sessionService.updateTitle(…, 'auto') —— titleOrigin 是
 *     `session.turn-completed` 埋点 titleAutoGenerated 的数据来源，origin 写错会让
 *     refine 阶段覆盖用户手动改过的标题；
 *   - 超长/空标题**拒绝而非静默截断**，错误文案给出实际长度与上限（纠正性引导纪律）。
 *
 * mock 手法照 agentService.test.ts：vi.mock + 动态 import；dao/sessionService/i18n/
 * toolRegistry 全部换假件，工具类直接 new 出来经 BaseTool.execute 模板驱动。
 */
import { describe, it, expect, beforeAll, beforeEach, vi } from 'vitest'
import type { ToolContext } from '../../services/toolContext'

const mocks = vi.hoisted(() => ({
  pick: vi.fn<(id: string, cols: string[]) => unknown>(),
  updateTitle: vi.fn(),
  registerBuiltinTool: vi.fn()
}))

vi.mock('../../dao/sessionDao', () => ({ sessionDao: { pick: mocks.pick } }))
vi.mock('../../services/sessionService', () => ({
  sessionService: { updateTitle: mocks.updateTitle }
}))
vi.mock('../../services/toolRegistry', () => ({ registerBuiltinTool: mocks.registerBuiltinTool }))
vi.mock('../../i18n', () => ({ t: (key: string) => key }))

type SessionConfigModule = typeof import('../sessionConfig')
let mod: SessionConfigModule
let tool: InstanceType<SessionConfigModule['SessionConfigTool']>

beforeAll(async () => {
  mod = await import('../sessionConfig')
  tool = new mod.SessionConfigTool({ sessionId: 's1' } as ToolContext)
})

beforeEach(() => {
  mocks.pick.mockReset()
  mocks.updateTitle.mockReset()
  // 缺省：普通聊天会话存在
  mocks.pick.mockReturnValue({ title: 'Old', settings: {} })
})

const setTitle = (title?: string): Promise<unknown> =>
  tool.execute('tc-1', { action: 'set-title', ...(title !== undefined ? { title } : {}) })

describe('SessionConfigTool — 参数面与目标会话边界', () => {
  it('schema 不含 sessionId（目标会话恒取 ToolContext，参数层就没有这个洞）', () => {
    expect(Object.keys(mod.SessionConfigParamsSchema.properties)).toEqual(['action', 'title'])
  })

  it('未知 action → 错误列出合法值 set-title', async () => {
    await expect(
      tool.execute('tc-1', { action: 'rename' as 'set-title', title: 'x' })
    ).rejects.toThrow(/Unknown action "rename"\. Valid actions: set-title/)
    expect(mocks.updateTitle).not.toHaveBeenCalled()
  })

  it('会话行不存在（workflow 无会话上下文 run 等场景）→ not attached to a session', async () => {
    mocks.pick.mockReturnValue(undefined)
    await expect(setTitle('T')).rejects.toThrow(/not attached to a session/)
    expect(mocks.updateTitle).not.toHaveBeenCalled()
  })

  it('笔记本会话（settings.notebookPath）→ 拒绝（标题绑定笔记文件）', async () => {
    mocks.pick.mockReturnValue({ title: 'nb.md', settings: { notebookPath: '/p/nb.md' } })
    await expect(setTitle('T')).rejects.toThrow(/notebook session/)
    expect(mocks.updateTitle).not.toHaveBeenCalled()
  })
})

describe('SessionConfigTool — set-title 校验与写入', () => {
  it.each([
    ['缺失', undefined],
    ['空串', ''],
    ['纯空白', '   ']
  ])('title %s → Pass the new title', async (_label, title) => {
    await expect(setTitle(title)).rejects.toThrow(/Pass the new title/)
    expect(mocks.updateTitle).not.toHaveBeenCalled()
  })

  it('61 字 → 错误含实际长度 61 与上限 60；恰 60 字 → 通过', async () => {
    await expect(setTitle('a'.repeat(61))).rejects.toThrow(
      /Title is 61 characters — keep it at most 60/
    )
    expect(mocks.updateTitle).not.toHaveBeenCalled()

    await setTitle('a'.repeat(60))
    expect(mocks.updateTitle).toHaveBeenCalledWith('s1', 'a'.repeat(60), 'auto')
  })

  it("happy path：updateTitle('s1', title, 'auto') 恰一次 + 返回 Session title set to", async () => {
    const out = (await setTitle('Fix login bug')) as {
      content: Array<{ type: string; text?: string }>
    }
    expect(mocks.updateTitle).toHaveBeenCalledTimes(1)
    expect(mocks.updateTitle).toHaveBeenCalledWith('s1', 'Fix login bug', 'auto')
    expect(out.content.map((c) => c.text).join('')).toBe('Session title set to "Fix login bug".')
  })

  it('title 先 trim 再判长与写入（前后空白不吃长度配额、不落库）', async () => {
    await setTitle(`  ${'a'.repeat(60)}  `)
    expect(mocks.updateTitle).toHaveBeenCalledWith('s1', 'a'.repeat(60), 'auto')
  })
})

describe('SessionConfigTool — 注册与描述', () => {
  it('模块加载即完成 registerBuiltinTool（name session-config、group system）', () => {
    expect(mocks.registerBuiltinTool).toHaveBeenCalledTimes(1)
    const entry = mocks.registerBuiltinTool.mock.calls[0][0] as {
      name: string
      group: string
      factory: (ctx: ToolContext) => unknown
    }
    expect(entry.name).toBe('session-config')
    expect(entry.group).toBe('system')
    expect(entry.factory({ sessionId: 's2' } as ToolContext)).toBeInstanceOf(mod.SessionConfigTool)
  })

  it('描述文案含上限 60（LLM 直接从描述得知长度约束）', () => {
    expect(mod.SESSION_CONFIG_DESCRIPTION).toContain('60')
    expect(tool.description).toContain('60')
  })
})
