/**
 * session 工具 —— auto-title 业务的执行侧收口。
 *
 * 钉住的是三条硬边界：
 *   - **目标会话恒取 ToolContext.sessionId、不收 sessionId 参数** —— schema 层就没有
 *     这个洞（LLM 抄 uuid 会抄错，「只能动自己所属会话」是比参数校验更硬的边界）；
 *   - 写入必经 sessionService.updateTitle(…, 'auto') —— titleOrigin 是
 *     `session.turn-completed` 埋点 titleAutoGenerated 的数据来源，origin 写错会让
 *     refine 阶段覆盖用户手动改过的标题；
 *   - 超长/空标题**拒绝而非静默截断**，错误文案给出实际长度与上限（纠正性引导纪律）。
 *
 * mock 手法照 agentService.test.ts：vi.mock + 动态 import；dao/sessionService/i18n/
 * toolRegistry 全部换假件，工具类直接 new 出来经 BaseTool.execute 模板驱动。
 */
import { describe, it, expect, beforeAll, beforeEach, vi } from 'vitest'
import type { ToolContext } from '../../services/toolContext'

const mocks = vi.hoisted(() => ({
  pick: vi.fn<(id: string, cols: string[]) => unknown>(),
  updateTitle: vi.fn(),
  registerBuiltinTool: vi.fn(),
  // 子会话：runner 握着全部业务规则，工具层只做参数面与文案 —— 这里整体换成假件，
  // 断言的是「转调了什么」与「结果怎么排版」，不是子会话的语义（那是 runner 的用例）
  runnerCreate: vi.fn(),
  runnerPrompt: vi.fn(),
  runnerWait: vi.fn(),
  runnerList: vi.fn(),
  runnerRead: vi.fn(),
  runnerStop: vi.fn()
}))

vi.mock('../../dao/sessionDao', () => ({ sessionDao: { pick: mocks.pick } }))
vi.mock('../../services/sessionService', () => ({
  sessionService: { updateTitle: mocks.updateTitle }
}))
vi.mock('../../services/toolRegistry', () => ({ registerBuiltinTool: mocks.registerBuiltinTool }))
vi.mock('../../services/subSessionRunner', () => ({
  DEFAULT_PROMPT_TIMEOUT_SEC: 300,
  subSessionRunner: {
    create: mocks.runnerCreate,
    prompt: mocks.runnerPrompt,
    wait: mocks.runnerWait,
    list: mocks.runnerList,
    read: mocks.runnerRead,
    stop: mocks.runnerStop
  }
}))
vi.mock('../../i18n', () => ({ t: (key: string) => key }))

type SessionModule = typeof import('../session')
let mod: SessionModule
let tool: InstanceType<SessionModule['SessionTool']>

beforeAll(async () => {
  mod = await import('../session')
  tool = new mod.SessionTool({ sessionId: 's1' } as ToolContext)
})

beforeEach(() => {
  mocks.pick.mockReset()
  mocks.updateTitle.mockReset()
  for (const fn of [
    mocks.runnerCreate,
    mocks.runnerPrompt,
    mocks.runnerWait,
    mocks.runnerList,
    mocks.runnerRead,
    mocks.runnerStop
  ]) {
    fn.mockReset()
  }
  // 缺省：普通聊天会话存在
  mocks.pick.mockReturnValue({ title: 'Old', settings: {} })
})

const setTitle = (title?: string): Promise<unknown> =>
  tool.execute('tc-1', { action: 'set-title', ...(title !== undefined ? { title } : {}) })

describe('SessionTool — 参数面与目标会话边界', () => {
  it('schema 不含 sessionId：能点名的只有 sub_session_id（且必须是自己的子会话）', () => {
    const keys = Object.keys(mod.SessionParamsSchema.properties)
    expect(keys).toEqual([
      'action',
      'title',
      'agent_profile',
      'sub_session_id',
      'message',
      'run_in_background',
      'timeout_seconds'
    ])
    // 参数面没有随 action 变多而膨胀：wait 复用 sub_session_id / timeout_seconds
    // 「改哪条会话」的选择权始终不给模型：本会话恒取 ToolContext.sessionId，
    // 而 sub_session_id 只能指向调用方自己的子会话（判定在 runner，见其用例）
    expect(keys).not.toContain('sessionId')
    expect(keys).not.toContain('session_id')
  })

  it('未知 action → 错误列出全部合法值', async () => {
    await expect(
      tool.execute('tc-1', { action: 'rename' as 'set-title', title: 'x' })
    ).rejects.toThrow(/Unknown action "rename"\. Valid actions: set-title, create-sub-session/)
    expect(mocks.updateTitle).not.toHaveBeenCalled()
  })

  it('会话行不存在（workflow 无会话上下文 run 等场景）→ not attached to a session', async () => {
    mocks.pick.mockReturnValue(undefined)
    await expect(setTitle('T')).rejects.toThrow(/not attached to a session/)
    expect(mocks.updateTitle).not.toHaveBeenCalled()
  })

  it('笔记本会话（settings.notebookPath）→ 拒绝（标题绑定笔记文件）', async () => {
    mocks.pick.mockReturnValue({ title: 'nb.md', settings: { notebookPath: '/p/nb.md' } })
    await expect(setTitle('T')).rejects.toThrow(/notebook session/)
    expect(mocks.updateTitle).not.toHaveBeenCalled()
  })
})

describe('SessionTool — set-title 校验与写入', () => {
  it.each([
    ['缺失', undefined],
    ['空串', ''],
    ['纯空白', '   ']
  ])('title %s → Pass the new title', async (_label, title) => {
    await expect(setTitle(title)).rejects.toThrow(/Pass the new title/)
    expect(mocks.updateTitle).not.toHaveBeenCalled()
  })

  it('61 字 → 错误含实际长度 61 与上限 60；恰 60 字 → 通过', async () => {
    await expect(setTitle('a'.repeat(61))).rejects.toThrow(
      /Title is 61 characters — keep it at most 60/
    )
    expect(mocks.updateTitle).not.toHaveBeenCalled()

    await setTitle('a'.repeat(60))
    expect(mocks.updateTitle).toHaveBeenCalledWith('s1', 'a'.repeat(60), 'auto')
  })

  it("happy path：updateTitle('s1', title, 'auto') 恰一次 + 返回 Session title set to", async () => {
    const out = (await setTitle('Fix login bug')) as {
      content: Array<{ type: string; text?: string }>
    }
    expect(mocks.updateTitle).toHaveBeenCalledTimes(1)
    expect(mocks.updateTitle).toHaveBeenCalledWith('s1', 'Fix login bug', 'auto')
    expect(out.content.map((c) => c.text).join('')).toBe('Session title set to "Fix login bug".')
  })

  it('title 先 trim 再判长与写入（前后空白不吃长度配额、不落库）', async () => {
    await setTitle(`  ${'a'.repeat(60)}  `)
    expect(mocks.updateTitle).toHaveBeenCalledWith('s1', 'a'.repeat(60), 'auto')
  })
})

describe('SessionTool — 注册与描述', () => {
  it('模块加载即完成 registerBuiltinTool（name session、group system）', () => {
    expect(mocks.registerBuiltinTool).toHaveBeenCalledTimes(1)
    const entry = mocks.registerBuiltinTool.mock.calls[0][0] as {
      name: string
      group: string
      factory: (ctx: ToolContext) => unknown
    }
    expect(entry.name).toBe('session')
    expect(entry.group).toBe('system')
    expect(entry.factory({ sessionId: 's2' } as ToolContext)).toBeInstanceOf(mod.SessionTool)
  })

  it('描述文案含上限 60（LLM 直接从描述得知长度约束）', () => {
    expect(mod.SESSION_DESCRIPTION).toContain('60')
    expect(tool.description).toContain('60')
  })
})

// ── 子会话的五个 action ────────────────────────────────
//
// 工具层是**翻译层**：调 runner → 有 error 就抛（文案原样，它握着准入规则）→
// 没有就把结果排版成文本。所以这里钉的是「转调了什么」与「回话长什么样」，
// 语义（准入 / 上限 / 超时降级 / 越权）全在 subSessionRunner 的用例里。

const textOf = (r: unknown): string =>
  ((r as { content: Array<{ text: string }> }).content ?? []).map((c) => c.text).join('')

const info = (
  id: string,
  title: string,
  status: 'idle' | 'running' | 'waiting-input'
): { id: string; title: string; status: typeof status; driven: boolean; updatedAt: number } => ({
  id,
  title,
  status,
  driven: false,
  updatedAt: 1
})

describe('SessionTool — 子会话 action', () => {
  it('create-sub-session：转调 runner（title/agent_profile 原样），回话含 id', async () => {
    mocks.runnerCreate.mockResolvedValue({ id: 'sub-1', title: '重构 parser' })
    const res = await tool.execute('tc-1', {
      action: 'create-sub-session',
      title: '重构 parser',
      agent_profile: 'coding'
    })
    expect(mocks.runnerCreate).toHaveBeenCalledWith('s1', {
      title: '重构 parser',
      agentProfile: 'coding'
    })
    expect(textOf(res)).toContain('sub-1')
    expect(textOf(res)).toContain('重构 parser')
  })

  it('runner 的 error 原样抛出（准入理由只有一份，工具层不复述也不改写）', async () => {
    mocks.runnerCreate.mockResolvedValue({ error: 'Chat sessions cannot have sub-sessions.' })
    await expect(tool.execute('tc-1', { action: 'create-sub-session' })).rejects.toThrow(
      'Chat sessions cannot have sub-sessions.'
    )
  })

  it('prompt-sub-session 前台：parentId 取 ToolContext，缺省超时 300s，答复在 <reply> 围栏内', async () => {
    // info 由 prompt 顺带带回（工具层不再为一个标题重投影整棵转写）
    mocks.runnerPrompt.mockResolvedValue({
      kind: 'answered',
      answer: 'DONE.',
      info: info('sub-1', 'A', 'idle')
    })
    const res = await tool.execute('tc-1', {
      action: 'prompt-sub-session',
      sub_session_id: 'sub-1',
      message: '去把测试跑绿'
    })
    expect(mocks.runnerPrompt).toHaveBeenCalledWith(
      expect.objectContaining({
        parentId: 's1',
        childId: 'sub-1',
        message: '去把测试跑绿',
        background: false,
        timeoutSeconds: 300
      })
    )
    // 子会话说的话恒在围栏内 —— 围栏外的每个字都是工具在说话
    expect(textOf(res)).toContain('<reply>\nDONE.\n</reply>')
    expect(textOf(res)).toContain('<sub-session id="sub-1"')
  })

  it('后台与超时降级的结果带 details.background —— UI 上与 bash 后台任务同一枚标签', async () => {
    const detailsOf = (r: unknown): unknown => (r as { details?: unknown }).details
    mocks.runnerPrompt.mockResolvedValue({ kind: 'started' })
    expect(
      detailsOf(
        await tool.execute('tc-1', {
          action: 'prompt-sub-session',
          sub_session_id: 'sub-1',
          message: 'go',
          run_in_background: true
        })
      )
    ).toEqual({ type: 'session', background: true })

    mocks.runnerPrompt.mockResolvedValue({ kind: 'timeout' })
    expect(
      detailsOf(
        await tool.execute('tc-1', {
          action: 'prompt-sub-session',
          sub_session_id: 'sub-1',
          message: 'go'
        })
      )
    ).toEqual({ type: 'session', background: true })

    // 前台拿到答复 = 这次调用等到底了，不是后台形态
    mocks.runnerPrompt.mockResolvedValue({
      kind: 'answered',
      answer: 'ok',
      info: info('sub-1', 'A', 'idle')
    })
    expect(
      detailsOf(
        await tool.execute('tc-1', {
          action: 'prompt-sub-session',
          sub_session_id: 'sub-1',
          message: 'go'
        })
      )
    ).toBeUndefined()
  })

  it('wait 没等到底也是后台形态（活还在跑）；settled 不是', async () => {
    const detailsOf = (r: unknown): unknown => (r as { details?: unknown }).details
    const row = { ...info('sub-1', 'A', 'running') }
    mocks.runnerWait.mockResolvedValue({ kind: 'timeout', results: [row] })
    expect(detailsOf(await tool.execute('tc-1', { action: 'wait-for-sub-sessions' }))).toEqual({
      type: 'session',
      background: true
    })

    mocks.runnerWait.mockResolvedValue({
      kind: 'settled',
      results: [{ ...info('sub-1', 'A', 'idle'), answer: 'done' }]
    })
    expect(
      detailsOf(await tool.execute('tc-1', { action: 'wait-for-sub-sessions' }))
    ).toBeUndefined()
  })

  it('后台形态与超时降级：都只给回执，**不带任何内容**（内容会永久留在上下文并被每步重发）', async () => {
    mocks.runnerPrompt.mockResolvedValue({ kind: 'started' })
    const started = textOf(
      await tool.execute('tc-1', {
        action: 'prompt-sub-session',
        sub_session_id: 'sub-1',
        message: 'go',
        run_in_background: true
      })
    )
    expect(mocks.runnerPrompt).toHaveBeenCalledWith(expect.objectContaining({ background: true }))
    expect(started).toMatch(/background/i)
    // 收尾指引指向 wait 而不是「你会被通知」——后者兑现不了（notify 只插得进还在跑的那一轮），
    // 而正是那句话把模型推向 sleep 轮询
    expect(started).toContain('wait-for-sub-sessions')
    expect(started).toContain('Do NOT sleep and poll')
    expect(started).not.toMatch(/notified/i)

    mocks.runnerPrompt.mockResolvedValue({ kind: 'timeout' })
    const timedOut = textOf(
      await tool.execute('tc-1', {
        action: 'prompt-sub-session',
        sub_session_id: 'sub-1',
        message: 'go',
        timeout_seconds: 30
      })
    )
    // 超时**没有**中止子会话 —— 这句话必须写在回执里，否则模型会以为工作被丢了
    expect(timedOut).toContain('NOT cancelled')
    expect(timedOut).toContain('wait-for-sub-sessions')
  })

  it('失败的一轮走 <error> 围栏（同一份事实，但与正常答复分得开）', async () => {
    mocks.runnerPrompt.mockResolvedValue({
      kind: 'answered',
      answer: 'boom',
      isError: true,
      info: info('sub-1', 'A', 'idle')
    })
    expect(
      textOf(
        await tool.execute('tc-1', {
          action: 'prompt-sub-session',
          sub_session_id: 'sub-1',
          message: 'go'
        })
      )
    ).toContain('<error>\nboom\n</error>')
  })

  it('wait-for-sub-sessions：不传 id = 等全部；结果一次交齐（含答复正文）', async () => {
    mocks.runnerWait.mockResolvedValue({
      kind: 'settled',
      results: [
        { id: 'sub-1', title: 'A', status: 'idle', driven: false, updatedAt: 1, answer: 'A DONE' },
        { id: 'sub-2', title: 'B', status: 'idle', driven: false, updatedAt: 2, answer: 'B DONE' }
      ]
    })
    const out = textOf(await tool.execute('tc-1', { action: 'wait-for-sub-sessions' }))
    expect(mocks.runnerWait).toHaveBeenCalledWith(
      expect.objectContaining({ parentId: 's1', timeoutSeconds: 300 })
    )
    // 不传 id 时不能塞一个空串进去（那会被当成「等某条不存在的子会话」）
    expect(mocks.runnerWait.mock.calls[0][0]).not.toHaveProperty('childId')
    expect(out).toContain('A DONE')
    expect(out).toContain('B DONE')
  })

  it('wait 超时：说清仍在跑且没被中止', async () => {
    mocks.runnerWait.mockResolvedValue({
      kind: 'timeout',
      results: [{ id: 'sub-1', title: 'A', status: 'running', driven: true, updatedAt: 1 }]
    })
    const out = textOf(
      await tool.execute('tc-1', { action: 'wait-for-sub-sessions', timeout_seconds: 30 })
    )
    expect(out).toContain('<sub-sessions status="timeout">')
    expect(out).toContain('NOT cancelled')
    expect(out).toContain('status="running"')
  })

  it('wait 到一条卡在 ask 上的：明说它不会自己好起来（否则父级会一直等）', async () => {
    mocks.runnerWait.mockResolvedValue({
      kind: 'settled',
      results: [{ id: 'sub-1', title: 'A', status: 'waiting-input', driven: false, updatedAt: 1 }]
    })
    const out = textOf(await tool.execute('tc-1', { action: 'wait-for-sub-sessions' }))
    expect(out).toContain('status="waiting-input"')
    expect(out).toContain('Waiting for the user')
  })

  it('list-sub-sessions：每行 id + 状态 + 标题；空名单给出创建指引', async () => {
    mocks.runnerList.mockReturnValue({
      subSessions: [
        { id: 'sub-1', title: 'A', status: 'running', driven: true, updatedAt: 1 },
        { id: 'sub-2', title: 'B', status: 'waiting-input', driven: false, updatedAt: 2 }
      ]
    })
    const listed = textOf(await tool.execute('tc-1', { action: 'list-sub-sessions' }))
    expect(listed).toContain('<sub-session id="sub-1" title="A" status="running"/>')
    expect(listed).toContain('<sub-session id="sub-2" title="B" status="waiting-input"/>')

    mocks.runnerList.mockReturnValue({ subSessions: [] })
    expect(textOf(await tool.execute('tc-1', { action: 'list-sub-sessions' }))).toContain(
      'create-sub-session'
    )
  })

  it('read-sub-session：整块在 <sub-session> 围栏里；还没回话时是 <note> 而不是空答复', async () => {
    const row = info('sub-1', 'A', 'idle')
    mocks.runnerRead.mockResolvedValue({ info: row, answer: 'RESULT' })
    const read = textOf(
      await tool.execute('tc-1', { action: 'read-sub-session', sub_session_id: 'sub-1' })
    )
    expect(read).toContain('<sub-session id="sub-1" title="A" status="idle">')
    expect(read).toContain('<reply>\nRESULT\n</reply>')
    expect(read.trimEnd().endsWith('</sub-session>')).toBe(true)

    mocks.runnerRead.mockResolvedValue({ info: row })
    const empty = textOf(
      await tool.execute('tc-1', { action: 'read-sub-session', sub_session_id: 'sub-1' })
    )
    expect(empty).toContain('<note>No reply yet.</note>')
    expect(empty).not.toContain('<reply>')
  })

  it('标题里的引号/换行不撕破标签（标题是 LLM 起的，不能假定它干净）', async () => {
    mocks.runnerRead.mockResolvedValue({
      info: info('sub-1', '他说 "干完了"\n第二行', 'idle'),
      answer: 'ok'
    })
    const out = textOf(
      await tool.execute('tc-1', { action: 'read-sub-session', sub_session_id: 'sub-1' })
    )
    // 开标签仍是完整的一行：引号被换成单引号、换行被压平
    const openLine = out.split('\n').find((l) => l.startsWith('<sub-session '))!
    expect(openLine.endsWith('>')).toBe(true)
    expect(openLine).toContain("他说 '干完了' 第二行")
  })

  it('stop-sub-session：停住与本就没在跑，回话不同（模型据此判断要不要再等）', async () => {
    mocks.runnerStop.mockResolvedValue({ stopped: true })
    expect(
      textOf(await tool.execute('tc-1', { action: 'stop-sub-session', sub_session_id: 'sub-1' }))
    ).toContain('Stopped')

    mocks.runnerStop.mockResolvedValue({ stopped: false })
    expect(
      textOf(await tool.execute('tc-1', { action: 'stop-sub-session', sub_session_id: 'sub-1' }))
    ).toContain('not running')
  })
})
