/**
 * Hook 自动触发端到端（隔离实例 + 假提供商）：内置 auto-title 的 quick / refine 两段，
 * 加上用户 hook 的整条链路 —— 任务文本组装、CEL 过滤、去重、归属会话、删会话即中止。
 *
 * 观测面：
 *   - 一次 hook run 就是一次 `agentManager.runTask`，在主窗口表现为一条 `sub_session_register`
 *     （parentSessionId = 归属会话、parentToolCallId 缺省、subAgentName = agent、description = hook
 *     显示名、prompt = 渲染后的任务文本）+ 随后的 `sub_session_end`。register 的 sessionId 是派生
 *     agent 自己的 id —— 所以按 parentSessionId 过滤 `events.all()`，`waitFor` 的 sessionId 用不上；
 *   - 假提供商收到的 hook agent 请求，lastUserText 就是那段任务文本（围栏里带 `sessionId: <sid>`）。
 *     **脚本一律按内容认领**：quick 的派发与根会话自己的请求并发，echo 每轮都起，FIFO 永远不安全；
 *   - 跳过（busy / unknown-agent / no-model）与 run 起止只进主进程日志 → `app.mainLog()`。
 *
 * 派生 agent 跑完不销毁（监控里 phase 回到 idle）—— 不断言它消失。
 * 用例有顺序依赖：HA-2 接着 HA-1 的会话往下聊，HA-4 读 HA-3 那条会话。
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parse as parseYaml } from 'yaml'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { sleep, until } from '../../harness/cdp'
import { startFakeProvider, type FakeProvider, type FakeRequest } from '../../harness/fakeProvider'
import { launchApp, type E2EApp } from '../../harness/launch'
import { sidebarPane } from '../../harness/pages'
import {
  eventRecorder,
  seedFakeProvider,
  waitRendererReady,
  writeAgentMd,
  type EventRecorder,
  type RecordedEvent
} from '../../harness/seed'

const MODEL = 'e2e-model'
const PROMPT_ACCEPTED = 'session.prompt-accepted'
const TURN_COMPLETED = 'session.turn-completed'
/** 内置 auto-title 的正文开头（各语言副本的正文都是这段英文） */
const TITLER_BODY = 'Derive one concise title'
const ECHO_BODY = 'E2E echo hook.'
const LATE_BODY = 'E2E late hook.'
const FENCE_CLOSE = '</hook_event>'
/** `session.turn-completed` 的 payload 键 —— 事件围栏里恰好是这些（`trigger` 在围栏属性上，不在 YAML 里） */
const TURN_COMPLETED_KEYS = [
  'isDefaultTitle',
  'profileName',
  'recentText',
  'sessionId',
  'textMessageCount',
  'title',
  'titleAutoGenerated',
  'turnCount'
]

interface HookItem {
  name: string
  displayName: string
  agent: string
  triggers: string[]
  source: 'builtin' | 'user'
  basePath: string
  overridden?: boolean
}

interface SessionRow {
  id: string
  title: string
  settings?: { titleOrigin?: string } | null
}

interface ListedMessage {
  role: string
  type: string
  content: string
}

interface RegisterEvent extends RecordedEvent {
  parentSessionId: string
  parentToolCallId?: string
  subAgentName: string
  description: string
  prompt: string
}

interface EndEvent extends RecordedEvent {
  parentSessionId: string
  result?: string
  isError?: boolean
}

interface MonitorEntry {
  agentId: string
  kind: string
  rootSessionId: string
  profileName: string
  phase: string
}

interface Binding {
  trigger: string
  when?: string
}

const hookMd = (name: string, opts: { agent: string; on: Binding[]; body?: string }): string =>
  [
    '---',
    'shuvix: hook v1',
    `name: ${name}`,
    `shuvix-hook-agent: ${opts.agent}`,
    'shuvix-hook-on:',
    ...opts.on.flatMap((b) => [
      `  - trigger: ${b.trigger}`,
      ...(b.when ? [`    when: ${b.when}`] : [])
    ]),
    '---',
    '',
    opts.body ?? '',
    ''
  ].join('\n')

/** 丢了前缀的裸 `on:` —— 解析器整份拒绝：不触发、也不遮蔽同名内置 */
const bareOnMd = (name: string, agent: string, trigger: string): string =>
  [
    '---',
    'shuvix: hook v1',
    `name: ${name}`,
    `shuvix-hook-agent: ${agent}`,
    'on:',
    `  - trigger: ${trigger}`,
    '---',
    '',
    'Bare on body.',
    ''
  ].join('\n')

let app: E2EApp
let provider: FakeProvider
let events: EventRecorder
/** 内置 auto-title 的显示名（随界面语言，经 IPC 取） */
let autoTitleLabel = ''
const sids: Record<string, string> = {}
/** HA-3 第 1 轮收尾时 echo / late 的 register 数（HA-4 断言） */
let turn1Counts: { echo: number; late: number } | null = null

const writeHook = (fileName: string, text: string): void =>
  writeFileSync(join(app.hooksDir, fileName), text)
const listHooks = (): Promise<HookItem[]> => app.main.eval('window.api.hook.list()')
const listInvalid = (): Promise<Array<{ fileName: string; error: string }>> =>
  app.main.eval('window.api.hook.listInvalid()')
/** 无项目会话（根档案 chat），标题是主进程当前语言的默认标题 */
const createSession = (): Promise<string> =>
  app.main.eval<string>(`window.api.session.create({}).then((s) => s.id)`)
const sessionOf = (sid: string): Promise<SessionRow> =>
  app.main.eval<SessionRow>(`window.api.session.getById(${JSON.stringify(sid)})`)
/** 用户改名（IPC 路径记 titleOrigin=user） */
const renameSession = (sid: string, title: string): Promise<unknown> =>
  app.main.eval(`window.api.session.updateTitle(${JSON.stringify({ id: sid, title })})`)
const listMessages = (sid: string): Promise<ListedMessage[]> =>
  app.main.eval(`window.api.message.list(${JSON.stringify(sid)})`)
const monitorList = (): Promise<MonitorEntry[]> => app.main.eval('window.api.agent.monitorList()')
const logLines = (): string[] => app.mainLog().split('\n')

/** 发 prompt 不等它、失败也吞掉：hook 的派发与根会话这一轮并发，轮的收尾另由 agent_end 等 */
const promptTolerant = (sid: string, text: string): Promise<unknown> =>
  app.main.eval(
    `(window.api.agent.prompt(${JSON.stringify({ sessionId: sid, text })}).catch(() => undefined), true)`
  )

/** 发一轮并等根会话这一轮收尾（agent_end 是流式游标：每轮恰好等到自己那一条） */
const promptTurn = async (sid: string, text: string): Promise<void> => {
  await promptTolerant(sid, text)
  await events.waitFor('agent_end', { sessionId: sid })
}

const fenceOpen = (trigger: string): string => `<hook_event trigger="${trigger}">`

/** 任务文本里事件围栏的 YAML → 对象（找不到围栏直接抛，免得断言在 undefined 上失败得莫名其妙） */
const eventOf = (prompt: string, trigger: string): Record<string, unknown> => {
  const open = `${fenceOpen(trigger)}\n`
  const start = prompt.indexOf(open)
  const end = prompt.lastIndexOf(`\n${FENCE_CLOSE}`)
  if (start < 0 || end < start) {
    throw new Error(`no ${trigger} fence in prompt: ${prompt.slice(0, 300)}`)
  }
  return parseYaml(prompt.slice(start + open.length, end)) as Record<string, unknown>
}

/** hook agent 的请求：任务文本以这段正文开头、围栏是这个埋点、payload 里是这条会话 */
const hookRequest =
  (body: string, trigger: string, sid: string) =>
  (r: FakeRequest): boolean =>
    r.lastUserText.startsWith(body) &&
    r.lastUserText.includes(fenceOpen(trigger)) &&
    r.lastUserText.includes(sid)
const titlerRequest = (sid: string, trigger: string): ((r: FakeRequest) => boolean) =>
  hookRequest(TITLER_BODY, trigger, sid)
const echoRequest = (sid: string): ((r: FakeRequest) => boolean) =>
  hookRequest(ECHO_BODY, TURN_COMPLETED, sid)
/** 根会话的请求：最后一条用户消息就是这句 prompt（每条会话每一轮的 prompt 文本都不同） */
const rootRequest =
  (text: string) =>
  (r: FakeRequest): boolean =>
    r.lastUserText === text
const toolNames = (r: FakeRequest): string[] =>
  ((r.body.tools ?? []) as Array<{ function?: { name?: string } }>).map(
    (t) => t.function?.name ?? ''
  )

let titleCallSeq = 0
/** titler 的两发：先 session set-title，再以标题正文作答收尾（hook 不读这个返回值） */
const scriptTitler = (sid: string, trigger: string, title: string): void => {
  const when = titlerRequest(sid, trigger)
  provider.script(
    {
      toolCalls: [
        {
          id: `call_title_${++titleCallSeq}`,
          name: 'session',
          args: JSON.stringify({ action: 'set-title', title })
        }
      ],
      when
    },
    { text: title, when }
  )
}

interface RegisterFilter {
  /** 任务文本里的事件围栏是这个埋点 */
  trigger?: string
  agent?: string
  /** hook 显示名（没写 shuvix-displayName 的用户 hook 就是它的 name） */
  description?: string
}

const isRegister =
  (sid: string, f: RegisterFilter = {}) =>
  (e: RecordedEvent): e is RegisterEvent => {
    if (e.type !== 'sub_session_register' || e.parentSessionId !== sid) return false
    const reg = e as RegisterEvent
    return (
      (!f.trigger || reg.prompt.includes(fenceOpen(f.trigger))) &&
      (!f.agent || reg.subAgentName === f.agent) &&
      (!f.description || reg.description === f.description)
    )
  }

/** 某会话名下（可再筛）的 hook run 登记，按到达序 */
const hookRegisters = async (sid: string, f: RegisterFilter = {}): Promise<RegisterEvent[]> =>
  (await events.all()).filter(isRegister(sid, f))

const endOf = async (agentId: string): Promise<EndEvent | undefined> =>
  (await events.all()).find(
    (e): e is EndEvent => e.type === 'sub_session_end' && e.sessionId === agentId
  )

/** 等某会话上满足筛选的 register 到齐 n 条且每条都已 sub_session_end，回这些 register */
const settledRegisters = (
  sid: string,
  f: RegisterFilter,
  n: number,
  what: string
): Promise<RegisterEvent[]> =>
  until(async () => {
    const all = await events.all()
    const regs = all.filter(isRegister(sid, f))
    if (regs.length < n) return null
    const ended = new Set(all.filter((e) => e.type === 'sub_session_end').map((e) => e.sessionId))
    return regs.every((r) => ended.has(r.sessionId)) ? regs : null
  }, what)

/** 某会话某 hook 这次 run 的 runId（取自日志的 start 行） */
const runIdOf = async (hook: string, trigger: string, sid: string): Promise<string> => {
  const line = await until(
    () =>
      logLines().find(
        (l) =>
          l.includes(`hook "${hook}" run=`) &&
          l.includes(` start trigger=${trigger} session=${sid} `)
      ),
    `hook "${hook}" run start logged for ${sid}`
  )
  return /run=(\S+)/.exec(line)![1]
}

beforeAll(async () => {
  app = await launchApp()
  provider = await startFakeProvider()
  await seedFakeProvider(app.main, { baseUrl: provider.baseUrl, modelId: MODEL })
  await waitRendererReady(app.main)
  events = eventRecorder(app.main)
  await events.install()

  writeAgentMd(app, 'echo-agent', { tools: 'read', body: 'ECHO AGENT BODY.' })
  mkdirSync(app.hooksDir, { recursive: true })
  // echo：无 when，每条会话的每一轮都起 —— 兼作每轮的同步栅栏
  writeHook(
    'echo.md',
    hookMd('echo', { agent: 'echo-agent', on: [{ trigger: TURN_COMPLETED }], body: ECHO_BODY })
  )
  // late：同一个 agent，CEL 挡掉第 1 轮
  writeHook(
    'late.md',
    hookMd('late', {
      agent: 'echo-agent',
      on: [{ trigger: TURN_COMPLETED, when: 'event.turnCount >= 2' }],
      body: LATE_BODY
    })
  )
  writeHook('bad-on.md', bareOnMd('bad-on', 'echo-agent', TURN_COMPLETED))
  writeHook(
    'base-agent.md',
    hookMd('base-agent', { agent: 'work', on: [{ trigger: TURN_COMPLETED }], body: 'E2E base.' })
  )

  const builtin = (await listHooks()).find((h) => h.name === 'auto-title' && h.source === 'builtin')
  autoTitleLabel = builtin?.displayName ?? ''
})

afterAll(async () => {
  await provider?.close()
  await app?.stop()
})

describe('内置 auto-title —— quick / refine', () => {
  it('HA-1 默认标题会话的首条 prompt 起 quick：titler 经 session set-title 写标题（titleOrigin=auto）；run 挂在归属会话下，任务文本 = 正文 + prompt-accepted 事件围栏', async () => {
    const sid = await createSession()
    sids.quick = sid
    const fresh = await sessionOf(sid)
    const defaultTitle = fresh.title
    expect(defaultTitle).not.toBe('')
    expect(fresh.settings?.titleOrigin).toBeUndefined()
    expect(autoTitleLabel).not.toBe('')

    provider.script({ text: 'r1', when: rootRequest('hello') })
    scriptTitler(sid, PROMPT_ACCEPTED, 'Hooked title')
    await promptTurn(sid, 'hello')

    await until(async () => (await sessionOf(sid)).title === 'Hooked title', 'quick title applied')
    expect((await sessionOf(sid)).settings?.titleOrigin).toBe('auto')

    const [quick] = await settledRegisters(
      sid,
      { trigger: PROMPT_ACCEPTED },
      1,
      'quick titler run settled'
    )
    expect(await hookRegisters(sid, { trigger: PROMPT_ACCEPTED })).toHaveLength(1)
    expect(quick.subAgentName).toBe('titler')
    expect(quick.parentToolCallId).toBeUndefined()
    expect(quick.description).toBe(autoTitleLabel)
    expect(quick.prompt.startsWith(TITLER_BODY)).toBe(true)
    expect(quick.prompt.endsWith(FENCE_CLOSE)).toBe(true)
    for (const line of [
      'promptText: hello',
      'isDefaultTitle: true',
      'profileName: chat',
      `sessionId: ${sid}`
    ]) {
      expect(quick.prompt).toContain(line)
    }
    const event = eventOf(quick.prompt, PROMPT_ACCEPTED)
    expect(event).toMatchObject({
      sessionId: sid,
      profileName: 'chat',
      title: defaultTitle,
      isDefaultTitle: true,
      promptText: 'hello'
    })
    expect(event).not.toHaveProperty('trigger')

    // 工具调用一发 + 正文作答一发；titler 的工具集只有 session
    const titlerCalls = provider.requests().filter(titlerRequest(sid, PROMPT_ACCEPTED))
    expect(titlerCalls).toHaveLength(2)
    for (const call of titlerCalls) {
      expect(toolNames(call)).toContain('session')
      expect(toolNames(call)).not.toContain('bash')
    }

    await until(
      async () => (await sidebarPane(app.main).titles()).includes('Hooked title'),
      'sidebar shows the hook-written title'
    )
  })

  it('HA-2 第 2 轮结束起一次 refine（事件带 turnCount 2 / textMessageCount 4 / recentText 块），第 3 轮不再起', async () => {
    const sid = sids.quick
    // 上一轮的 echo 还没收尾时，这一轮的 echo 会 busy 跳过 —— 后面要按 echo 计数，先等它落定
    await settledRegisters(sid, { description: 'echo' }, 1, 'turn-1 echo settled')

    provider.script({ text: 'r2', when: rootRequest('second') })
    scriptTitler(sid, TURN_COMPLETED, 'Refined title')
    await promptTurn(sid, 'second')

    await until(
      async () => (await sessionOf(sid)).title === 'Refined title',
      'refined title applied'
    )
    expect((await sessionOf(sid)).settings?.titleOrigin).toBe('auto')
    const [refine] = await settledRegisters(
      sid,
      { trigger: TURN_COMPLETED, agent: 'titler' },
      1,
      'refine run settled'
    )
    for (const line of [
      'turnCount: 2',
      'textMessageCount: 4',
      'titleAutoGenerated: true',
      'recentText: |'
    ]) {
      expect(refine.prompt).toContain(line)
    }
    const recentText = String(eventOf(refine.prompt, TURN_COMPLETED).recentText)
    expect(recentText).toContain('User: second')
    expect(recentText).toContain('Assistant: r2')
    // 标题已不是默认值：第 2 条 prompt 没有再起 quick
    expect(await hookRegisters(sid, { trigger: PROMPT_ACCEPTED })).toHaveLength(1)

    // 第 3 轮：refine 的 `turnCount == 2` 关门
    await settledRegisters(sid, { description: 'echo' }, 2, 'turn-2 echo settled')
    provider.script({ text: 'r3', when: rootRequest('third') })
    await promptTurn(sid, 'third')
    await settledRegisters(sid, { description: 'echo' }, 3, 'turn-3 echo settled (barrier)')
    await sleep(500)
    expect(await hookRegisters(sid, { agent: 'titler' })).toHaveLength(2)
    expect((await sessionOf(sid)).title).toBe('Refined title')
  })
})

describe('用户 hook —— 组装、CEL 过滤、不级联', () => {
  it('HA-3 用户改过名的会话：auto-title 两段都不起，标题与 titleOrigin=user 原样保留', async () => {
    const sid = await createSession()
    sids.renamed = sid
    await renameSession(sid, 'Renamed by user')
    expect((await sessionOf(sid)).settings?.titleOrigin).toBe('user')

    provider.script(
      { text: 'm1r', when: rootRequest('m1') },
      { text: 'm2r', when: rootRequest('m2') }
    )
    await promptTurn(sid, 'm1')
    await settledRegisters(sid, { description: 'echo' }, 1, 'turn-1 echo settled')
    // 同一次 fire 起的 run 同时登记；留一拍让「本不该起的 late」有机会冒出来
    await sleep(300)
    turn1Counts = {
      echo: (await hookRegisters(sid, { description: 'echo' })).length,
      late: (await hookRegisters(sid, { description: 'late' })).length
    }

    await promptTurn(sid, 'm2')
    await settledRegisters(sid, { description: 'echo' }, 2, 'turn-2 echo settled')
    await settledRegisters(sid, { description: 'late' }, 1, 'turn-2 late settled')

    expect(await hookRegisters(sid, { agent: 'titler' })).toHaveLength(0)
    const row = await sessionOf(sid)
    expect(row.title).toBe('Renamed by user')
    expect(row.settings?.titleOrigin).toBe('user')
    const echo2 = (await hookRegisters(sid, { description: 'echo' }))[1]
    expect(eventOf(echo2.prompt, TURN_COMPLETED)).toMatchObject({
      turnCount: 2,
      textMessageCount: 4,
      titleAutoGenerated: false
    })
  })

  it('HA-4 无 when 的 echo 每轮都起、CEL 挡掉第 1 轮的 late；任务文本 = 正文 + 围栏 YAML，模型收到的正是它；hook agent 不再触发 hook', async () => {
    const sid = sids.renamed
    expect(turn1Counts).toEqual({ echo: 1, late: 0 })

    const echoes = await hookRegisters(sid, { description: 'echo' })
    const lates = await hookRegisters(sid, { description: 'late' })
    expect(echoes).toHaveLength(2)
    expect(lates).toHaveLength(1)

    const head = `${ECHO_BODY}\n\n${fenceOpen(TURN_COMPLETED)}\n`
    const tail = `\n${FENCE_CLOSE}`
    for (const [i, reg] of echoes.entries()) {
      expect(reg.subAgentName).toBe('echo-agent')
      expect(reg.parentToolCallId).toBeUndefined()
      expect(reg.prompt.startsWith(head)).toBe(true)
      expect(reg.prompt.endsWith(tail)).toBe(true)
      const payload = parseYaml(reg.prompt.slice(head.length, -tail.length)) as Record<
        string,
        unknown
      >
      expect(Object.keys(payload).sort()).toEqual(TURN_COMPLETED_KEYS)
      expect(payload).toMatchObject({
        sessionId: sid,
        profileName: 'chat',
        title: 'Renamed by user',
        isDefaultTitle: false,
        turnCount: i + 1,
        titleAutoGenerated: false
      })
      expect(String(payload.recentText).startsWith('User:')).toBe(true)

      // 模型侧：hook agent 那一发的最后一条用户消息逐字就是 register 的任务文本，系统提示词是 agent md 正文
      const calls = provider.requests().filter((r) => r.lastUserText === reg.prompt)
      expect(calls.length).toBeGreaterThan(0)
      for (const call of calls) expect(call.raw).toContain('ECHO AGENT BODY.')
    }
    expect(lates[0].subAgentName).toBe('echo-agent')
    expect(lates[0].prompt.startsWith(`${LATE_BODY}\n\n`)).toBe(true)
    expect(eventOf(lates[0].prompt, TURN_COMPLETED).turnCount).toBe(2)

    // 不级联：hook 派发的 agent 不经 AgentSession、不发会话埋点，名下不会再有 run
    const registers = (await events.all()).filter(
      (e): e is RegisterEvent => e.type === 'sub_session_register'
    )
    const hookAgentIds = new Set(registers.map((r) => r.sessionId))
    expect(registers.filter((r) => hookAgentIds.has(r.parentSessionId))).toHaveLength(0)
    expect(await hookRegisters(sid)).toHaveLength(3)
  })
})

describe('非法文件', () => {
  it('HA-5 非法文件既不运行也不遮蔽：bad-on / base-agent 带原因进无法解析分组、从不派发；写坏的 auto-title.md 压不住内置，新会话照样拿到 quick 标题', async () => {
    const invalid = await listInvalid()
    const badOn = invalid.find((f) => f.fileName === 'bad-on.md')
    expect(badOn?.error).toContain("bare 'on' key is not read — use 'shuvix-hook-on'")
    expect(badOn?.error).toContain('rejected')
    expect(invalid.find((f) => f.fileName === 'base-agent.md')?.error).toContain(
      'names a session base profile'
    )
    const names = (await listHooks()).map((h) => h.name)
    expect(names).not.toContain('bad-on')
    expect(names).not.toContain('base-agent')
    // 前面几个用例已经跑过好几轮 turn-completed：两份非法文件若被误认合法早就派发过了
    const strays = (await events.all()).filter(
      (e) =>
        e.type === 'sub_session_register' &&
        ['bad-on', 'base-agent'].includes(String((e as RegisterEvent).description))
    )
    expect(strays).toHaveLength(0)

    writeHook('auto-title.md', bareOnMd('auto-title', 'titler', PROMPT_ACCEPTED))
    const rows = (await listHooks()).filter((h) => h.name === 'auto-title')
    expect(rows).toHaveLength(1)
    expect(rows[0].source).toBe('builtin')
    expect(rows[0].overridden).toBeFalsy()

    const sid = await createSession()
    provider.script({ text: 'r5', when: rootRequest('p5') })
    scriptTitler(sid, PROMPT_ACCEPTED, 'Builtin still titles')
    await promptTurn(sid, 'p5')
    await until(
      async () => (await sessionOf(sid)).title === 'Builtin still titles',
      'builtin quick title applied despite the broken override'
    )
    const [quick] = await settledRegisters(
      sid,
      { trigger: PROMPT_ACCEPTED, agent: 'titler' },
      1,
      'builtin quick run settled'
    )
    expect(quick.description).toBe(autoTitleLabel)

    expect(
      await app.main.eval(`window.api.hook.deleteByFile({ fileName: 'auto-title.md' })`)
    ).toEqual({ success: true })
    expect(existsSync(join(app.hooksDir, 'auto-title.md'))).toBe(false)
  })
})

describe('运行归属、去重与收尾', () => {
  it('HA-6 run 挂在归属会话下、监控可见；同一 hook × 同一会话还在跑时下一轮 busy 跳过（只进日志）而别的 hook 照跑；放行后 agent 回 idle、下一轮重新派发', async () => {
    const sid = await createSession()
    await renameSession(sid, 'HA-6 busy lane')
    provider.script(
      { text: 'h1r', when: rootRequest('h1') },
      // 放行靠 provider.release()；上限只是兜底
      { holdMs: 20_000, when: echoRequest(sid) },
      { text: 'h2r', when: rootRequest('h2') },
      { text: 'h3r', when: rootRequest('h3') }
    )

    await promptTurn(sid, 'h1')
    const [held] = await until(async () => {
      const regs = await hookRegisters(sid, { description: 'echo' })
      return regs.length === 1 ? regs : null
    }, 'held echo run registered')
    expect(held.parentToolCallId).toBeUndefined()
    expect(held.subAgentName).toBe('echo-agent')
    expect(await endOf(held.sessionId)).toBeUndefined()
    const entry = await until(
      async () =>
        (await monitorList()).find(
          (e) =>
            e.kind === 'spawned' &&
            e.rootSessionId === sid &&
            e.profileName === 'echo-agent' &&
            e.phase === 'turn'
        ),
      'held echo agent in the monitor with phase turn'
    )
    expect(entry.agentId).toBe(held.sessionId)

    // 仍挂着：第 2 轮的 echo 撞上还在跑的上一次 → busy 跳过；late 不受影响
    await promptTurn(sid, 'h2')
    await until(
      () =>
        logLines().some((l) =>
          l.includes(`hook "echo" skipped for session ${sid}: busy (previous run still going)`)
        ),
      'echo skipped busy on turn 2'
    )
    await settledRegisters(sid, { description: 'late' }, 1, 'late ran normally on turn 2')
    expect(await endOf(held.sessionId)).toBeUndefined()

    provider.release()
    await until(() => endOf(held.sessionId), 'held echo run settled after release')
    expect(await hookRegisters(sid, { description: 'echo' })).toHaveLength(1)
    await until(
      async () => (await monitorList()).find((e) => e.agentId === held.sessionId)?.phase === 'idle',
      'echo agent back to idle'
    )

    // 道空出来了：下一轮照常派发
    await promptTurn(sid, 'h3')
    await settledRegisters(sid, { description: 'echo' }, 2, 'echo dispatched again on turn 3')
  })

  it('HA-7 hook run 里模型报错：主进程日志记 failed:（不是 ok），归属会话的消息列表没有错误行、根回复完好', async () => {
    const sid = await createSession()
    await renameSession(sid, 'HA-7 failing hook')
    provider.script(
      { text: 'e1r', when: rootRequest('e1') },
      { httpStatus: 500, when: echoRequest(sid) }
    )

    await promptTurn(sid, 'e1')
    const [reg] = await settledRegisters(sid, { description: 'echo' }, 1, 'failed echo run settled')
    // 注入的 500 确实打在了 hook agent 身上（它的结果带着模型的 stopReason=error）—— 不是悄悄没发生
    expect((await endOf(reg.sessionId))?.result).toContain('stopReason=error')
    // 同一次失败在主进程日志里记为失败的 run：runTask 照常 resolve，失败原因在 outcome.error 上
    const runId = await runIdOf('echo', TURN_COMPLETED, sid)
    await until(
      () => logLines().some((l) => l.includes(`hook "echo" run=${runId} failed:`)),
      'failed echo run logged as failed'
    )
    expect(logLines().some((l) => l.includes(`hook "echo" run=${runId} ok (`))).toBe(false)

    const listed = await listMessages(sid)
    expect(listed.map((m) => m.role)).toEqual(['user', 'assistant'])
    expect(listed.some((m) => m.type === 'error_event')).toBe(false)
    expect(listed[1].content).toBe('e1r')
  })

  it('HA-8 删掉归属会话即中止它名下在跑的 hook run：日志记 aborted，挂着的 run 照样收到 sub_session_end', async () => {
    const sid = await createSession()
    await renameSession(sid, 'HA-8 deleted mid-run')
    provider.script(
      { text: 'd1r', when: rootRequest('d1') },
      { holdMs: 20_000, when: echoRequest(sid) }
    )

    await promptTurn(sid, 'd1')
    const [held] = await until(async () => {
      const regs = await hookRegisters(sid, { description: 'echo' })
      return regs.length === 1 ? regs : null
    }, 'held echo run registered')
    const runId = await runIdOf('echo', TURN_COMPLETED, sid)
    expect(await endOf(held.sessionId)).toBeUndefined()

    await app.main.eval(`window.api.session.delete(${JSON.stringify(sid)})`)
    await until(
      () =>
        logLines().some(
          (l) =>
            l.includes(`hook "echo" run=${runId} aborted`) ||
            l.includes(`hook "echo" run=${runId} failed:`)
        ),
      'held echo run ended by the session delete'
    )
    await until(() => endOf(held.sessionId), 'sub_session_end for the aborted run')
  })
})
