/**
 * 业务埋点的统一注册表 —— 全部触发点的「业务位置 + 该位置能提供的上下文信息」的类型声明。
 *
 * 架构约定（docs/hook-design.md）：
 *  - **埋点是通用的，不和任何 hook 绑定**：emit 侧只调 `fire(id, payload)`，声明自己
 *    所处的业务位置与当下上下文里的事实，无视有没有人订阅；
 *  - **hook 声明自己在哪触发**（md 的 `shuvix-hook-on`）—— 两者只以字符串 id 耦合；
 *  - 本表是双方唯一的契约点：`TriggerPayloadMap` 给 emit 侧编译期类型安全
 *    （fire 的 payload 形状按 id 收窄），`TRIGGER_POINTS` 给解析器/文档/UI 一份可枚举目录。
 *    **加一个埋点 = 此表加一行 + 在业务位置补一个 fire 调用**，格式与 runner 零改动。
 *
 * payload 纪律：只放该业务位置**天然持有的事实**（会话状态、本轮统计、对话尾部文本…），
 * 不放为某个 hook 特制的字段 —— 判断标准是「换一个完全不同的 hook 订阅这里，这些字段
 * 是否仍然自然有用」。payload 整体会以 YAML 附在派发给 agent 的任务末尾（hookPrompt.ts），
 * 所以每个字段同时也是 agent 读到的事实。
 *
 * 保留键：CEL `when` 看到的 event 在 payload 之上附加 `trigger`（埋点 id）—— payload 不得使用这个键名。
 *
 * **两类埋点**（`kind`）：
 *  - `observe`（观察型）：`fire` 广播，hook 是观察者 —— 不拦截、不等它、结果不读；
 *  - `decide`（判定型）：`decide` 等所有命中的 hook 给出结论并按严格程度合并。结论的形状由
 *    DECIDE_SPECS 给出（即派发时的结果契约 schema），hook md 的格式不因此加任何键 —— 绑到判定型
 *    埋点，就按判定方式执行。判定型埋点只出现在宿主已经决定「这里需要一个判断」的地方，hook 回答的
 *    是「谁来判断」，不改变那个决定本身（见 docs/permission-review-design.md）。
 */
import {
  PERMISSION_VERDICT_SCHEMA,
  isPermissionVerdict,
  permissionDecisionSeverity,
  type PermissionVerdict
} from '@shuvix/chat-protocol/types/permissionReview'

/** 会话域埋点的公共上下文（emit 侧从会话状态现取） */
interface SessionTriggerBase {
  /** 所属会话 id —— 会话域埋点（scope:'session'）以它作为 run 的归属会话 */
  sessionId: string
  /** 会话根 Agent 当前档案名（由会话形态推导：work / chat / notebook / bot，或子会话钉下的档案） */
  profileName: string
  /** 会话当前标题 */
  title: string
  /** 标题是否仍是通用默认值（宿主按当前语言的默认标题判定；笔记本会话不经这些埋点） */
  isDefaultTitle: boolean
}

/**
 * `permission.request` 的 payload —— 策略引擎判出「需要判断」（ask 档，不含 force-ask）、弹询问卡片
 * 之前，宿主从那次安全请求投影出的事实。它就是审查 agent 的**全部输入**（设计里的「独立上下文」）：
 * 只收人写的意图与操作本身，不收 agent 写的正文、工具输出、命令的 description 参数 —— 那些正是注入
 * 进来、或能被拿来说服审查者的地方。
 */
export interface PermissionRequestPayload {
  /** 根会话 id —— run 的归属。派生 agent 的操作也挂在根会话下，审查 run 的深度因此恒为 1 */
  sessionId: string
  /** 发起这次操作的 agent */
  agent: {
    /** 档案名 */
    profile: string
    /** 'root' | 'spawned' */
    kind: string
  }
  /** 要判断的操作 */
  operation: {
    /** 工具名；多路复用工具带动作（如 `session: create-sub-session`） */
    tool: string
    /** read / write / execute / navigate … */
    action: string
    /** 客体类型：path / command / gitTool / database / url / invocation */
    objectType: string
    /** 客体原文：命令 / 路径 / SQL / URL / 工具名 */
    target: string
    /**
     * 其余事实，按客体类型：命令的 channel / host / sandboxed / unconfinedReason / background，路径的
     * path / requestedPath / diff 预览，数据库的 connection / dbType / readonly …；各类型都带
     * workingDirectory / platform
     */
    facts: Record<string, string | number | boolean>
  }
  /** 要求判断的策略：显示名，与它们写给人看的风险提示（合并后的一段） */
  policy: { names: string[]; prompt: string }
  /**
   * 人写的输入，旧 → 新，逐条截断：人发的消息、人对 agent 提问（ask 工具）的回答、人在审批卡片上
   * 写的反馈（安全模块收到回答时记下的那份，不是会话树里的工具结果文字）。子会话里人发的消息取
   * **顶层会话**的 —— 子会话里的「用户消息」是父 agent 写的，见 delegatedTasks；子会话自己的 ask
   * 回答与卡片反馈照样算。
   */
  userMessages: string[]
  /**
   * 仅子会话：父 agent 派进来的任务文本（旧 → 新）。是 agent 写的，只能当作「它声称要做什么」，
   * 不是人的授权。非子会话为空。
   */
  delegatedTasks: string[]
  /** 本会话最近判定过的操作（目标 + 结果），旧 → 新 —— 看得出「先下载再执行」「被拒后换写法」 */
  recentOperations: Array<{ target: string; outcome: string }>
}

/**
 * 埋点 id → payload 形状的类型目录。emit 侧 `fire('session.turn-completed', {...})`
 * 由此获得编译期校验；hook md 的 CEL `when` 与派发给 agent 的事件围栏读的就是这份数据。
 */
export interface TriggerPayloadMap {
  /** 用户 prompt 通过校验、正式派发给根 Agent 之前（本轮 LLM 尚未开始） */
  'session.prompt-accepted': SessionTriggerBase & {
    /** 本条用户消息的文本 */
    promptText: string
  }
  /**
   * 一轮 prompt 完整结束之后（含工具调用）。**无论成败恒触发**（abort/出错的轮也算
   * 「结束」）—— 桌面 emit 侧不做成败过滤，订阅方用 when 自行取舍；成败标记等有
   * 消费方需要再进 payload。
   */
  'session.turn-completed': SessionTriggerBase & {
    /** 会话内用户文本消息数（≈ 已发生的轮数；含本轮） */
    turnCount: number
    /** 有正文的对话消息数（user/assistant，空文本不计） */
    textMessageCount: number
    /** 标题是否出自自动化（settings.titleOrigin === 'auto'，用户手动改名后为 false） */
    titleAutoGenerated: boolean
    /** 对话末尾文本（`User:`/`Assistant:` 拼接，尾部截断 ~1000 字） */
    recentText: string
  }
  /**
   * 判定型：策略引擎判出 ask（不含 force-ask）、弹询问卡片之前。命中的 hook 替用户回答
   * allow / ask（照旧问人）/ deny；没有 hook 命中或都没给出结论时照旧问人。
   */
  'permission.request': PermissionRequestPayload
}

/** 判定型埋点 → 结论形状（即派发时结果契约的形状，见 DECIDE_SPECS） */
export interface TriggerResultMap {
  'permission.request': PermissionVerdict
}

export type TriggerId = keyof TriggerPayloadMap
/** 判定型埋点：`decide` 等结论 */
export type DecideTriggerId = keyof TriggerResultMap
/** 观察型埋点：`fire` 广播、结果不读 */
export type ObserveTriggerId = Exclude<TriggerId, DecideTriggerId>

/** 判定型埋点的结论契约 */
export interface DecideSpec<R> {
  /** 结果契约的 JSON Schema —— 派发时即 `next` 工具的参数 schema */
  schema: Record<string, unknown>
  /** 捕获值 → 结论；认不出的返回 null（按「这个 hook 没有意见」处理） */
  parse: (value: unknown) => R | null
  /** 严格程度，数大者更严 —— 多个 hook 都给出结论时取最严的那个 */
  severity: (result: R) => number
}

export const DECIDE_SPECS: { [K in DecideTriggerId]: DecideSpec<TriggerResultMap[K]> } = {
  'permission.request': {
    schema: PERMISSION_VERDICT_SCHEMA,
    parse: (value) => (isPermissionVerdict(value) ? value : null),
    severity: (verdict) => permissionDecisionSeverity(verdict.decision)
  }
}

/** 一个埋点的声明（目录条目）—— 解析器/文档/UI 消费；payload 类型在 TriggerPayloadMap */
export interface TriggerPointDef {
  id: TriggerId
  /** 观察型（`fire`，结果不读）还是判定型（`decide`，等结论）—— 见文件头 */
  kind: 'observe' | 'decide'
  /** 业务位置的一句话描述（文档/UI 用，非 LLM 面向） */
  description: string
  /**
   * 'session'：payload.sessionId 同时是 run 的归属会话 —— 派发的 agent 以它为
   * parentSessionId（工具绑定/询问路由/LLM 日志归属/面板可见都随之落到该会话）。
   * v1 的 hook 只在会话域埋点上运行：没有归属会话的 run 会让授权为空、询问被拒，
   * 那是静默降级，宁可不跑。
   */
  scope?: 'session'
}

export const TRIGGER_POINTS: Record<TriggerId, TriggerPointDef> = {
  'session.prompt-accepted': {
    id: 'session.prompt-accepted',
    kind: 'observe',
    description: 'A user prompt was accepted and is about to be dispatched to the session agent',
    scope: 'session'
  },
  'session.turn-completed': {
    id: 'session.turn-completed',
    kind: 'observe',
    description: 'A full prompt turn (including tool calls) finished in a chat session',
    scope: 'session'
  },
  'permission.request': {
    id: 'permission.request',
    kind: 'decide',
    description:
      'A security policy wants an operation judged; a decide hook may answer before the user is asked',
    scope: 'session'
  }
}

/** 按（可能未知的）字符串 id 查目录 —— 解析器用；未知 id 的绑定惰性化而非判非法 */
export function getTriggerPoint(id: string): TriggerPointDef | undefined {
  return (TRIGGER_POINTS as Record<string, TriggerPointDef>)[id]
}
