/**
 * 业务埋点的统一注册表 —— 全部触发点的「业务位置 + 该位置能提供的上下文信息」的类型声明。
 *
 * 架构约定（docs/hook-design.md）：
 *  - **埋点是通用的，不和任何 hook 绑定**：emit 侧只调 `fire(id, payload)`，声明自己
 *    所处的业务位置与当下上下文里的事实，无视有没有人订阅；
 *  - **hook 声明自己在哪触发**（md 的 `shuvix-hook-on`）—— 两者只以字符串 id 耦合；
 *  - 本表是双方唯一的契约点：`TriggerPayloadMap` 给 emit 侧编译期类型安全
 *    （fire 的 payload 形状按 id 收窄），`TRIGGER_POINTS` 给解析器/文档/UI 一份可枚举目录。
 *    **加一个埋点 = 此表加一行 + 在业务位置补一个 fire 调用**，格式与 runner 零改动。
 *
 * payload 纪律：只放该业务位置**天然持有的事实**（会话状态、本轮统计、对话尾部文本…），
 * 不放为某个 hook 特制的字段 —— 判断标准是「换一个完全不同的 hook 订阅这里，这些字段
 * 是否仍然自然有用」。payload 整体会以 YAML 附在派发给 agent 的任务末尾（hookPrompt.ts），
 * 所以每个字段同时也是 agent 读到的事实。
 *
 * 保留键：CEL `when` 看到的 event 在 payload 之上附加 `trigger`（埋点 id）—— payload 不得使用这个键名。
 */

/** 会话域埋点的公共上下文（emit 侧从会话状态现取） */
interface SessionTriggerBase {
  /** 所属会话 id —— 会话域埋点（scope:'session'）以它作为 run 的归属会话 */
  sessionId: string
  /** 会话根 Agent 当前档案名（由会话形态推导：work / chat / notebook / bot，或子会话钉下的档案） */
  profileName: string
  /** 会话当前标题 */
  title: string
  /** 标题是否仍是通用默认值（宿主按当前语言的默认标题判定；笔记本会话不经这些埋点） */
  isDefaultTitle: boolean
}

/**
 * 埋点 id → payload 形状的类型目录。emit 侧 `fire('session.turn-completed', {...})`
 * 由此获得编译期校验；hook md 的 CEL `when` 与派发给 agent 的事件围栏读的就是这份数据。
 */
export interface TriggerPayloadMap {
  /** 用户 prompt 通过校验、正式派发给根 Agent 之前（本轮 LLM 尚未开始） */
  'session.prompt-accepted': SessionTriggerBase & {
    /** 本条用户消息的文本 */
    promptText: string
  }
  /**
   * 一轮 prompt 完整结束之后（含工具调用）。**无论成败恒触发**（abort/出错的轮也算
   * 「结束」）—— 桌面 emit 侧不做成败过滤，订阅方用 when 自行取舍；成败标记等有
   * 消费方需要再进 payload。
   */
  'session.turn-completed': SessionTriggerBase & {
    /** 会话内用户文本消息数（≈ 已发生的轮数；含本轮） */
    turnCount: number
    /** 有正文的对话消息数（user/assistant，空文本不计） */
    textMessageCount: number
    /** 标题是否出自自动化（settings.titleOrigin === 'auto'，用户手动改名后为 false） */
    titleAutoGenerated: boolean
    /** 对话末尾文本（`User:`/`Assistant:` 拼接，尾部截断 ~1000 字） */
    recentText: string
  }
}

export type TriggerId = keyof TriggerPayloadMap

/** 一个埋点的声明（目录条目）—— 解析器/文档/UI 消费；payload 类型在 TriggerPayloadMap */
export interface TriggerPointDef {
  id: TriggerId
  /** 业务位置的一句话描述（文档/UI 用，非 LLM 面向） */
  description: string
  /**
   * 'session'：payload.sessionId 同时是 run 的归属会话 —— 派发的 agent 以它为
   * parentSessionId（工具绑定/询问路由/LLM 日志归属/面板可见都随之落到该会话）。
   * v1 的 hook 只在会话域埋点上运行：没有归属会话的 run 会让授权为空、询问被拒，
   * 那是静默降级，宁可不跑。
   */
  scope?: 'session'
}

export const TRIGGER_POINTS: Record<TriggerId, TriggerPointDef> = {
  'session.prompt-accepted': {
    id: 'session.prompt-accepted',
    description: 'A user prompt was accepted and is about to be dispatched to the session agent',
    scope: 'session'
  },
  'session.turn-completed': {
    id: 'session.turn-completed',
    description: 'A full prompt turn (including tool calls) finished in a chat session',
    scope: 'session'
  }
}

/** 按（可能未知的）字符串 id 查目录 —— 解析器用；未知 id 的绑定惰性化而非判非法 */
export function getTriggerPoint(id: string): TriggerPointDef | undefined {
  return (TRIGGER_POINTS as Record<string, TriggerPointDef>)[id]
}
