/**
 * 模型相关元数据。
 *
 * 已不再落库（v15 删掉了 sessions.modelMetadata）——唯一事实源是会话树上的
 * thinking_level_change entry。这个类型保留是因为它仍是 `agent.init` 返回给前端的形状。
 */
export interface SessionModelMetadata {
  /** 思考深度 */
  thinkingLevel?: string
}

/** 会话级配置（DB 中以 JSON 字符串存储，DAO 层负责序列化/反序列化） */
export interface SessionSettings {
  /** 命令免询问（bash + ssh 统一开关） */
  autoAllow?: boolean
  /** 路径允许列表，格式 Read(path) / Write(path)（历史 Bash/SSH 条目不再识别，等同失效） */
  allowList?: string[]
  /**
   * 扩展能力勾选（`mcp:<server>` / `skill:<name>`，只收这两类）。
   *
   * 创建会话时定下（sessionService.create：项目会话继承项目保存过的勾选 —— 项目没保存过、
   * 或不属于任何项目都为空；子会话抄父会话），
   * **只在创建 Agent 那一刻读一次**；运行时存在期间只读（写入口 updateEnabledTools 拒绝）。
   * 缺这个键的是改制前的旧会话，首次解析时按同一条继承规则补上并落库。
   */
  enabledTools?: string[]
  /**
   * 这条会话启用了哪几个知识库（用户库的目录名，或保留名 `project` = 本会话所属项目的库）。
   *
   * 与 `enabledTools` 不同，这一份**不落快照、不在创建 Agent 时读死**：知识库是 `resolveBase`
   * 每次调用现查的，所以走一条活的回落链 —— 会话设过用会话的，否则项目设过用项目的，
   * 都没设过就是「全部用户库 +（属于项目时）项目库」。改完立刻生效，运行时存在期间照样可改。
   * 空数组是明确表态「这条会话不接知识库」，与缺键（没设过）不是一回事。
   */
  knowledgeBases?: string[]
  /**
   * 这条会话绑定的 bot（`~/.shuvix/bots/<name>.md`）。有值即为 bot 会话 —— 一条**普通有根会话**：
   * 根 Agent 的档案是基座 `bot`，那份 md 的正文（人设与记忆）经 systemContext 追加到它的系统提示词
   * 末尾。创建那一刻定死，不可换绑（换个 bot 就是另开一条会话 —— 这条会话的历史全是那个 bot 说的话）。
   * 判定一律经 chat-protocol `botSession.ts` 的 `isBotSessionSettings` / `boundBotOf`。
   */
  bot?: string
  /**
   * 子会话被父级钉下的档案名（session 工具 `create-sub-session` 的 `agent_profile`，如 coding；
   * 唯一写入口 sessionService.pinAgentProfile）。根会话不读它：根 Agent 的档案由会话形态推导
   * （项目 work / 无项目 chat / 笔记本 notebook，见 resolveAgentProfileName）——旧的会话内切换
   * 写下的戳（含旧基座名 default）只是遗留数据，刻意不迁移。
   */
  agentProfile?: string
  /** 笔记本会话绑定的 md 文件（相对项目根，forward-slash；项目记忆为绝对路径）；非空即为笔记本会话（根 Agent 钉死 notebook 基座档案，对话经输入卡片的抽屉呈现） */
  notebookPath?: string
  /**
   * 项目记忆笔记本：该会话绑定的是 `~/.shuvix/memory/<projectId>/<slug>.md`。
   * 侧栏据此把它归入项目组下的「项目记忆」子文件夹，而不是并排混进会话列表。
   */
  memorySlug?: string
  /**
   * 标题最近一次由谁写入：'user' = UI 重命名，'auto' = 自动化（session 工具）。
   * 缺省视同 'user'。`session.turn-completed` 埋点的 titleAutoGenerated 即出自此处 ——
   * 自动标题据此不覆盖用户手动改过的名字。
   */
  titleOrigin?: 'user' | 'auto'
}

/** 会话数据结构（对应 DB 表 sessions） */
export interface Session {
  id: string
  title: string
  /** 所属项目 ID（null 表示临时会话） */
  projectId: string | null
  /**
   * 父会话 ID（null = 顶层会话）。非空即「子会话」：agent 经 `session` 工具自建、
   * 由它代替用户发消息驱动的一条**普通会话** —— 产品行为与顶层会话完全一致，
   * 唯一差别是侧栏把它渲染在父会话下面。嵌套只允许一层（子会话不能再开子会话）。
   */
  parentId: string | null
  /** 会话级配置（SSH 免询问等） */
  settings: SessionSettings
  createdAt: number
  /**
   * 账本时间：任何改 title / projectId / settings 的 DAO 写入都 bump
   * （含旧会话补 `enabledTools` 键）。不是「最后活跃」——日历和侧栏不读它。
   */
  updatedAt: number
  /**
   * 用户在这条会话上动过手的时间（毫秒）。新建时 = createdAt；之后只在用户消息
   * 真正落树入账时写。点开、改标题、挪项目、改会话设置、补键、自动标题、
   * pinAgentProfile、bot 文件改名都不算。侧栏按它倒序。桌面日历按
   * session_day_prompts 落日，不再按这一列。
   */
  lastActiveAt: number
}
