/**
 * 模型相关元数据。
 *
 * 已不再落库（v15 删掉了 sessions.modelMetadata）——唯一事实源是会话树上的
 * thinking_level_change / active_tools_change entry。这个类型保留是因为它仍是
 * `agent.init` 返回给前端的形状。
 */
export interface SessionModelMetadata {
  /** 思考深度 */
  thinkingLevel?: string
  /** 会话级启用的工具列表 */
  enabledTools?: string[]
}

/** 会话级配置（DB 中以 JSON 字符串存储，DAO 层负责序列化/反序列化） */
export interface SessionSettings {
  /** 命令免询问（bash + ssh 统一开关） */
  autoAllow?: boolean
  /** 路径允许列表，格式 Read(path) / Write(path)（历史 Bash/SSH 条目不再识别，等同失效） */
  allowList?: string[]
  /**
   * 聊天会话的成员 bot 名单（`~/.shuvix/bots/<name>.md`）。**非空即为聊天会话**：
   * 它没有根 Agent —— 用户消息由成员各自的管线应答，`resolveAgentProfileName` 因此返回 null。
   * 判定一律用 `bots?.length`：settings 的 JSON patch 没有删键路径，「移除全部成员」只能
   * 写 `[]`，而空数组是 truthy。
   */
  bots?: string[]
  /**
   * 会话根 Agent 采用的档案名（内置档案或 `~/.shuvix/agents/<name>.md`）。
   * 缺省 / 档案已不存在 → 回落 'default'（见 sessionService.resolveAgentProfileName）。
   */
  agentProfile?: string
  /** 笔记本会话绑定的 md 文件（相对项目根，forward-slash；项目记忆为绝对路径）；非空即为笔记本会话（根 Agent 钉死 notebook 基座档案，对话经输入卡片的抽屉呈现） */
  notebookPath?: string
  /**
   * 项目记忆笔记本：该会话绑定的是 `~/.shuvix/memory/<projectId>/<slug>.md`。
   * 侧栏据此把它归入项目组下的「项目记忆」子文件夹，而不是并排混进会话列表。
   */
  memorySlug?: string
  /**
   * 标题最近一次由谁写入：'user' = UI 重命名，'auto' = 自动化（session-config 工具）。
   * 缺省视同 'user'。`session.turn-completed` 埋点的 titleAutoGenerated 即出自此处 ——
   * 自动标题据此不覆盖用户手动改过的名字。
   */
  titleOrigin?: 'user' | 'auto'
  /**
   * 聊天会话的未读 bot 回复数（A4）。bot 落树 +1（settings 写顺带 touch updatedAt ——
   * 列表按它排序，上浮与未读同一笔账）；`session:markRead` 清零。仅聊天会话在维护。
   */
  unreadCount?: number
  /**
   * **聊天会话专属**的运行配置（v2）。
   *
   * 迁移 v15 把 provider/model 从本表删掉，理由是「运行配置的唯一事实源是会话树的
   * model_change entry」—— 那对**有根会话**成立。聊天会话没有根 Agent，v2 之后连会话树
   * 都没有（转写在 chat_messages 表里），所以它的配置需要另一个家，就是这里。
   *
   * 这不违反 v15 的单一事实源：两种会话形态的运行时根本不同，事实源各一份且互斥不相交
   * （一个会话在创建那一刻就定死是哪一种）。`chat` 前缀是为了让读代码的人一眼看出
   * 这条只对无根会话有意义。
   *
   * 刻意**不含 enabledTools**：任务段的 agent 就是 bot 自己，工具来自它 md 里的
   * `shuvix-tools`，一个会话级的工具勾选在这里不表达任何东西（对应 UI 上隐藏 ToolPicker）。
   */
  chatRunConfig?: {
    provider: string
    model: string
    thinkingLevel?: string
  }
}

/** 会话数据结构（对应 DB 表 sessions） */
export interface Session {
  id: string
  title: string
  /** 所属项目 ID（null 表示临时会话） */
  projectId: string | null
  /** 会话级配置（SSH 免询问等） */
  settings: SessionSettings
  createdAt: number
  updatedAt: number
}
