/**
 * 模型相关元数据。
 *
 * 已不再落库（v15 删掉了 sessions.modelMetadata）——唯一事实源是会话树上的
 * thinking_level_change / active_tools_change entry。这个类型保留是因为它仍是
 * `agent.init` 返回给前端的形状。
 */
export interface SessionModelMetadata {
  /** 思考深度 */
  thinkingLevel?: string
  /** 会话级启用的工具列表 */
  enabledTools?: string[]
}

/** 会话级配置（DB 中以 JSON 字符串存储，DAO 层负责序列化/反序列化） */
export interface SessionSettings {
  /** 命令免询问（bash + ssh 统一开关） */
  autoAllow?: boolean
  /** 路径允许列表，格式 Read(path) / Write(path)（历史 Bash/SSH 条目不再识别，等同失效） */
  allowList?: string[]
  /**
   * 这条会话绑定的 bot（`~/.shuvix/bots/<name>.md`）。有值即为 bot 会话 —— 一条**普通有根会话**：
   * 根 Agent 的档案是基座 `bot`，那份 md 的正文（人设与记忆）经 systemContext 追加到它的系统提示词
   * 末尾。创建那一刻定死，不可换绑（换个 bot 就是另开一条会话 —— 这条会话的历史全是那个 bot 说的话）。
   * 判定一律经 chat-protocol `botSession.ts` 的 `isBotSessionSettings` / `boundBotOf`。
   */
  bot?: string
  /**
   * 子会话被父级钉下的档案名（session 工具 `create-sub-session` 的 `agent_profile`，如 coding；
   * 唯一写入口 sessionService.pinAgentProfile）。根会话不读它：根 Agent 的档案由会话形态推导
   * （项目 work / 无项目 chat / 笔记本 notebook，见 resolveAgentProfileName）——旧的会话内切换
   * 写下的戳（含旧基座名 default）只是遗留数据，刻意不迁移。
   */
  agentProfile?: string
  /** 笔记本会话绑定的 md 文件（相对项目根，forward-slash；项目记忆为绝对路径）；非空即为笔记本会话（根 Agent 钉死 notebook 基座档案，对话经输入卡片的抽屉呈现） */
  notebookPath?: string
  /**
   * 项目记忆笔记本：该会话绑定的是 `~/.shuvix/memory/<projectId>/<slug>.md`。
   * 侧栏据此把它归入项目组下的「项目记忆」子文件夹，而不是并排混进会话列表。
   */
  memorySlug?: string
  /**
   * 标题最近一次由谁写入：'user' = UI 重命名，'auto' = 自动化（session 工具）。
   * 缺省视同 'user'。`session.turn-completed` 埋点的 titleAutoGenerated 即出自此处 ——
   * 自动标题据此不覆盖用户手动改过的名字。
   */
  titleOrigin?: 'user' | 'auto'
}

/** 会话数据结构（对应 DB 表 sessions） */
export interface Session {
  id: string
  title: string
  /** 所属项目 ID（null 表示临时会话） */
  projectId: string | null
  /**
   * 父会话 ID（null = 顶层会话）。非空即「子会话」：agent 经 `session` 工具自建、
   * 由它代替用户发消息驱动的一条**普通会话** —— 产品行为与顶层会话完全一致，
   * 唯一差别是侧栏把它渲染在父会话下面。嵌套只允许一层（子会话不能再开子会话）。
   */
  parentId: string | null
  /** 会话级配置（SSH 免询问等） */
  settings: SessionSettings
  createdAt: number
  updatedAt: number
}
