/**
 * botService 的 A2 两半：**per-bot 停止**（abortBot，粒度到 (bot, 消息)）与
 * **失败标记贯通**（say 的 error 选项 + 三处宿主失败落点 → 署名侧车 `error: true` →
 * 投影 `metadata.botFailure`）。
 *
 * 打真会话树（同 botServiceMessages / botServiceTriggers）：失败标记的断言面一半在
 * 树上的原始侧车、一半在投影产物，假树两头都测不到。假的只有 workflowService（引擎
 * 不在这一层）、sessionService、i18n 与广播出口。
 *
 * 收尾纪律（设计者风险点）：gated invoke **全放行**、每条 `handleUserMessage` 都 await
 * 到底 —— 留一个挂着的 invoke 等于把这条会话永远钉在在飞状态，红在别人的用例里。
 */
import { describe, it, expect, beforeEach, afterEach, afterAll, vi } from 'vitest'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs'
import { join } from 'path'

const dirs = vi.hoisted(() => {
  const tmp = (process.env.TMPDIR || process.env.TEMP || '/tmp').replace(/[\\/]+$/, '')
  const base = `${tmp}/shuvix-bota2-${process.pid}`
  return { base, sessions: `${base}/sessions`, bots: `${base}/bots` }
})

const mocks = vi.hoisted(() => ({
  fire: vi.fn(),
  invoke: vi.fn(),
  hasWorkflow: vi.fn((_name: string) => true),
  abortSessionRuns: vi.fn(() => 0),
  getById: vi.fn(),
  buildFacts: vi.fn(),
  isDefaultTitle: vi.fn(() => false),
  broadcast: vi.fn()
}))

vi.mock('../workflowService', () => ({
  workflowService: {
    invoke: mocks.invoke,
    abortSessionRuns: mocks.abortSessionRuns,
    hasWorkflow: mocks.hasWorkflow,
    // 槽位表来自管线的输入 schema —— 这一组不看槽位，空表即可
    agentSlots: vi.fn(() => []),
    registerRunJournalSink: vi.fn()
  },
  workflowTriggers: { fire: mocks.fire }
}))
vi.mock('electron', () => ({ shell: { openPath: vi.fn(async () => '') } }))
// v2：聊天会话转写在 chat_messages 表里。真 DAO 一经导入就会打开 sqlite
// （DatabaseManager 构造即开库，而原生绑定是 Electron ABI 的），故整个替换成内存版
vi.mock('../../dao/chatMessageDao', async () => await import('./fakeChatMessageDao'))
vi.mock('../../utils/paths', () => ({
  // v2 起 botService 经 chatMessageDao 触到 DatabaseManager，它的构造读 getDataDir
  getDataDir: () => join(dirs.base, 'data'),
  getChatAttachmentsDir: (sid: string) => join(dirs.base, 'data', 'chat-attachments', sid),
  getSessionsDir: () => dirs.sessions,
  getDefaultBotsDir: () => dirs.bots,
  // botService → agentService 的模块作用域构造器在 import 阶段就要它
  getDefaultAgentsDir: () => `${dirs.base}/agents`
}))
vi.mock('../../logger', () => ({
  createLogger: () => ({ info: () => {}, warn: () => {}, error: () => {} })
}))
// 会话可见文案走 i18n —— 断言用 key 而不是某一种语言的串
vi.mock('../../i18n', () => ({ t: (key: string) => key }))
vi.mock('../agentRuntimeAdapters', () => ({ electronEventSink: { broadcast: mocks.broadcast } }))
vi.mock('../sessionTriggerFacts', () => ({
  buildTurnCompletedFacts: mocks.buildFacts,
  isDefaultTitle: mocks.isDefaultTitle
}))
vi.mock('../sessionService', () => ({
  // noteUnreadBotReply：A4 起 appendBotMessage 每次落树都记未读账 —— 本组用例不关心它,给 no-op
  sessionService: { getById: mocks.getById, noteUnreadBotReply: () => {} }
}))

import type { ChatMessage } from '@shuvix/chat-protocol/types/chatMessage'
import { botService } from '../botService'
import { messageService, setChatSessionPredicate } from '../messageService'
import { clearSessionTreeCacheForTests } from '../sessionStorage'

/** 每条用例一条新会话（botService 是模块级单例，按会话 id 记着在飞计数与消息序） */
let SID = 'a2-sess'
let sidSeq = 0

const FACTS = {
  title: 'Some title',
  isDefaultTitle: false,
  titleAutoGenerated: false,
  turnCount: 1,
  textMessageCount: 2,
  recentText: 'User: hi'
}

function writeBot(
  name: string,
  opts: {
    displayName?: string
    /** `shuvix-bot-pipeline.workflow` —— 必填；缺省内置 bot-chat（模板的缺省，解析器没有缺省） */
    pipeline?: string
    agents?: Record<string, string>
    input?: Record<string, unknown>
  } = {}
): void {
  mkdirSync(dirs.bots, { recursive: true })
  const lines = ['---', 'shuvix: bot v1', `name: ${name}`, `description: unit bot ${name}`]
  if (opts.displayName) lines.push(`shuvix-displayName: ${opts.displayName}`)
  // 管线绑定是一个嵌套块：workflow 必填，agents / input 是它的从属项
  lines.push('shuvix-bot-pipeline:', `  workflow: ${opts.pipeline ?? 'bot-chat'}`)
  if (opts.agents) {
    lines.push('  agents:')
    for (const [k, v] of Object.entries(opts.agents)) lines.push(`    ${k}: ${v}`)
  }
  if (opts.input) {
    lines.push('  input:')
    for (const [k, v] of Object.entries(opts.input)) lines.push(`    ${k}: ${JSON.stringify(v)}`)
  }
  lines.push('---', '', 'BOT BODY.')
  writeFileSync(join(dirs.bots, `${name}.md`), lines.join('\n'))
}

const seedSession = (bots: string[]): void => {
  mocks.getById.mockReturnValue({
    workingDirectory: dirs.sessions,
    title: 'Some title',
    settings: { bots }
  })
}

/** 某个埋点 id 的全部 payload */
const fired = (id: string): Array<Record<string, unknown>> =>
  mocks.fire.mock.calls.filter((c) => c[0] === id).map((c) => c[1] as Record<string, unknown>)

/** 某个 bot 的决策记录 kind 序列 */
function kindsOf(botName: string): string[] {
  const file = join(dirs.bots, '.runs', botName, 'decisions.jsonl')
  if (!existsSync(file)) return []
  return readFileSync(file, 'utf-8')
    .trim()
    .split('\n')
    .filter(Boolean)
    .map((l) => String((JSON.parse(l) as Record<string, unknown>).kind))
}

/** 广播出去的 ChatEvent（按 type 过滤） */
const broadcasts = (type: string): Array<Record<string, unknown>> =>
  mocks.broadcast.mock.calls
    .map((c) => c[0] as Record<string, unknown>)
    .filter((e) => e.type === type)

const ran = (
  output: Record<string, unknown> = { gate: 'ok', outcome: 'reply' }
): Record<string, unknown> => ({ started: true, ok: true, output })

/** 一次被门控住的 invoke 调用 —— 记下票面（input / signal / extraApi），由测试放行 */
interface GatedCall {
  input: { message: { id: string } }
  signal: AbortSignal
  api: {
    say: (raw: unknown, opts?: unknown) => Promise<{ messageId: string | null }>
  }
  finish: (result?: Record<string, unknown>) => void
}

/**
 * 逐调用门控：每次 invoke 挂起并记录，由测试逐个放行。
 * **每个拿到的 call 都必须 finish** —— 否则这条会话永远在飞（收尾纪律）。
 */
function gateCalls(): { calls: GatedCall[]; wait: (n: number) => Promise<void> } {
  const calls: GatedCall[] = []
  mocks.invoke.mockImplementation(
    (req: {
      input: { message: { id: string } }
      signal: AbortSignal
      extraApi: GatedCall['api']
    }) =>
      new Promise((resolve) => {
        calls.push({
          input: req.input,
          signal: req.signal,
          api: req.extraApi,
          finish: (result = ran()) => resolve(result)
        })
      })
  )
  return {
    calls,
    wait: (n) => vi.waitFor(() => expect(calls.length).toBeGreaterThanOrEqual(n))
  }
}

const prompt = (text = 'hello'): Promise<void> =>
  botService.handleUserMessage({ sessionId: SID, text } as never)

/** 表里最后一条 bot 行 —— v2 的「原始存储」就是这一行（decision / error 都是列） */
async function lastSidecarData(): Promise<Record<string, unknown>> {
  const { chatMessageDao } = await import('./fakeChatMessageDao')
  const row = chatMessageDao.findLastBot(SID)
  if (!row) throw new Error('no bot message')
  return {
    botName: row.botName,
    displayName: row.displayName,
    ...(row.decision ? { decision: row.decision } : {}),
    ...(row.reply ? { reply: JSON.parse(row.reply) } : {}),
    ...(row.isError ? { error: true } : {})
  } as Record<string, unknown>
}

// v2：messageService 靠注入的谓词分流「聊天会话读表 / 有根会话读树」。
// 真件在 botService.init() 里注册，用例不走那条路，所以这里直接把本文件的会话全判为聊天会话
setChatSessionPredicate(() => true)

beforeEach(() => {
  sidSeq += 1
  SID = `a2-sess-${sidSeq}`
  rmSync(dirs.base, { recursive: true, force: true })
  mkdirSync(dirs.sessions, { recursive: true })
  mkdirSync(dirs.bots, { recursive: true })
  clearSessionTreeCacheForTests()
  for (const m of Object.values(mocks)) m.mockReset()
  mocks.hasWorkflow.mockReturnValue(true)
  mocks.abortSessionRuns.mockReturnValue(0)
  mocks.isDefaultTitle.mockReturnValue(false)
  mocks.invoke.mockResolvedValue(ran())
  mocks.buildFacts.mockResolvedValue(FACTS)
  writeBot('scout', { displayName: 'Scout' })
  seedSession(['scout'])
})

afterEach(() => {
  vi.restoreAllMocks()
})

afterAll(() => {
  rmSync(dirs.base, { recursive: true, force: true })
})

// ────────────────────────── AB：per-bot 停止 ──────────────────────────

describe('AB —— abortBot（粒度到 (bot, 消息)）', () => {
  it('A2-B7 命中在飞票 → true，且门控住的 invoke 的 req.signal 落下', async () => {
    const g = gateCalls()
    const msg = prompt('停我这条')
    await g.wait(1)
    const messageId = g.calls[0].input.message.id
    expect(g.calls[0].signal.aborted).toBe(false)

    expect(botService.abortBot(SID, 'scout', messageId)).toBe(true)
    expect(g.calls[0].signal.aborted).toBe(true)

    g.calls[0].finish()
    await msg
  })

  it('A2-B8 messageId / botName / sessionId 任一不匹配 → false，signal 不动', async () => {
    const g = gateCalls()
    const msg = prompt('别人停不了我')
    await g.wait(1)
    const messageId = g.calls[0].input.message.id

    expect(botService.abortBot(SID, 'scout', 'not-this-message')).toBe(false)
    expect(botService.abortBot(SID, 'ranger', messageId)).toBe(false)
    expect(botService.abortBot('another-session', 'scout', messageId)).toBe(false)
    expect(g.calls[0].signal.aborted).toBe(false)

    g.calls[0].finish()
    await msg
  })

  it('A2-B9 中止后 {started:true, ok:false} 收尾 → 无 runFailed 气泡；run_end 照记、turn-completed 照 fire', async () => {
    // §9.1：用户按的停止不是「无从解释的沉默」—— 兜底气泡被 !signal.aborted 守卫压掉，
    // 但这一轮的账（run_end 决策、轮结束埋点）一分不少
    const g = gateCalls()
    const msg = prompt('停了别再道歉')
    await g.wait(1)
    botService.abortBot(SID, 'scout', g.calls[0].input.message.id)

    g.calls[0].finish({ started: true, ok: false, error: 'aborted by user' })
    await msg

    const msgs = await messageService.listBySession(SID)
    expect(msgs.filter((m) => m.role === 'assistant')).toHaveLength(0)
    expect(msgs.some((m) => m.content === 'bot.runFailed')).toBe(false)
    expect(kindsOf('scout')).toContain('run_end')
    expect(fired('session.turn-completed')).toHaveLength(1)
  })

  it('A2-B10 同 bot 两条消息在飞：abortBot(msg1) 只落 msg1 的 signal，msg2 照常 say 落树', async () => {
    const g = gateCalls()
    const m1 = prompt('第一条')
    await g.wait(1)
    const m2 = prompt('第二条')
    await g.wait(2)

    botService.abortBot(SID, 'scout', g.calls[0].input.message.id)
    expect(g.calls[0].signal.aborted).toBe(true)
    expect(g.calls[1].signal.aborted).toBe(false)

    // 被停的那条不说话收尾；另一条照常 say —— 粒度是 (bot, 消息)，不是整个 bot
    g.calls[0].finish({ started: true, ok: false })
    await expect(g.calls[1].api.say('第二条照常回答')).resolves.toMatchObject({
      messageId: expect.any(String)
    })
    g.calls[1].finish()
    await Promise.all([m1, m2])

    const replies = (await messageService.listBySession(SID)).filter((m) => m.role === 'assistant')
    expect(replies.map((m) => m.content)).toEqual(['第二条照常回答'])
  })
})

// ────────────────────────── SE：say 的 error 选项 ──────────────────────────

describe('SE —— say(…, { error }) 写进署名侧车', () => {
  /** 单 bot 会话跑一轮，让脚本侧调一次 say 后正常收尾 */
  async function sayOnce(raw: unknown, opts?: unknown): Promise<void> {
    const g = gateCalls()
    const msg = prompt('说一句')
    await g.wait(1)
    await g.calls[0].api.say(raw, opts)
    g.calls[0].finish()
    await msg
  }

  it('A2-B11 say("x", {error:true, decision:"clarify"})：侧车有 error:true、**无** decision 键', async () => {
    // 降级出声绝不带 decision —— 否则一条 clarify 会把用户的下一条无关消息
    // 硬路由回这个刚出过故障的 bot
    await sayOnce('x', { error: true, decision: 'clarify' })

    const data = await lastSidecarData()
    expect(data.error).toBe(true)
    expect(data).not.toHaveProperty('decision')
    expect(data).toMatchObject({ botName: 'scout', displayName: 'Scout' })
  })

  it('A2-B12 say("x", {error:"true"})：赃值不上车 —— 侧车无 error 键；decision 照常写入', async () => {
    // error 的收窄口径是 === true：字符串 "true" 不算降级出声，
    // 于是「不带 decision」那条纪律也不触发
    await sayOnce('x', { error: 'true', decision: 'clarify' })

    const data = await lastSidecarData()
    expect(data).not.toHaveProperty('error')
    expect(data.decision).toBe('clarify')
  })

  it('A2-B13 say(结构化, {error:true})：reply 与 error 共存 —— 降级通告也可以带结构', async () => {
    await sayOnce({ headline: '出错但有结构', body: '带着结构的降级通告。' }, { error: true })

    const data = await lastSidecarData()
    expect(data.error).toBe(true)
    expect(data.reply).toMatchObject({ headline: '出错但有结构', body: '带着结构的降级通告。' })
  })
})

// ────────────────────────── HF：三处宿主失败落点 ──────────────────────────

/**
 * 三处宿主失败都要把 error 写进侧车、投影成 `metadata.botFailure === true` ——
 * 每条换新 bot 名（gateHealth 是进程级 sticky 的，且不该为测试开复位后门）。
 */
describe('HF —— 宿主失败落树带 error', () => {
  it('A2-B14a 管线缺失的可见失败 → metadata.botFailure === true', async () => {
    mocks.hasWorkflow.mockImplementation((name: string) => name !== 'nope-flow')
    writeBot('hf-miss', { displayName: 'Miss', pipeline: 'nope-flow' })
    seedSession(['hf-miss'])
    await prompt('这条没人接得住')

    await vi.waitFor(async () => {
      const msgs = await messageService.listBySession(SID)
      const bubble = msgs.find((m) => m.content === 'bot.pipelineMissing')
      expect(bubble).toBeDefined()
      expect((bubble!.metadata as { botFailure?: unknown }).botFailure).toBe(true)
    })
  })

  it('A2-B14b runFailed 兜底气泡 → metadata.botFailure === true', async () => {
    writeBot('hf-fail', { displayName: 'Fail' })
    seedSession(['hf-fail'])
    mocks.invoke.mockResolvedValue({ started: true, ok: false, error: 'boom' })
    await prompt('这条会失败')

    await vi.waitFor(async () => {
      const msgs = await messageService.listBySession(SID)
      const bubble = msgs.find((m) => m.content === 'bot.runFailed')
      expect(bubble).toBeDefined()
      expect((bubble!.metadata as { botFailure?: unknown }).botFailure).toBe(true)
    })
  })

  it('A2-B14c 门控回落提示 → metadata.botFailure === true（脱手 .catch 落树，须 waitFor）', async () => {
    writeBot('hf-gate', { displayName: 'Gate' })
    seedSession(['hf-gate'])
    mocks.invoke.mockResolvedValue(ran({ gate: 'broken', outcome: 'gate-broken' }))
    await prompt('一')
    await prompt('二')

    // 回落提示刻意不在这一轮的关键路径上（.catch 而非 await）—— 等它落定
    await vi.waitFor(async () => {
      const msgs = await messageService.listBySession(SID)
      const bubble = msgs.find((m) => m.content === 'bot.gateFallback')
      expect(bubble).toBeDefined()
      expect((bubble!.metadata as { botFailure?: unknown }).botFailure).toBe(true)
    })
  })
})

// ────────────────────────── BR：广播与重开同源 ──────────────────────────

describe('BR —— error 消息的广播与 message.list 同源', () => {
  it('A2-B15 appendBotMessage(error:true) 的 assistant_message 与 message.list 同 id 逐字段全等，botFailure === true', async () => {
    const id = await botService.appendBotMessage(
      SID,
      { botName: 'scout', displayName: 'Scout', error: true },
      { content: '⚠️ 这条没办成' }
    )
    expect(id).toBeTruthy()

    const evt = broadcasts('assistant_message').find((e) => e.messageId === id)!
    expect(evt).toBeDefined()
    const streamed = JSON.parse(evt.message as string) as ChatMessage
    const reopened = (await messageService.listBySession(SID)).find((m) => m.id === id)

    // 流式所见即重开所见 —— botFailure 若只在其中一条路径上成型，刷新一下失败卡就没了
    expect(reopened).toEqual(streamed)
    expect((streamed.metadata as { botFailure?: unknown }).botFailure).toBe(true)
  })
})
