/**
 * botService 的三条**跨模块接线**：会话域埋点（TR）、abortSession 的会师点（WI）、
 * 门控段的健康度与回落（GH）。
 *
 * 三者的共同点是它们都不是一张表 —— 表在 botServicePipeline.test.ts。这里测的是
 * **顺序与时机**：埋点在哪一刻带着什么事实发出、禁写位在谁都走完之前不许撤、
 * 连续几次故障之后才换掉那个门控 agent。顺序错了不会报错，只会在某次真实会话里表现为
 * 「工作流莫名其妙不触发」「删会话之后树上多了一条孤儿消息」「它忽然变得不一样了」。
 *
 * **打真会话树**（同 botServiceMessages）：埋点的事实、窗口构建、可见提示的落树都要经过它。
 * 假的只有 workflowService（引擎不在这一层的测试范围）、sessionService、i18n 与广播出口。
 */
import { describe, it, expect, beforeEach, afterEach, afterAll, vi } from 'vitest'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs'
import { join } from 'path'

const dirs = vi.hoisted(() => {
  const tmp = (process.env.TMPDIR || process.env.TEMP || '/tmp').replace(/[\\/]+$/, '')
  const base = `${tmp}/shuvix-bottrig-${process.pid}`
  return { base, sessions: `${base}/sessions`, bots: `${base}/bots` }
})

const mocks = vi.hoisted(() => ({
  fire: vi.fn(),
  invoke: vi.fn(),
  hasWorkflow: vi.fn(() => true),
  abortSessionRuns: vi.fn(() => 0),
  getById: vi.fn(),
  buildFacts: vi.fn(),
  isDefaultTitle: vi.fn(() => false),
  broadcast: vi.fn(),
  warn: vi.fn()
}))

vi.mock('../workflowService', () => ({
  workflowService: {
    invoke: mocks.invoke,
    abortSessionRuns: mocks.abortSessionRuns,
    hasWorkflow: mocks.hasWorkflow,
    // 槽位表来自管线的输入 schema —— 这一组不看槽位，空表即可
    agentSlots: vi.fn(() => []),
    registerRunJournalSink: vi.fn()
  },
  workflowTriggers: { fire: mocks.fire }
}))
vi.mock('electron', () => ({ shell: { openPath: vi.fn(async () => '') } }))
// v2：聊天会话转写在 chat_messages 表里。真 DAO 一经导入就会打开 sqlite
// （DatabaseManager 构造即开库，而原生绑定是 Electron ABI 的），故整个替换成内存版
vi.mock('../../dao/chatMessageDao', async () => await import('./fakeChatMessageDao'))
vi.mock('../../utils/paths', () => ({
  // v2 起 botService 经 chatMessageDao 触到 DatabaseManager，它的构造读 getDataDir
  getDataDir: () => join(dirs.base, 'data'),
  getChatAttachmentsDir: (sid: string) => join(dirs.base, 'data', 'chat-attachments', sid),
  getSessionsDir: () => dirs.sessions,
  getDefaultBotsDir: () => dirs.bots,
  // botService → agentService 的模块作用域构造器在 import 阶段就要它
  getDefaultAgentsDir: () => `${dirs.base}/agents`
}))
vi.mock('../../logger', () => ({
  createLogger: () => ({ info: () => {}, warn: mocks.warn, error: () => {} })
}))
// 会话可见文案走 i18n —— 断言用 key 而不是某一种语言的串（三种语言都有这几条）
vi.mock('../../i18n', () => ({ t: (key: string) => key }))
vi.mock('../agentRuntimeAdapters', () => ({ electronEventSink: { broadcast: mocks.broadcast } }))
vi.mock('../sessionTriggerFacts', () => ({
  buildTurnCompletedFacts: mocks.buildFacts,
  isDefaultTitle: mocks.isDefaultTitle
}))
vi.mock('../sessionService', () => ({
  // noteUnreadBotReply：A4 起 appendBotMessage 每次落树都记未读账 —— 本组用例不关心它,给 no-op
  sessionService: { getById: mocks.getById, noteUnreadBotReply: () => {} }
}))

import { botService } from '../botService'
import { messageService, setChatSessionPredicate } from '../messageService'
import { clearSessionTreeCacheForTests, withSessionTreeLock } from '../sessionStorage'

/**
 * **每条用例一条新会话**。botService 是模块级单例，它按会话 id 记着在飞计数、禁写位、
 * clarify 消费集与消息序号；而回落提示这类写入刻意脱手（`.catch` 而非 await），
 * 于是上一条用例的尾巴可能落在下一条用例刚建好的树上。换个 id 比给生产代码开复位后门干净。
 */
let SID = 'trig-sess'
let sidSeq = 0

/** buildTurnCompletedFacts 的一份现成事实（它自己的单测在 sessionTriggerFacts.test.ts） */
const FACTS = {
  title: 'Some title',
  isDefaultTitle: false,
  titleAutoGenerated: false,
  turnCount: 1,
  textMessageCount: 2,
  recentText: 'User: hi\nAssistant: yo'
}

function writeBot(
  name: string,
  opts: { displayName?: string; agents?: Record<string, string> } = {}
): void {
  mkdirSync(dirs.bots, { recursive: true })
  const lines = ['---', 'shuvix: bot v1', `name: ${name}`, `description: unit bot ${name}`]
  if (opts.displayName) lines.push(`shuvix-displayName: ${opts.displayName}`)
  if (opts.agents) {
    lines.push('shuvix-bot-agents:')
    for (const [k, v] of Object.entries(opts.agents)) lines.push(`  ${k}: ${v}`)
  }
  lines.push('---', '', 'BOT BODY.')
  writeFileSync(join(dirs.bots, `${name}.md`), lines.join('\n'))
}

const seedSession = (bots: string[], title = 'Some title'): void => {
  mocks.getById.mockReturnValue({ workingDirectory: dirs.sessions, title, settings: { bots } })
}

/** 某个埋点 id 的全部 payload */
const fired = (id: string): Array<Record<string, unknown>> =>
  mocks.fire.mock.calls.filter((c) => c[0] === id).map((c) => c[1] as Record<string, unknown>)

/** 某个 bot 的决策记录（一行一条 JSON） */
function decisions(botName: string): Array<Record<string, unknown>> {
  const file = join(dirs.bots, '.runs', botName, 'decisions.jsonl')
  if (!existsSync(file)) return []
  return readFileSync(file, 'utf-8')
    .trim()
    .split('\n')
    .filter(Boolean)
    .map((l) => JSON.parse(l) as Record<string, unknown>)
}

const kindsOf = (botName: string): string[] => decisions(botName).map((d) => String(d.kind))

/** 一次管线 invoke 的结果 —— 缺省「跑完了，门控正常」 */
const ran = (
  output: Record<string, unknown> = { gate: 'ok', outcome: 'reply' }
): { started: boolean; ok: boolean; output: Record<string, unknown> } => ({
  started: true,
  ok: true,
  output
})

/** 拿住写锁并卡住，返回释放函数 —— 用来造「在飞」的确定性窗口 */
function holdLock(sid?: string): { release: () => void; done: Promise<void> } {
  const target = sid ?? SID
  let release: () => void = () => {}
  const gate = new Promise<void>((r) => {
    release = r
  })
  return { release, done: withSessionTreeLock(target, () => gate, dirs.sessions) }
}

/**
 * 让 invoke 挂起，返回放行函数。
 *
 * 放行是**一次性开闸**而不是「把此刻排队的放掉」：管线起跑要经过落树 + 投影 + 窗口构建
 * 好几个 await，测试端很难精确等到那一刻，而漏掉一次尚未到达的 invoke 就会让这条会话
 * 永远停在在飞状态 —— 表现为一条与被测行为毫无关系的超时。
 */
function gateInvoke(output: Record<string, unknown> = { gate: 'ok', outcome: 'reply' }): {
  release: () => void
} {
  const waiters: Array<() => void> = []
  let open = false
  mocks.invoke.mockImplementation(() =>
    open
      ? Promise.resolve(ran(output))
      : new Promise((resolve) => waiters.push(() => resolve(ran(output))))
  )
  return {
    release: () => {
      open = true
      for (const w of waiters.splice(0)) w()
    }
  }
}

const prompt = (text = 'hello', over: Record<string, unknown> = {}): Promise<void> =>
  botService.handleUserMessage({ sessionId: SID, text, ...over } as never)

// v2：messageService 靠注入的谓词分流「聊天会话读表 / 有根会话读树」。
// 真件在 botService.init() 里注册，用例不走那条路，所以这里直接把本文件的会话全判为聊天会话
setChatSessionPredicate(() => true)

beforeEach(() => {
  sidSeq += 1
  SID = `trig-sess-${sidSeq}`
  rmSync(dirs.base, { recursive: true, force: true })
  mkdirSync(dirs.sessions, { recursive: true })
  mkdirSync(dirs.bots, { recursive: true })
  clearSessionTreeCacheForTests()
  for (const m of Object.values(mocks)) m.mockReset()
  mocks.hasWorkflow.mockReturnValue(true)
  mocks.abortSessionRuns.mockReturnValue(0)
  mocks.isDefaultTitle.mockReturnValue(false)
  mocks.invoke.mockResolvedValue(ran())
  mocks.buildFacts.mockResolvedValue(FACTS)
  writeBot('scout', { displayName: 'Scout' })
  seedSession(['scout'])
})

afterEach(() => {
  vi.useRealTimers()
  vi.restoreAllMocks()
})

afterAll(() => {
  rmSync(dirs.base, { recursive: true, force: true })
})

// ────────────────────────── TR：会话域埋点 ──────────────────────────

/**
 * **聊天会话也 fire** —— 用户工作流因此能旁观这里发生的事（auto-title 也就顺带对聊天
 * 会话生效了）。payload 只是会话此刻的事实，与订阅方无关：这一组的每条断言都在守
 * 「emit 侧不替订阅方做判断」这条纪律。
 */
describe('TR —— 埋点', () => {
  it('TR-1 用户消息落盘之后 fire session.prompt-accepted 一次', async () => {
    await prompt('hello there')
    const [p] = fired('session.prompt-accepted')
    expect(fired('session.prompt-accepted')).toHaveLength(1)
    expect(p).toMatchObject({ sessionId: SID, promptText: 'hello there', bots: ['scout'] })
  })

  it('TR-2 profileName 是空串 —— 无根会话没有档案名，编一个不如空着', async () => {
    // 订阅方要区分会话种类看的是 bots 的有无，不是 profileName 的真假
    await prompt()
    expect(fired('session.prompt-accepted')[0].profileName).toBe('')
  })

  it('TR-3 promptText 是**展开后的全文**，不是标记态原文', async () => {
    // 内联 Token 在标记态里是一串占位符 —— 订阅方（如起标题）拿到的必须是模型看到的那一份
    await prompt('看看 {{shuvixInlineToken:t0}} 这个', {
      inlineTokens: {
        t0: {
          type: 'at',
          id: 'src/a.ts',
          displayText: 'a.ts',
          payload: '[workspace file: src/a.ts]'
        }
      }
    })
    const text = String(fired('session.prompt-accepted')[0].promptText)
    expect(text).toContain('[workspace file: src/a.ts]')
    expect(text).not.toContain('shuvixInlineToken')
  })

  it('TR-4 bots 现取 —— 名单随时可能被 updateBots 改，不能用建会话时的快照', async () => {
    seedSession(['scout', 'ranger'])
    await prompt()
    expect(fired('session.prompt-accepted')[0].bots).toEqual(['scout', 'ranger'])
  })

  it('TR-5 isDefaultTitle 现算（默认标题随语言变，不是一个常量）', async () => {
    mocks.isDefaultTitle.mockReturnValue(true)
    seedSession(['scout'], 'New Chat')
    await prompt()
    expect(fired('session.prompt-accepted')[0]).toMatchObject({
      title: 'New Chat',
      isDefaultTitle: true
    })
  })

  it('TR-6 一轮结束 fire session.turn-completed 一次，事实来自共用的构造器', async () => {
    await prompt()
    const turns = fired('session.turn-completed')
    expect(turns).toHaveLength(1)
    expect(turns[0]).toMatchObject({ sessionId: SID, profileName: '', bots: ['scout'], ...FACTS })
  })

  it('TR-7 一轮 = cohort 整体，不是每个成员一次', async () => {
    // 逐成员 fire 会让订阅方（auto-title）在一条消息上起 N 个 run，而它们互相 skip 的
    // 结果取决于谁先跑到
    writeBot('ranger', { displayName: 'Ranger' })
    seedSession(['scout', 'ranger'])
    await prompt()
    expect(fired('session.turn-completed')).toHaveLength(1)
  })

  it('TR-8 事实构造器返回 null（会话已被删）→ 不 fire（不编一份事实出来）', async () => {
    mocks.buildFacts.mockResolvedValue(null)
    await prompt()
    expect(fired('session.turn-completed')).toHaveLength(0)
    // prompt-accepted 仍然发了 —— 它的事实是同步取的，那一刻会话还在
    expect(fired('session.prompt-accepted')).toHaveLength(1)
  })

  it('TR-9 【L0 全筛掉也算一轮】名单里的成员 md 全没了、没人被唤起时仍 fire turn-completed', async () => {
    // 有根会话那侧的契约是「无论成败恒触发」。两边在「什么时候算一轮」上错开，订阅方
    // 看到的就是「某类会话的工作流莫名其妙不触发」。v3 起 L0 能筛掉成员的原因只剩一种：
    // 名单里的 md 不在了（没有 mention-only 这类逐 bot 的门控模式，在册的成员必然进 cohort）
    seedSession(['ghost'])
    await prompt('没有人接得住')

    expect(mocks.invoke).not.toHaveBeenCalled()
    expect(kindsOf('ghost')).toEqual(['l0_member_missing'])
    expect(fired('session.turn-completed')).toHaveLength(1)
  })

  it('TR-10 名单为空 → 不 fire turn-completed（这条会话根本不是聊天会话）', async () => {
    // 与上一条的区别是**分不出成员**与**没有成员**：后者压根没有「一轮」这回事
    seedSession([])
    await prompt()
    expect(fired('session.turn-completed')).toHaveLength(0)
    expect(fired('session.prompt-accepted')).toHaveLength(1)
  })

  it('TR-11 【键集之差恰为 bots】聊天会话的 turn-completed 就是有根会话那份加一个成员名单', async () => {
    // 有根会话那侧铺的是 {sessionId, profileName, ...facts}（agentSession.fireTurnCompleted），
    // 聊天会话多一个 bots。端到端的那份对照在 e2e 的 task.e2e.ts（E-3），这里钉的是本侧
    await prompt()
    const keys = Object.keys(fired('session.turn-completed')[0]).sort()
    const rooted = ['sessionId', 'profileName', ...Object.keys(FACTS)].sort()
    expect(keys.filter((k) => !rooted.includes(k))).toEqual(['bots'])
    expect(rooted.filter((k) => !keys.includes(k))).toEqual([])
  })

  it('TR-12 埋点顺序：prompt-accepted 在派发之前，turn-completed 在全员收尾之后', async () => {
    const order: string[] = []
    mocks.fire.mockImplementation((id: string) => order.push(id))
    mocks.invoke.mockImplementation(async () => {
      order.push('invoke')
      return ran()
    })
    await prompt()
    expect(order).toEqual(['session.prompt-accepted', 'invoke', 'session.turn-completed'])
  })

  it('TR-13 用户消息先落树再 fire —— 订阅方读会话时那条消息必须已经在', async () => {
    // 订阅方（auto-title 的 quick 绑定就是其一）会立刻回头读这条会话。埋点跑在落树之前的话，
    // 它读到的是一条还没有这句话的会话 —— 而这种错序不会报错，只会让标题总是慢一拍
    let readAtFire: ReturnType<typeof messageService.listBySession> | null = null
    mocks.fire.mockImplementation((id: string) => {
      if (id === 'session.prompt-accepted') readAtFire = messageService.listBySession(SID)
    })
    await prompt('落树顺序')

    expect(readAtFire).not.toBeNull()
    const msgs = await readAtFire!
    expect(msgs.some((m) => m.role === 'user' && String(m.content).includes('落树顺序'))).toBe(true)
  })

  it('TR-14 一个成员的管线炸了不拖垮埋点（cohort 的结局仍然要收）', async () => {
    mocks.invoke.mockRejectedValue(new Error('boom'))
    await prompt()
    expect(fired('session.turn-completed')).toHaveLength(1)
  })

  it('TR-15 payload 里没有任何工作流的名字 —— 埋点不知道谁在订阅', async () => {
    await prompt()
    for (const p of [...fired('session.prompt-accepted'), ...fired('session.turn-completed')]) {
      expect(JSON.stringify(p)).not.toContain('auto-title')
      expect(JSON.stringify(p)).not.toContain('bot-chat')
    }
  })
})

// ────────────────────────── WI：abortSession 的会师点 ──────────────────────────

/**
 * `abortSession` 的契约是：**Promise 落定时保证不会再有人写这棵树**。三个调用点
 * （回退 / 清空 / 删除会话）都拿它当动树之前的安全前提，所以这一组每条都在问同一件事 ——
 * 「这一刻还有谁可能再拿一次写锁？」
 */
describe('WI —— 会师点', () => {
  it('WI-1 没有在飞的东西 → 立即落定', async () => {
    await expect(botService.abortSession(SID)).resolves.toBeUndefined()
  })

  it('WI-2 管线在飞 → 等它收尾之后才落定', async () => {
    const gate = gateInvoke()
    const msg = prompt()
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalled())

    let done = false
    const abort = botService.abortSession(SID).then(() => {
      done = true
    })
    await new Promise((r) => setTimeout(r, 30))
    expect(done).toBe(false)

    gate.release()
    await abort
    expect(done).toBe(true)
    await msg
  })

  it('WI-3 【带上限】卡死的脚本不把「删除会话」永久挂住', async () => {
    // 宁可让极端情况下多出一次并发写（树是 append-only 的，最坏是多一条孤儿 entry），
    // 也不能让界面卡在那里
    const gate = gateInvoke()
    const msg = prompt()
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalled())

    vi.useFakeTimers()
    const abort = botService.abortSession(SID)
    await vi.advanceTimersByTimeAsync(5_100)
    await abort
    expect(mocks.warn.mock.calls.some((c) => String(c[0]).includes('仍未收尾'))).toBe(true)

    vi.useRealTimers()
    gate.release()
    await msg
  })

  it('WI-4 落定之后禁写位被撤掉（中止只管那一轮，不是把会话永久锁死）', async () => {
    await botService.abortSession(SID)
    const id = await botService.appendBotMessage(
      SID,
      { botName: 'scout', displayName: 'Scout' },
      { content: '中止之后仍能说话' }
    )
    expect(id).toBeTruthy()
  })

  it('WI-5 在飞期间禁写：这一刻的落树请求被拒（返回 null 而不是偷偷写进去）', async () => {
    const gate = gateInvoke()
    const msg = prompt()
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalled())

    const abort = botService.abortSession(SID)
    const blocked = await botService.appendBotMessage(
      SID,
      { botName: 'scout', displayName: 'Scout' },
      { content: '这条不该落树' }
    )
    expect(blocked).toBeNull()

    gate.release()
    await abort
    await msg
  })

  it('WI-6 【引用计数】两次重叠的中止，先落定的那个不撤禁写位', async () => {
    // 四个入口（回退 / 清空 / 删除会话 / 网关 abort）可以重叠，而 whenIdle 把驻留窗口
    // 从毫秒级 drain 拉到秒级 —— 先完成的那个若直接撤掉禁写位，另一个还在等的中止
    // 就失去了它赖以成立的前提
    const hold = holdLock()
    // A：此刻没有在飞的管线，whenIdle 立刻过，卡在 drain 上
    const a = botService.abortSession(SID)

    const gate = gateInvoke()
    const msg = prompt()
    // B：管线在飞，whenIdle 要等
    const b = botService.abortSession(SID)

    hold.release()
    await hold.done
    await a

    // A 已经落定，但 B 还在等 —— 禁写位必须还在
    const blocked = await botService.appendBotMessage(
      SID,
      { botName: 'scout', displayName: 'Scout' },
      { content: 'A 走了但 B 还没' }
    )
    expect(blocked).toBeNull()

    gate.release()
    await b
    await msg
    // 最后一个也走了 → 恢复可写
    expect(
      await botService.appendBotMessage(
        SID,
        { botName: 'scout', displayName: 'Scout' },
        { content: '两个都走了' }
      )
    ).toBeTruthy()
  })

  it('WI-7 中止时把该拆的都拆了：引擎的 run、以及在飞的询问', async () => {
    const gate = gateInvoke()
    const msg = prompt()
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalled())

    const abort = botService.abortSession(SID)
    expect(mocks.abortSessionRuns).toHaveBeenCalledWith(SID)
    // 门关上了：中止之后到达的询问立刻取消，而不是挂在那里等一个不会来的答复
    await expect(
      botService.requestUserInput(SID, { requestId: 'r1', kind: 'text', prompt: 'q' } as never)
    ).resolves.toMatchObject({ kind: 'cancel' })

    gate.release()
    await abort
    await msg
  })

  it('WI-8 传给管线的 signal 在中止时落下（脚本据此安静退出）', async () => {
    const gate = gateInvoke()
    const msg = prompt()
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalled())
    const signal = (mocks.invoke.mock.calls[0][0] as { signal?: AbortSignal }).signal!
    expect(signal.aborted).toBe(false)

    const abort = botService.abortSession(SID)
    expect(signal.aborted).toBe(true)

    gate.release()
    await abort
    await msg
  })

  it('WI-9 【fire 在会师点之内】turn-completed 发出时这条会话仍算「在飞」', async () => {
    // 放到在飞计数之外的话，abortSession 的会师点可以在这次 fire 还在飞时就落定，
    // 于是 auto-title 能在一个正在被删除/清空的会话上新起一个 run
    let activeAtFire: boolean | null = null
    mocks.fire.mockImplementation((id: string) => {
      if (id === 'session.turn-completed') activeAtFire = botService.isActive(SID)
    })
    await prompt()
    expect(activeAtFire).toBe(true)
    // 一轮跑完之后计数归零 —— 不然树会被永久钉在缓存里
    expect(botService.isActive(SID)).toBe(false)
  })
})

// ────────────────────────── GH：门控健康度与回落 ──────────────────────────

/**
 * 门控段连续故障之后回落内置 `bot-intent`。信道是脚本返回值的 `gate` 字段 —— 宿主看不见
 * 脚本内 `run()` 的错，而管线自己知道它这一轮是怎么收的。
 *
 * 这个计数器问的是「**内置门控契约**还灵不灵」，所以它对 `gate` 缺省的那些收场
 * （自定义管线、没起跑、脚本自己抛）既不递增也不清零 —— 否则一次网络抖动就能把用户的
 * 自定义管线打成回落态。
 */
describe('GH —— 门控回落', () => {
  /**
   * **每条用例一个新 bot 名**：健康度是 botService 这个模块级单例上的进程级状态
   * （回落刻意是 sticky 的 —— 它答的是「这个 bot 的门控还灵不灵」，不是「这一轮怎样」），
   * 没有复位入口也不该有。换个名字比给生产代码开一个测试后门干净。
   */
  let BOT = ''
  let seq = 0
  const gateOf = (i: number): unknown =>
    (mocks.invoke.mock.calls[i][0] as { input: { agents: Record<string, string> } }).input.agents
      .intent

  beforeEach(() => {
    seq += 1
    BOT = `gh-bot-${seq}`
    writeBot(BOT, { displayName: 'GH', agents: { intent: 'my-intent' } })
    seedSession([BOT])
  })

  it('GH-1 门控正常 → 不记故障，不回落', async () => {
    mocks.invoke.mockResolvedValue(ran({ gate: 'ok', outcome: 'reply' }))
    await prompt()
    expect(kindsOf(BOT)).not.toContain('gate_broken')
    expect(botService.gateDegradedOf(BOT)).toBeUndefined()
  })

  it('GH-2 一次破损 → 记 gate_broken（带连击数），但还不换人', async () => {
    mocks.invoke.mockResolvedValue(ran({ gate: 'broken', outcome: 'gate-broken' }))
    await prompt()
    const rec = decisions(BOT).find((d) => d.kind === 'gate_broken')!
    expect(rec).toBeDefined()
    expect((rec.detail as { streak?: number }).streak).toBe(1)
    expect(kindsOf(BOT)).not.toContain('gate_fallback')
    expect(gateOf(0)).toBe('my-intent')
  })

  it('GH-3 连续两次 → 记 gate_fallback，并**在会话里出声**', async () => {
    // 回落是看得见的行为改变：这个 bot 从此不再用用户指定的门控 agent 了。只落 journal
    // 加设置页徽标的话，用户看到的是「它忽然变得不一样了」而线索埋在文件系统里
    mocks.invoke.mockResolvedValue(ran({ gate: 'broken', outcome: 'gate-broken' }))
    await prompt('一')
    await prompt('二')

    expect(kindsOf(BOT)).toContain('gate_fallback')
    expect(botService.gateDegradedOf(BOT)).toBe('broken')
    // 提示刻意不在这一轮的关键路径上（.catch 而非 await）—— 所以这里等它落定
    await vi.waitFor(async () => {
      const msgs = await messageService.listBySession(SID)
      expect(msgs.some((m) => m.content === 'bot.gateFallback')).toBe(true)
    })
  })

  it('GH-4 回落之后角色表里的 intent 换成内置件（用户的 shuvix-bot-agents 让位）', async () => {
    mocks.invoke.mockResolvedValue(ran({ gate: 'broken', outcome: 'gate-broken' }))
    await prompt('一')
    await prompt('二')
    await prompt('三')

    expect(gateOf(0)).toBe('my-intent')
    expect(gateOf(2)).toBe('bot-intent')
  })

  it('GH-5 回落是 sticky 的：提示只出一次，之后每轮不再重复刷屏', async () => {
    mocks.invoke.mockResolvedValue(ran({ gate: 'broken', outcome: 'gate-broken' }))
    for (const text of ['一', '二', '三', '四']) await prompt(text)

    await vi.waitFor(async () => {
      const msgs = await messageService.listBySession(SID)
      expect(msgs.filter((m) => m.content === 'bot.gateFallback')).toHaveLength(1)
    })
    expect(decisions(BOT).filter((d) => d.kind === 'gate_fallback')).toHaveLength(1)
  })

  it('GH-6 中途成功一次 → 连击清零，两次故障重新数起', async () => {
    mocks.invoke.mockResolvedValueOnce(ran({ gate: 'broken', outcome: 'gate-broken' }))
    await prompt('一')
    mocks.invoke.mockResolvedValueOnce(ran({ gate: 'ok', outcome: 'reply' }))
    await prompt('二')
    mocks.invoke.mockResolvedValueOnce(ran({ gate: 'broken', outcome: 'gate-broken' }))
    await prompt('三')

    expect(kindsOf(BOT)).not.toContain('gate_fallback')
    expect(decisions(BOT).filter((d) => d.kind === 'gate_broken')).toHaveLength(2)
  })

  it('GH-7 回落之后再成功也不清零（回落是单向的，用户去设置里改回来）', async () => {
    mocks.invoke.mockResolvedValue(ran({ gate: 'broken', outcome: 'gate-broken' }))
    await prompt('一')
    await prompt('二')
    mocks.invoke.mockResolvedValue(ran({ gate: 'ok', outcome: 'reply' }))
    await prompt('三')

    expect(botService.gateDegradedOf(BOT)).toBe('broken')
  })

  it.each([
    ['自定义管线没报 gate', ran({ outcome: 'whatever' })],
    ['压根没起跑', { started: false, reason: 'error' }],
    ['起跑了但失败了且无 gate', { started: true, ok: false, error: 'boom' }],
    ['gate 是个不认识的值', ran({ gate: 'weird' })]
  ])('GH-8 gate 缺省或不认识（%s）→ 既不递增也不清零', async (_n, result) => {
    mocks.invoke.mockResolvedValue(result)
    await prompt('一')
    await prompt('二')
    await prompt('三')
    expect(kindsOf(BOT)).not.toContain('gate_broken')
    expect(kindsOf(BOT)).not.toContain('gate_fallback')
    expect(botService.gateDegradedOf(BOT)).toBeUndefined()
  })

  it('GH-9 超时与破损各记各的 kind（两者对用户的意味不同）', async () => {
    mocks.invoke.mockResolvedValue(ran({ gate: 'timeout', outcome: 'gate-timeout' }))
    await prompt('一')
    await prompt('二')
    expect(kindsOf(BOT)).toContain('gate_timeout')
    expect(kindsOf(BOT)).not.toContain('gate_broken')
    expect(botService.gateDegradedOf(BOT)).toBe('timeout')
  })

  it('GH-10 【回落提示落树失败不拖垮这一轮】它是 .catch 不是 await', async () => {
    // 裸的浮动 Promise 会在这里炸成一次 unhandled rejection（vitest 直接判红），
    // 而 await 它则会把一次「提示没写进去」升级成「这一轮的管线收尾失败」
    mocks.invoke.mockResolvedValue(ran({ gate: 'broken', outcome: 'gate-broken' }))
    await prompt('一')
    const spy = vi
      .spyOn(botService, 'appendBotMessage')
      .mockRejectedValueOnce(new Error('disk is full'))
    await expect(prompt('二')).resolves.toBeUndefined()
    expect(spy).toHaveBeenCalled()
    expect(kindsOf(BOT)).toContain('gate_fallback')
    // 这一轮照常收尾：埋点没少发
    expect(fired('session.turn-completed')).toHaveLength(2)
  })
})
