/**
 * bot→bot 接力的**宿主侧**接线（v2 的第二根轴 `shuvix-bot-respond-to` 落到运行时）。
 *
 * L0 门自己怎么判「谁参与」有它的纯函数单测（`bot/__tests__/botGate.test.ts`）；这一层
 * 问的是另外三件事，每一件失手都不会报错，只会在真实会话里表现成一句难查的抱怨：
 *
 *  - **短路**：没有任何别的成员声明 `all` 时，一条 bot 消息必须一步都不往下走 ——
 *    否则每条回复都白跑一遍全员 L0 + 目录全扫，症状只是「变慢了」；
 *  - **脱手**：接力由某个 bot 的 `say` 触发，`await` 它等于把接力做成同步递归 ——
 *    症状是最先说话的那个 bot 一直「在输入中」，直到整条链路跑完；
 *  - **两个计数的传递**：`rootId` 认的是「同一棵传播树」，`hop` 认的是深度。root 被换掉，
 *    每跳都重新起算 8 条，maxFanout 形同虚设；hop 传错，链路要么早断要么不收敛。
 *
 * mock 面照抄 botServiceTriggers：workflowService / sessionService / paths / logger /
 * i18n / 广播出口是假的，**消息表与决策日志是真的**（内存版 DAO + 临时目录里的 jsonl）——
 * 这一组的断言几乎全在「到底落了什么行、记了什么决策」上。
 *
 * 额外多一层假：`bot/botGate` 被包了一层**透传**的探针（真件照跑，只是把入参录下来），
 * 因为 `author` / `hop` / `fanout` 这三个接力事实除此之外没有观测口 —— 它们既不进消息行
 * 也不进 invoke 的 input。
 */
import { describe, it, expect, beforeEach, afterEach, afterAll, vi } from 'vitest'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs'
import { join } from 'path'

const dirs = vi.hoisted(() => {
  const tmp = (process.env.TMPDIR || process.env.TEMP || '/tmp').replace(/[\\/]+$/, '')
  const base = `${tmp}/shuvix-botrelay-${process.pid}`
  return { base, sessions: `${base}/sessions`, bots: `${base}/bots` }
})

const mocks = vi.hoisted(() => ({
  fire: vi.fn(),
  invoke: vi.fn(),
  hasWorkflow: vi.fn(() => true),
  abortSessionRuns: vi.fn(() => 0),
  getById: vi.fn(),
  noteUnread: vi.fn(),
  buildFacts: vi.fn(),
  isDefaultTitle: vi.fn(() => false),
  broadcast: vi.fn(),
  warn: vi.fn(),
  /** L0 探针：录下每次门控的入参（真件照跑） */
  l0: vi.fn(),
  /** 全局设置读取（两道护栏）—— 缺省返回 undefined = 用缺省值 */
  setting: vi.fn((_key: string) => undefined as string | undefined)
}))

vi.mock('../workflowService', () => ({
  workflowService: {
    invoke: mocks.invoke,
    abortSessionRuns: mocks.abortSessionRuns,
    hasWorkflow: mocks.hasWorkflow,
    registerRunJournalSink: vi.fn()
  },
  workflowTriggers: { fire: mocks.fire }
}))
vi.mock('electron', () => ({ shell: { openPath: vi.fn(async () => '') } }))
// v2：聊天会话转写在 chat_messages 表里。真 DAO 一经导入就会打开 sqlite
// （DatabaseManager 构造即开库，而原生绑定是 Electron ABI 的），故整个替换成内存版
vi.mock('../../dao/chatMessageDao', async () => await import('./fakeChatMessageDao'))
vi.mock('../../utils/paths', () => ({
  getDataDir: () => join(dirs.base, 'data'),
  // 真件是 ensureDir(...)：建目录后才返回。替身不建目录的话 saveChatAttachments
  // 会逐张写失败（它只丢那一张，不抛），RL-14 的对照组就空了
  getChatAttachmentsDir: (sid: string) => {
    const dir = join(dirs.base, 'data', 'chat-attachments', sid)
    mkdirSync(dir, { recursive: true })
    return dir
  },
  getSessionsDir: () => dirs.sessions,
  getDefaultBotsDir: () => dirs.bots,
  getDefaultAgentsDir: () => `${dirs.base}/agents`
}))
vi.mock('../../logger', () => ({
  createLogger: () => ({ info: () => {}, warn: mocks.warn, error: () => {} })
}))
// 会话可见文案走 i18n。这里保留插值参数（`bot.fanoutCapped` 带 count），断言用
// 「key + 参数」而不是某一种语言的整句
vi.mock('../../i18n', () => ({
  t: (key: string, params?: Record<string, unknown>) =>
    params ? `${key}|${JSON.stringify(params)}` : key
}))
vi.mock('../agentRuntimeAdapters', () => ({ electronEventSink: { broadcast: mocks.broadcast } }))
vi.mock('../sessionTriggerFacts', () => ({
  buildTurnCompletedFacts: mocks.buildFacts,
  isDefaultTitle: mocks.isDefaultTitle
}))
vi.mock('../sessionService', () => ({
  sessionService: { getById: mocks.getById, noteUnreadBotReply: mocks.noteUnread }
}))
// botService 经 settingsService 读两道循环护栏。真件一经导入就把 settingsDao →
// dao/database 拉进模块图，而 DatabaseManager 构造即开 sqlite（原生绑定是 Electron ABI 的）
vi.mock('../settingsService', () => ({ settingsService: { get: mocks.setting } }))
// 透传探针：`author` / `hop` / `fanout` 是接力路径的核心事实，而它们既不落行也不进
// invoke 的 input —— 除了在门口录一份，没有别的观测口
vi.mock('../bot/botGate', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../bot/botGate')>()
  return {
    ...actual,
    runL0Gate: (inp: Parameters<typeof actual.runL0Gate>[0]) => {
      mocks.l0(inp)
      return actual.runL0Gate(inp)
    }
  }
})

import { botService } from '../botService'
import { chatMessageDao, __reset as resetRows, __rows } from './fakeChatMessageDao'
import type { ChatMessageRow } from '../../dao/types/chatMessage'
import type { L0Input } from '../bot/botGate'

/** 每条用例一条新会话：botService 是模块级单例，按会话 id 记着在飞计数与禁写位 */
let SID = 'relay-sess'
let sidSeq = 0

const FACTS = {
  title: 'Some title',
  isDefaultTitle: false,
  titleAutoGenerated: false,
  turnCount: 1,
  textMessageCount: 2,
  recentText: 'User: hi'
}

function writeBot(
  name: string,
  opts: { displayName?: string; respond?: string; respondTo?: string } = {}
): void {
  mkdirSync(dirs.bots, { recursive: true })
  const lines = ['---', 'shuvix: bot v1', `name: ${name}`, `description: relay bot ${name}`]
  if (opts.displayName) lines.push(`shuvix-displayName: ${opts.displayName}`)
  if (opts.respond) lines.push(`shuvix-bot-respond: ${opts.respond}`)
  if (opts.respondTo) lines.push(`shuvix-bot-respond-to: ${opts.respondTo}`)
  lines.push('---', '', 'BOT BODY.')
  writeFileSync(join(dirs.bots, `${name}.md`), lines.join('\n'))
}

const seedSession = (bots: string[]): void => {
  mocks.getById.mockReturnValue({
    workingDirectory: dirs.sessions,
    title: 'Some title',
    settings: { bots }
  })
}

/** 一次管线 invoke 的结果 —— 缺省「跑完了，门控正常」 */
const ran = (
  output: Record<string, unknown> = { gate: 'ok', outcome: 'reply' }
): { started: boolean; ok: boolean; output: Record<string, unknown> } => ({
  started: true,
  ok: true,
  output
})

type InvokeReq = {
  input: { bot: { name: string }; message: { text: string; attachments?: unknown[] } }
  extraApi: { say: (text: string) => Promise<{ messageId: string | null }> }
}

/**
 * 让每次派发都由被派发的那个 bot 说一句话 —— 内置管线脚本 `say` 的最小替身。
 * 返回 null 表示这一轮不说话（用来把某个成员从链路上摘掉）。
 */
function speakOnInvoke(textOf: (botName: string) => string | null = (n) => `${n} 说话了`): void {
  mocks.invoke.mockImplementation(async (req: unknown) => {
    const r = req as InvokeReq
    const text = textOf(r.input.bot.name)
    if (text) await r.extraApi.say(text)
    return ran()
  })
}

/** 一次说话都不说（只看派发有没有发生时用） */
const silentInvoke = (): void => {
  mocks.invoke.mockImplementation(async () => ran())
}

/** 让脱手的接力跑完（它不在任何 await 链上，只能等） */
const settle = async (ms = 40): Promise<void> => {
  await new Promise((r) => setTimeout(r, ms))
}

const rowsOf = (sid = SID): ChatMessageRow[] =>
  __rows()
    .filter((r) => r.sessionId === sid)
    .sort((a, b) => a.seq - b.seq)

const botRows = (sid = SID): ChatMessageRow[] => rowsOf(sid).filter((r) => r.authorKind === 'bot')

/** L0 探针录到的第 n 次门控入参 */
const l0Call = (n: number): L0Input => mocks.l0.mock.calls[n][0] as L0Input

/** invoke 的第 n 次入参 */
const invokeInput = (n: number): InvokeReq['input'] =>
  (mocks.invoke.mock.calls[n][0] as InvokeReq).input

const broadcastsOf = (type: string): Array<Record<string, unknown>> =>
  mocks.broadcast.mock.calls
    .map((c) => c[0] as Record<string, unknown>)
    .filter((e) => e.type === type)

/** 某个 bot 的决策记录 kind 列表 */
function kindsOf(botName: string): string[] {
  const file = join(dirs.bots, '.runs', botName, 'decisions.jsonl')
  if (!existsSync(file)) return []
  return readFileSync(file, 'utf-8')
    .trim()
    .split('\n')
    .filter(Boolean)
    .map((l) => String((JSON.parse(l) as { kind: unknown }).kind))
}

/** 一条 bot 消息落树（接力的唯一触发口） */
/**
 * 一条 bot 消息落库。
 *
 * **缺省带 origin**：接力只由「回应某条消息」的落点触发（`say` / 各条可见失败都带），
 * 开场白那条路径不带 —— 想测它就显式传 `null`（见 RL-10）。缺省若不带，本文件绝大多数
 * 用例测的其实是「开场白也接力」那条已被砍掉的路径
 */
const say = (
  botName: string,
  content: string,
  origin: { rootId?: string; hop?: number } | null = { hop: 0 }
): Promise<string | null> =>
  botService.appendBotMessage(
    SID,
    { botName, displayName: botName },
    { content },
    origin ?? undefined
  )

beforeEach(() => {
  sidSeq += 1
  SID = `relay-sess-${sidSeq}`
  rmSync(dirs.base, { recursive: true, force: true })
  mkdirSync(dirs.sessions, { recursive: true })
  mkdirSync(dirs.bots, { recursive: true })
  resetRows()
  for (const m of Object.values(mocks)) m.mockReset()
  mocks.hasWorkflow.mockReturnValue(true)
  mocks.abortSessionRuns.mockReturnValue(0)
  mocks.isDefaultTitle.mockReturnValue(false)
  mocks.buildFacts.mockResolvedValue(FACTS)
  mocks.setting.mockReturnValue(undefined)
  silentInvoke()
})

afterEach(() => {
  vi.restoreAllMocks()
})

afterAll(() => {
  rmSync(dirs.base, { recursive: true, force: true })
})

// ────────────────────────── RL-short：短路 ──────────────────────────

/**
 * 缺省（全体 `respond-to: user`）下这条路径必须**一步都不走**：与 v1「bot 的回复不触发
 * bot」在行为与开销上都等价。短路失效不会报错 —— 它只是让每条 bot 回复都白跑一遍
 * 全员 L0 + 一次 bots 目录全扫，用户能察觉的只有「变慢了」。
 */
describe('RL-short —— 接力短路', () => {
  it("RL-1 全体成员 'user' → 不派发、不落新行、一条决策记录都不记", async () => {
    writeBot('a')
    writeBot('b')
    seedSession(['a', 'b'])

    const id = await say('a', 'a 的回复')
    await settle()

    expect(id).toBeTruthy()
    expect(mocks.invoke).not.toHaveBeenCalled()
    // 除了那条 bot 消息本身，表里什么都没多
    expect(rowsOf()).toHaveLength(1)
    // L0 根本没被调起 —— 短路发生在 relayToBots 里，而不是靠 L0 把人筛光
    expect(mocks.l0).not.toHaveBeenCalled()
    expect(kindsOf('a')).toEqual([])
    expect(kindsOf('b')).toEqual([])
  })

  it("RL-2 名单只有一个成员 → 短路（members.length < 2），即便它声明了 'all'", async () => {
    writeBot('a', { respondTo: 'all' })
    seedSession(['a'])
    await say('a', 'a 自言自语')
    await settle()
    expect(mocks.invoke).not.toHaveBeenCalled()

    // 长度闸自己的贡献要另造一种形状才看得见：发言人**不在**名单里（成员被 updateBots
    // 摘掉之后它的在飞回复仍会落树），此时 anyRelay 是成立的，拦下它的只有 members.length < 2
    seedSession(['b'])
    writeBot('b', { respondTo: 'all' })
    await say('a', 'ghost 的回复')
    await settle()
    expect(mocks.invoke).not.toHaveBeenCalled()
  })

  it("RL-3 名单里唯一声明 'all' 的就是发言人自己 → 短路，不进派发", async () => {
    // `anyRelay` 里的 `m !== row.botName` 那一项。少了它就是一次完全隐形的空转 ——
    // 配合 A-4（bot 作者路径上的沉默不落记录）连一行日志都不会有
    writeBot('a', { respondTo: 'all' })
    writeBot('b')
    seedSession(['a', 'b'])

    await say('a', 'a 的回复')
    await settle()
    expect(mocks.invoke).not.toHaveBeenCalled()
    expect(mocks.l0).not.toHaveBeenCalled()
  })

  it("RL-4 至少一个**别的**成员声明 'all' → 真的派发，且作者是那个发言的 bot", async () => {
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])

    const id = await say('a', 'a 的回复')
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalled())

    expect(l0Call(0).author).toEqual({ kind: 'bot', name: 'a' })
    // 发言人自己不在 cohort 里，被派发的是 b
    expect(invokeInput(0).bot.name).toBe('b')
    expect(l0Call(0).members).toEqual(['a', 'b'])
    expect(id).toBeTruthy()
  })

  it('RL-5 空白正文 → 返回 null 且不触发接力（没落成消息的东西不该有下文）', async () => {
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])

    expect(await say('a', '   \n  ')).toBeNull()
    await settle()
    expect(rowsOf()).toHaveLength(0)
    expect(mocks.invoke).not.toHaveBeenCalled()
  })

  it('RL-6 会话关停中（blockWrites）→ 返回 null 且不触发接力', async () => {
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])

    // abortSession 同步置上禁写位，随后才 await —— 这一句之后、微任务排空之前，门是关着的
    const abort = botService.abortSession(SID)
    const blocked = say('a', '这条不该落树')
    expect(await blocked).toBeNull()
    await abort
    await settle()

    expect(rowsOf()).toHaveLength(0)
    expect(mocks.invoke).not.toHaveBeenCalled()
  })
})

// ────────────────────────── RL-async：脱手 ──────────────────────────

/**
 * 调用 `appendBotMessage` 的正是某个 bot 的 `say`。等接力跑完再返回，等于把 bot→bot
 * 做成同步递归：最先说话的那个一直卡在「正在输入」，而它其实早就说完了。
 */
describe('RL-async —— 接力是脱手的', () => {
  it('RL-7 派发挂起不结时，appendBotMessage 仍立即返回消息 id', async () => {
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])

    let release: () => void = () => {}
    mocks.invoke.mockImplementation(
      () =>
        new Promise((resolve) => {
          release = () => resolve(ran())
        })
    )

    const id = await say('a', 'a 的回复')
    expect(id).toBeTruthy()
    // 消息已经落库了，而下一跳还挂在那里
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalled())
    expect(botRows()).toHaveLength(1)

    release()
    await settle()
  })

  it('RL-8 接力内部抛异常 → appendBotMessage 不 reject，消息照落照播，只记一条 warn', async () => {
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])
    // 轮结束埋点的事实构造器炸掉 —— 它在 dispatchCohort 里被 await，异常会一路冒到
    // relayToBots 的 catch（成员级的 catch 包不住它）
    mocks.buildFacts.mockRejectedValue(new Error('boom'))

    const id = await say('a', 'a 的回复')
    expect(id).toBeTruthy()
    await vi.waitFor(() =>
      expect(mocks.warn.mock.calls.some((c) => String(c[0]).includes('接力失败'))).toBe(true)
    )
    // 发言的那一方不受反噬：行还在，广播也发了
    expect(botRows()).toHaveLength(1)
    expect(broadcastsOf('assistant_message')).toHaveLength(1)
    // 这条用例同时也是「不产生 unhandled rejection」的守卫 —— 有的话 vitest 直接判红
  })

  it('RL-8b 短路判断本身抛（读名单炸了）→ 同样被 catch 住，不是 unhandled rejection', async () => {
    // catch 的边界画在哪里是有讲究的：调用点是 `void this.relayToBots(...)`，逃出去的
    // 异常直接成为主进程级的未捕获拒绝。RL-8 走的是 dispatchCohort 那条深路径，而读名单
    // 与扫 bot 目录发生在它之前 —— 那两句落在 try 外面的话，本例是唯一会响的地方
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])
    const good = mocks.getById.getMockImplementation()
    let calls = 0
    mocks.getById.mockImplementation((...args: unknown[]) => {
      // 第一次是 appendBotMessage 自己读的（不能炸，否则消息根本落不下去），
      // 第二次才是接力读名单
      if (++calls === 2) throw new Error('settings read blew up')
      return good ? good(...args) : { settings: { bots: ['a', 'b'] } }
    })

    const id = await say('a', 'a 的回复')
    expect(id).toBeTruthy()
    await vi.waitFor(() =>
      expect(mocks.warn.mock.calls.some((c) => String(c[0]).includes('接力失败'))).toBe(true)
    )
    expect(botRows()).toHaveLength(1)
  })

  it('RL-9 接力发生在未读记账与 assistant_message 广播**之后**', async () => {
    // 顺序颠倒会让下一个 bot 的「正在输入」出现在它要回应的那条消息之前
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])

    const order: string[] = []
    mocks.broadcast.mockImplementation((e: unknown) => {
      const type = (e as { type: string }).type
      if (type === 'assistant_message') order.push('broadcast')
    })
    mocks.noteUnread.mockImplementation(() => order.push('unread'))
    mocks.l0.mockImplementation(() => order.push('relay'))

    await say('a', 'a 的回复')
    await vi.waitFor(() => expect(order).toContain('relay'))
    expect(order).toEqual(['broadcast', 'unread', 'relay'])
  })
})

// ────────────────────── RL-prop：rootId / hop 的传递 ──────────────────────

/**
 * `rootId` 认的是「同一棵传播树」，`hop` 认的是深度。两个计数都由**触发这一跳的那条行**
 * 交出去 —— root 被换掉，每跳都重新起算 8 条，maxFanout 形同虚设；hop 传错，链路要么
 * 早断要么根本不收敛。
 */
describe('RL-prop —— rootId / hop 的传递', () => {
  it('RL-10 无 origin（开场白）→ 落行 hop 0、rootId 空，且**一步都不接力**', async () => {
    // 开场白不回应任何人。少了这道判断，只要成员里有一个 respond-to: all，建会话那一刻
    // 就会自动开跑一轮 bot 对话 —— 用户一个字都还没说，会话里已经有人在聊了
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])
    speakOnInvoke()

    await say('a', 'a 的开场白', null)
    await settle()

    expect(botRows()).toHaveLength(1)
    expect(mocks.invoke).not.toHaveBeenCalled()
    const [first] = botRows()
    expect(first.hop).toBe(0)
    expect(first.rootId).toBeUndefined()
  })

  it('RL-10b 回应型落点（带 origin）无 rootId 时，下一跳的根取它自己的 id', async () => {
    // origin 只带 hop 而没有 rootId 是可达的（一条不挂在任何用户消息下的回应）——
    // 此时这条消息自己就是这棵传播树的根，否则扇出计数没有归组的口
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])
    speakOnInvoke()

    const id = await say('a', 'a 的回复')
    await vi.waitFor(() => expect(botRows()).toHaveLength(2))

    const [first, second] = botRows()
    // origin.hop=0（回的是一条用户消息）→ 这条是 hop 1，它引出的下一跳是 hop 2
    expect(first.hop).toBe(1)
    expect(second.rootId).toBe(id)
    expect(second.hop).toBe(2)
  })

  it.each([
    [0, 1],
    [1, 2],
    [5, 6]
  ])('RL-11 origin.hop=%s → 落行 hop=%s（由 h 触发的回复是 h+1）', async (given, expected) => {
    writeBot('a')
    seedSession(['a'])
    await say('a', '回复', { rootId: 'R', hop: given })
    expect(botRows()[0].hop).toBe(expected)
  })

  it('RL-12 用户 → A → B 三级链路共用同一个 rootId，hop 逐级 +1', async () => {
    // b 是 mention-only + all：用户那一轮它不参与（没被点名），a 在正文里点它的名才接上 ——
    // 这样一条用户消息的传播树是干净的一条链，rootId 的「共用」才断言得清楚
    writeBot('a')
    writeBot('b', { respond: 'mention-only', respondTo: 'all' })
    seedSession(['a', 'b'])
    speakOnInvoke((name) => (name === 'a' ? '这个 @b 更清楚' : 'b 的回答'))

    await botService.handleUserMessage({ sessionId: SID, text: '大家好' } as never)
    await vi.waitFor(() => expect(botRows()).toHaveLength(2))

    const [user] = rowsOf()
    const [fromA, fromB] = botRows()
    expect(user.rootId).toBe(user.id)
    expect(user.hop).toBe(0)
    expect(fromA).toMatchObject({ botName: 'a', rootId: user.id, hop: 1 })
    expect(fromB).toMatchObject({ botName: 'b', rootId: user.id, hop: 2 })

    // 接力那一次门控拿到的就是 A 这条行的深度
    const relay = l0Call(1)
    expect(relay.author).toEqual({ kind: 'bot', name: 'a' })
    expect(relay.hop).toBe(1)
    // 整棵树共用一个 root —— 扇出计数因此是全树口径而不是每跳重来
    expect(relay.fanout).toBe(chatMessageDao.countBotMessagesByRoot(SID, user.id) - 1)
  })

  it('RL-13 text 与 promptText 都取 row.content，且不带 inlineTokens', async () => {
    // 于是一个 bot 在正文里写 `@b` 会真的定向唤起 b（接力路径没有胶囊可用，
    // 只有裸文本降级这一条路）
    writeBot('a')
    writeBot('b', { respond: 'mention-only', respondTo: 'all' })
    writeBot('c', { respondTo: 'all' })
    seedSession(['a', 'b', 'c'])
    silentInvoke()

    await say('a', '这个问题 @b 更清楚')
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalled())

    expect(l0Call(0).text).toBe('这个问题 @b 更清楚')
    expect(l0Call(0).inlineTokens).toBeUndefined()
    expect(invokeInput(0).message.text).toBe('这个问题 @b 更清楚')
    // 裸文本命中：只有被点名的 b 被唤起，虽然 c 也声明了 all
    expect(mocks.invoke.mock.calls.map((c) => (c[0] as InvokeReq).input.bot.name)).toEqual(['b'])
  })

  it('RL-14 接力不透传 attachments（钉住现状）', async () => {
    // b 取 mention-only：用户那一轮只有 a 被唤起，链路才是「用户 → a → b」一条线，
    // 两次 invoke 一一对得上（否则 b 在用户那一轮也被派发，第一次 invoke 是谁的就不确定了）
    writeBot('a')
    writeBot('b', { respond: 'mention-only', respondTo: 'all' })
    seedSession(['a', 'b'])
    speakOnInvoke((name) => (name === 'a' ? '@b 你看这张图' : null))

    await botService.handleUserMessage({
      sessionId: SID,
      text: '看看这张图',
      images: [{ data: Buffer.from('BYTES').toString('base64'), mimeType: 'image/png' }]
    } as never)
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalledTimes(2))

    // 对照组：用户那一跳带着描述符
    expect(invokeInput(0).message.attachments).toHaveLength(1)
    // 接力那一跳一个都不带 —— bot 消息本来就没有附件列，宿主也不去回捞上游那条
    expect(invokeInput(1).message).not.toHaveProperty('attachments')
  })
})

// ─────────────────── RL-fanout：扇出计数与可见结局 ───────────────────

/**
 * 横向触顶是**会话里看得见**的（一条 system 行），纵向触顶不是 —— 刻意的不对称：
 * 扇出被拦下时链路是凭空断掉的，用户看不出发生过什么；深度触顶则是链路自然收敛，
 * 每多说一句都是噪音。
 */
describe('RL-fanout —— 扇出触顶', () => {
  /** 往同一棵树里塞 n 条 bot 行（扇出计数的口径就是这个） */
  const seedTree = (rootId: string, n: number): void => {
    for (let i = 0; i < n; i++) {
      chatMessageDao.append({
        sessionId: SID,
        authorKind: 'bot',
        botName: 'seed',
        displayName: 'seed',
        content: `第 ${i} 条`,
        rootId,
        hop: 1
      })
    }
  }

  beforeEach(() => {
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])
  })

  it('RL-15 触顶时落一条 system 行：文案带 count、root/hop 继承，随后广播 messages_reloaded', async () => {
    seedTree('R', 8)
    await say('a', '第九条', { rootId: 'R', hop: 0 })
    await vi.waitFor(() => expect(rowsOf().some((r) => r.authorKind === 'system')).toBe(true))

    const sys = rowsOf().find((r) => r.authorKind === 'system')!
    expect(sys.content).toContain('bot.fanoutCapped')
    expect(sys.content).toContain('"count":8')
    expect(sys.rootId).toBe('R')
    // ctx.hop 就是触发这一跳的那条行的 hop（origin.hop=0 → 落行 hop=1）
    expect(sys.hop).toBe(1)
    expect(broadcastsOf('messages_reloaded')).toHaveLength(1)
    expect(kindsOf('a')).toContain('l0_fanout_exceeded')
  })

  it('RL-16 system 行不走 appendBotMessage：不再接力、不 bump 未读、不广播 assistant_message', async () => {
    // 系统行若走 bot 路径，它自己会再派发一轮 —— 一条「本轮到此为止」的通告反而
    // 成了下一轮的触发源
    seedTree('R', 8)
    await say('a', '第九条', { rootId: 'R', hop: 0 })
    await vi.waitFor(() => expect(rowsOf().some((r) => r.authorKind === 'system')).toBe(true))
    await settle()

    expect(mocks.invoke).not.toHaveBeenCalled()
    expect(mocks.noteUnread).toHaveBeenCalledTimes(1)
    expect(broadcastsOf('assistant_message')).toHaveLength(1)
  })

  it("RL-17 system 行不计入扇出（authorKind 是 'system' 不是 'bot'）", async () => {
    seedTree('R', 8)
    await say('a', '第九条', { rootId: 'R', hop: 0 })
    await vi.waitFor(() => expect(rowsOf().some((r) => r.authorKind === 'system')).toBe(true))

    expect(rowsOf()).toHaveLength(10) // 8 条种子 + a 的那条 + 一条 system
    expect(chatMessageDao.countBotMessagesByRoot(SID, 'R')).toBe(9)
  })

  it('RL-18 深度触顶时不落任何 system 行（与 RL-15 刻意不对称）', async () => {
    seedTree('R', 1)
    // origin.hop=1 → 落行 hop=2 = maxHop，接力那一跳直接被纵向护栏拦下
    await say('a', '第三跳', { rootId: 'R', hop: 1 })
    await vi.waitFor(() => expect(kindsOf('a')).toContain('l0_hop_exceeded'))
    await settle()

    expect(rowsOf().some((r) => r.authorKind === 'system')).toBe(false)
    expect(broadcastsOf('messages_reloaded')).toHaveLength(0)
    expect(mocks.invoke).not.toHaveBeenCalled()
  })

  it('RL-19 触顶那一轮仍然 fire session.turn-completed（同 TR-9 的契约）', async () => {
    // cohort 为空也是「一轮」。两边在「什么时候算一轮」上错开，订阅方看到的就是
    // 「某类会话的工作流莫名其妙不触发」
    seedTree('R', 8)
    await say('a', '第九条', { rootId: 'R', hop: 0 })
    await vi.waitFor(() =>
      expect(mocks.fire.mock.calls.filter((c) => c[0] === 'session.turn-completed')).toHaveLength(1)
    )
  })

  it('RL-20 check-then-act 的已知上界：同一层最多可越过上限 N-1 条', async () => {
    // 扇出在**派发之前只读一次**，之后这一层的 N 个成员各说各的 —— 于是上限可以被
    // 越过最多 N-1 条。写成用例是为了让它成为一个被知道的上界，而不是某天被当成 bug
    // 报上来的意外；若将来改成每条 append 之前复查，本例反转
    writeBot('c', { respondTo: 'all' })
    writeBot('d', { respondTo: 'all' })
    seedSession(['a', 'b', 'c', 'd'])
    speakOnInvoke()

    seedTree('R', 6)
    await say('a', '第七条', { rootId: 'R', hop: 0 })
    await vi.waitFor(() => expect(mocks.invoke).toHaveBeenCalledTimes(3))
    await settle()

    // 那一次门控读到的是 7（还没到 8），于是 b/c/d 三个全部放行
    expect(l0Call(0).fanout).toBe(7)
    expect(l0Call(0).limits.maxFanout).toBe(8)
    // 结果是 10 条 —— 越过上限 2 条 = cohort 大小 3 减一
    expect(chatMessageDao.countBotMessagesByRoot(SID, 'R')).toBe(10)
    expect(rowsOf().some((r) => r.authorKind === 'system')).toBe(false)
  })
})

// ────────── RL-cfg：两道护栏来自全局设置（设计 §4.2「都放全局设置可调」）──────────

/**
 * 护栏是**会话级的安全阀**，所以既不写死在代码里、也不放进 bot md（让被护的人自己声明
 * 能触发多深，等于把护栏交给它）。这一组钉的是「设置真的被读到了」以及写坏时的回落 ——
 * 设置项是纯文本键值，UI 之外还有 `session-config` 工具这条写入口。
 */
describe('RL-cfg —— 护栏取自全局设置', () => {
  /** 让 settingsService.get 按 key 返回指定字符串 */
  const setLimits = (hop?: string, fanout?: string): void => {
    mocks.setting.mockImplementation((key: string) =>
      key === 'bot.maxHop' ? hop : key === 'bot.maxFanout' ? fanout : undefined
    )
  }

  it('RL-21 未设置 → 缺省 2 / 8', async () => {
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])

    await say('a', 'a 的回复', { rootId: 'R', hop: 0 })
    await vi.waitFor(() => expect(mocks.l0).toHaveBeenCalled())
    expect(l0Call(0).limits).toEqual({ maxHop: 2, maxFanout: 8 })
  })

  it('RL-22 maxHop=1 → 等价于关掉 bot→bot：一跳消息就已触顶', async () => {
    // 文档里对 1 的承诺（「等价于关掉」）在这里才成立或不成立
    setLimits('1', '8')
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])

    await say('a', 'a 的回复', { rootId: 'R', hop: 0 })
    await settle()

    expect(mocks.invoke).not.toHaveBeenCalled()
    expect(kindsOf('a')).toContain('l0_hop_exceeded')
  })

  it('RL-23 maxFanout 调小 → 触顶的 system 行报的是**设置里那个数**，不是缺省 8', async () => {
    // 文案与判定用同一个数：报 8 而按 2 拦，用户会以为自己看错了
    setLimits('2', '2')
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])
    chatMessageDao.append({
      sessionId: SID,
      authorKind: 'bot',
      botName: 'x',
      content: '1',
      hop: 1,
      rootId: 'R'
    })
    chatMessageDao.append({
      sessionId: SID,
      authorKind: 'bot',
      botName: 'x',
      content: '2',
      hop: 1,
      rootId: 'R'
    })

    await say('a', 'a 的回复', { rootId: 'R', hop: 0 })
    await settle()

    const sys = rowsOf().find((r) => r.authorKind === 'system')
    expect(sys?.content).toContain('bot.fanoutCapped')
    expect(sys?.content).toContain('"count":2')
  })

  it.each([
    ['非数', 'many'],
    ['小数', '2.5'],
    ['负数', '-1'],
    ['空串', '']
  ])('RL-24 设置写坏（%s）→ 回落缺省，而不是把护栏关掉', async (_n, bad) => {
    setLimits(bad, bad)
    writeBot('a')
    writeBot('b', { respondTo: 'all' })
    seedSession(['a', 'b'])

    await say('a', 'a 的回复', { rootId: 'R', hop: 0 })
    await vi.waitFor(() => expect(mocks.l0).toHaveBeenCalled())
    expect(l0Call(0).limits).toEqual({ maxHop: 2, maxFanout: 8 })
  })
})
