/**
 * sessionService.updateTitle —— titleOrigin 簿记与 titleChanged 广播的口径。
 *
 * `settings.titleOrigin` 是 `session.turn-completed` 埋点里 titleAutoGenerated 的
 * 唯一数据来源：origin 恒写入（'user'/'auto' 都要落），auto-title 的 refine 阶段据此
 * 避免覆盖用户手动改过的标题。广播只在 origin='auto' 时发 —— 用户改名时渲染端自行更新，
 * 自动写入才需要推给各端会话列表。
 *
 * sessionService 的 import 图很重（dao/agentSession/frontend/...），全部换假件、
 * 只留 chat-protocol / agent-runtime 真件 —— 本文件只钉 updateTitle 这一个纯写入口。
 */
import { describe, it, expect, beforeAll, beforeEach, vi } from 'vitest'

const mocks = vi.hoisted(() => ({
  daoUpdateTitle: vi.fn(),
  daoUpdateSettings: vi.fn(),
  broadcastTitleChanged: vi.fn()
}))

vi.mock('../../dao/sessionDao', () => ({
  sessionDao: { updateTitle: mocks.daoUpdateTitle, updateSettings: mocks.daoUpdateSettings }
}))
vi.mock('../../dao/httpLogDao', () => ({ httpLogDao: {} }))
vi.mock('../../dao/providerDao', () => ({ providerDao: {} }))
vi.mock('../../dao/projectDao', () => ({ projectDao: {} }))
vi.mock('../../dao/settingsDao', () => ({ settingsDao: {} }))
vi.mock('../messageService', () => ({ messageService: {} }))
vi.mock('../sessionStorage', () => ({
  readSessionRunConfig: vi.fn(),
  addSessionTreePin: vi.fn(),
  appendModelChange: vi.fn(),
  appendActiveToolsChange: vi.fn()
}))
vi.mock('../../i18n', () => ({ t: (key: string) => key }))
vi.mock('../../utils/paths', () => ({ getTempWorkspace: vi.fn(), getToolResultsBase: vi.fn() }))
vi.mock('../toolAggregator', () => ({
  getDefaultEnabledTools: vi.fn(() => []),
  filterAvailableTools: vi.fn((tools: string[]) => tools)
}))
vi.mock('../../utils/toolUtils/allowList', () => ({ buildAllowEntry: vi.fn() }))
vi.mock('../botService', () => ({
  botService: {
    abortSession: vi.fn(async () => {}),
    seedGreetings: vi.fn(async () => {}),
    isActive: vi.fn(() => false)
  }
}))
vi.mock('../agentService', () => ({ agentService: { getProfile: vi.fn() } }))
vi.mock('../agentSession', () => ({ AgentSession: class {} }))
vi.mock('../bgTaskService', () => ({ killBySession: vi.fn(), setBgTaskNotifier: vi.fn() }))
vi.mock('../../agents/agentHost', () => ({
  resolveProfileModelSpec: vi.fn()
}))
vi.mock('../../utils/sessionConfigBroadcast', () => ({
  broadcastSessionConfigChanged: vi.fn(),
  broadcastSessionListChanged: vi.fn(),
  broadcastSessionTitleChanged: mocks.broadcastTitleChanged
}))
vi.mock('../../frontend/core/ChatFrontendRegistry', () => ({
  chatFrontendRegistry: { broadcast: vi.fn() }
}))
vi.mock('../userInputBroker', () => ({ registerUserInputParticipant: vi.fn() }))
vi.mock('../../logger', () => ({
  createLogger: () => ({ info: () => {}, warn: () => {}, error: () => {} })
}))

let sessionService: (typeof import('../sessionService'))['sessionService']

beforeAll(async () => {
  ;({ sessionService } = await import('../sessionService'))
})
beforeEach(() => {
  mocks.daoUpdateTitle.mockReset()
  mocks.daoUpdateSettings.mockReset()
  mocks.broadcastTitleChanged.mockReset()
})

describe('sessionService.updateTitle — titleOrigin 簿记与广播口径', () => {
  it("缺省 origin='user'：省略第三参等价用户改名（titleOrigin 落 'user'）", () => {
    sessionService.updateTitle('s1', 'Renamed')
    expect(mocks.daoUpdateTitle).toHaveBeenCalledWith('s1', 'Renamed')
    expect(mocks.daoUpdateSettings).toHaveBeenCalledWith('s1', { titleOrigin: 'user' })
  })

  it("origin 恒写入 settings.titleOrigin（'user'/'auto' 各一）—— 埋点 titleAutoGenerated 的数据源", () => {
    sessionService.updateTitle('s1', 'A', 'user')
    expect(mocks.daoUpdateSettings).toHaveBeenNthCalledWith(1, 's1', { titleOrigin: 'user' })
    sessionService.updateTitle('s1', 'B', 'auto')
    expect(mocks.daoUpdateSettings).toHaveBeenNthCalledWith(2, 's1', { titleOrigin: 'auto' })
    expect(mocks.daoUpdateTitle).toHaveBeenCalledTimes(2)
  })

  it("origin='auto' → broadcastSessionTitleChanged(id, title) 恰一次（自动写入推给各端列表）", () => {
    sessionService.updateTitle('s1', 'Auto title', 'auto')
    expect(mocks.broadcastTitleChanged).toHaveBeenCalledTimes(1)
    expect(mocks.broadcastTitleChanged).toHaveBeenCalledWith('s1', 'Auto title')
  })

  it("origin='user' → 不广播（用户改名的渲染端自行更新，维持旧行为）", () => {
    sessionService.updateTitle('s1', 'Manual title', 'user')
    expect(mocks.broadcastTitleChanged).not.toHaveBeenCalled()
  })
})
