/**
 * 会话域埋点的**事实构造器** —— `session.turn-completed` 的 payload 从哪来。
 *
 * 为什么它值得一份自己的单测：这份 payload 是一条**契约**，两个 emit 侧共用
 * （有根会话由 AgentSession 触发，聊天会话由 botService 触发），而订阅方的 CEL `when`
 * 是照着这份形状写的 —— 内置的 auto-title 就靠 `turnCount == 2 && textMessageCount >= 3`
 * 决定要不要精修标题。数字算错一格，表现出来是「某类会话的工作流莫名其妙不触发」，
 * 而那种故障没有报错、没有日志，只有一个永远不改的标题。
 *
 * 这里只答「会话此刻是什么样」。谁订阅、订阅去做什么，都不是埋点该知道的事 —— 所以
 * 这份用例里一个工作流的名字都不该出现。
 */
import { describe, it, expect, beforeEach, vi } from 'vitest'

const mocks = vi.hoisted(() => ({
  pick: vi.fn(),
  listBySession: vi.fn(),
  t: vi.fn((key: string) => (key === 'agent.defaultTitle' ? 'New Chat' : key))
}))

vi.mock('../../dao/sessionDao', () => ({ sessionDao: { pick: mocks.pick } }))
vi.mock('../messageService', () => ({
  messageService: { listBySession: mocks.listBySession }
}))
vi.mock('../../i18n', () => ({ t: mocks.t }))

import { buildTurnCompletedFacts, isDefaultTitle } from '../sessionTriggerFacts'

type Msg = { role: string; content: string }

const msg = (role: string, content: string): Msg => ({ role, content })

function seed(
  opts: {
    title?: string
    settings?: Record<string, unknown> | null
    messages?: Msg[]
    missing?: boolean
  } = {}
): void {
  mocks.pick.mockReturnValue(
    opts.missing
      ? undefined
      : { title: opts.title ?? 'Some title', settings: opts.settings ?? null }
  )
  mocks.listBySession.mockResolvedValue(opts.messages ?? [])
}

beforeEach(() => {
  mocks.pick.mockReset()
  mocks.listBySession.mockReset()
})

describe('TF —— isDefaultTitle', () => {
  it('TF-1 与当前语言的默认标题逐字相等才算「还是默认标题」', () => {
    expect(isDefaultTitle('New Chat')).toBe(true)
    expect(isDefaultTitle('新对话')).toBe(false)
    expect(isDefaultTitle('New Chat ')).toBe(false)
    expect(isDefaultTitle('')).toBe(false)
  })

  it('TF-2 判据现取自 i18n —— 切了语言之后「默认标题」跟着变', () => {
    // 它不是一个常量：用户把界面切成中文之后，新会话的默认标题就是中文那句，
    // 而 auto-title 的 quick 绑定正是靠这个判据决定要不要起标题
    mocks.t.mockImplementationOnce(() => '新对话')
    expect(isDefaultTitle('新对话')).toBe(true)
  })
})

describe('TF —— buildTurnCompletedFacts', () => {
  it('TF-3 会话行不存在 → null（删除与本次埋点竞态时不编一份事实出来）', async () => {
    seed({ missing: true })
    expect(await buildTurnCompletedFacts('s1')).toBeNull()
    // 连消息都不必读
    expect(mocks.listBySession).not.toHaveBeenCalled()
  })

  it('TF-4 turnCount 数的是**用户文本消息**（≈ 已发生的轮数，含本轮）', async () => {
    seed({
      messages: [msg('user', 'a'), msg('assistant', 'b'), msg('user', 'c'), msg('assistant', 'd')]
    })
    const facts = (await buildTurnCompletedFacts('s1'))!
    expect(facts.turnCount).toBe(2)
    expect(facts.textMessageCount).toBe(4)
  })

  it('TF-5 空正文的消息两个计数都不算（工具轮/被中止的空卡片不该顶掉一轮）', async () => {
    // auto-title 的 refine 绑定卡在 turnCount == 2 上，这是个一次性窗口 —— 多算一条，
    // 那次精修就永远错过了
    seed({
      messages: [msg('user', 'a'), msg('assistant', ''), msg('assistant', '   '), msg('user', ' ')]
    })
    const facts = (await buildTurnCompletedFacts('s1'))!
    expect(facts.turnCount).toBe(1)
    expect(facts.textMessageCount).toBe(1)
  })

  it('TF-6 非对话角色（system_notify 等）不计入任何一个计数', async () => {
    seed({
      messages: [msg('user', 'a'), msg('system_notify', '出错了'), msg('assistant', 'b')]
    })
    const facts = (await buildTurnCompletedFacts('s1'))!
    expect(facts.textMessageCount).toBe(2)
    expect(facts.recentText).not.toContain('出错了')
  })

  it('TF-7 recentText 用固定的 `User:` / `Assistant:` 标签拼接，按时间序', async () => {
    // 标签刻意不本地化：它是数据标注不是界面文案，模型跨语言都读得懂
    seed({ messages: [msg('user', '第一句'), msg('assistant', '第二句')] })
    expect((await buildTurnCompletedFacts('s1'))!.recentText).toBe(
      'User: 第一句\nAssistant: 第二句'
    )
  })

  it('TF-8 recentText 截的是**尾部**（近的留下）且不超过 1000 字', async () => {
    // 起标题看的是最近在聊什么 —— 截头部会让它拿着一段早已过时的对话去命名
    seed({ messages: [msg('user', 'x'.repeat(2000)), msg('assistant', '最后一句')] })
    const facts = (await buildTurnCompletedFacts('s1'))!
    expect(facts.recentText.length).toBe(1000)
    expect(facts.recentText.endsWith('Assistant: 最后一句')).toBe(true)
  })

  it('TF-9 标题三件事：原样带出、是否默认、是否出自自动化', async () => {
    seed({ title: 'New Chat', settings: { titleOrigin: 'auto' } })
    expect(await buildTurnCompletedFacts('s1')).toMatchObject({
      title: 'New Chat',
      isDefaultTitle: true,
      titleAutoGenerated: true
    })

    seed({ title: '我自己起的名字', settings: { titleOrigin: 'user' } })
    expect(await buildTurnCompletedFacts('s1')).toMatchObject({
      title: '我自己起的名字',
      isDefaultTitle: false,
      titleAutoGenerated: false
    })
  })

  it('TF-10 settings 缺席 / 无 titleOrigin → titleAutoGenerated 为 false（不猜）', async () => {
    // 用户手动改过名之后 titleOrigin 是 'user'，而**从来没被起过名**的会话什么都没有 ——
    // 两者都不该让 refine 去覆盖一个它没写过的标题
    seed({ settings: null })
    expect((await buildTurnCompletedFacts('s1'))!.titleAutoGenerated).toBe(false)
    seed({ settings: {} })
    expect((await buildTurnCompletedFacts('s1'))!.titleAutoGenerated).toBe(false)
  })

  it('TF-11 零消息的会话 → 计数为 0、recentText 为空串（不是 null，形状恒定）', async () => {
    seed({ messages: [] })
    expect(await buildTurnCompletedFacts('s1')).toMatchObject({
      turnCount: 0,
      textMessageCount: 0,
      recentText: ''
    })
  })

  it('TF-12 键集钉板 —— payload 是契约，两个 emit 侧照着同一份形状铺', async () => {
    seed({ messages: [msg('user', 'a')] })
    expect(Object.keys((await buildTurnCompletedFacts('s1'))!).sort()).toEqual(
      [
        'isDefaultTitle',
        'recentText',
        'textMessageCount',
        'titleAutoGenerated',
        'title',
        'turnCount'
      ].sort()
    )
  })
})
