/**
 * P2-14 · 起标题的会话事实读 durable 会话（`sessionTriggerFacts` 的转写换成 agent-runtime 的转写摘要）。
 *
 *   P2-14-29 durable 基本面：计数、recentText、标题三件事取自会话行；只 peek，从不 open、从不读 messageService
 *   P2-14-30 通知不算（裁决 PIN-02）：日期 / 后台通知、按形状认出的通知都不算 user，也不算一条文本；
 *            refine 的 CEL `when`（取自内置 auto-title 的 md）因此照样成立
 *   P2-14-31 内联 Token：recentText 用显示侧车的标记态原文，payload 不进
 *   P2-14-32 没有行 → null 且不 peek；durable 行但没有存储 → 零计数；peek / 摘要失败 → 照样拒绝（不编零）
 *
 * 替身：sessionRecords（行 = 标题 / 设置 / storageKind）/ messageService（spy）/ sessionHost（`{peek, get, open}`）/
 * i18n。agent-runtime 用真的（MemoryStorage 会话）。
 */
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { SessionHost } from '@shuvix/agent-runtime'
import { evaluateWhen } from '../../../../../../packages/agent-runtime/src/hook/when'
import {
  assistant,
  bg,
  memoryHost,
  notice,
  user,
  writeDurable,
  type TwinStep
} from './support/transcriptTwins'

interface Row {
  title: string
  settings: Record<string, unknown> | null
  storageKind: string
}

const mocks = vi.hoisted(() => ({
  pick: vi.fn<(id: string, fields: string[]) => unknown>(),
  listBySession: vi.fn(),
  peek: vi.fn<(id: string) => Promise<unknown>>(),
  open: vi.fn(),
  get: vi.fn()
}))

vi.mock('../sessionRecords', () => ({ sessionRecords: { pick: mocks.pick } }))
vi.mock('../messageService', () => ({ messageService: { listBySession: mocks.listBySession } }))
vi.mock('../sessionHost', () => ({
  getSessionHost: () => ({ peek: mocks.peek, get: mocks.get, open: mocks.open })
}))
vi.mock('../../i18n', () => ({
  t: (key: string) => (key === 'agent.defaultTitle' ? 'New Chat' : key)
}))

import { buildTurnCompletedFacts } from '../sessionTriggerFacts'

const rows = new Map<string, Row>()
let host: SessionHost
let seq = 0

beforeEach(() => {
  vi.resetAllMocks()
  ;({ host } = memoryHost())
  mocks.pick.mockImplementation((id) => rows.get(id))
  mocks.listBySession.mockResolvedValue([])
  mocks.peek.mockImplementation((id) => host.peek(id))
})

afterEach(async () => {
  await host.closeAll()
  rows.clear()
})

async function durable(steps: readonly TwinStep[], row: Partial<Row> = {}): Promise<string> {
  const id = `tfd-${++seq}`
  rows.set(id, {
    title: 'Deploy plan',
    settings: { titleOrigin: 'auto' },
    storageKind: 'durable-sqlite-1',
    ...row
  })
  if (steps.length > 0) await writeDurable(await host.open(id), steps)
  return id
}

/** 内置 auto-title 在 `session.turn-completed` 上的 `when`（取自随包的 md，而不是在这里再抄一遍） */
function refineWhen(): string {
  const here = dirname(fileURLToPath(import.meta.url))
  const md = readFileSync(
    resolve(
      here,
      '../../../../../../packages/agent-runtime/src/hook/builtinHooks/md/auto-title.md'
    ),
    'utf8'
  )
  const match = /trigger: session\.turn-completed\s*\n\s*when: (.+)\n/.exec(md)
  if (!match) throw new Error('auto-title.md has no session.turn-completed binding')
  return match[1]!.trim()
}

describe('P2-14 · turn-completed facts on durable sessions', () => {
  it('P2-14-29 durable basics: counts and recentText from the digest, the title fields from the row; peek only', async () => {
    const sid = await durable([user(1, 'a'), assistant(2, 'A'), user(3, 'b'), assistant(4, 'B')])
    expect(await buildTurnCompletedFacts(sid)).toEqual({
      title: 'Deploy plan',
      isDefaultTitle: false,
      titleAutoGenerated: true,
      turnCount: 2,
      textMessageCount: 4,
      recentText: 'User: a\nAssistant: A\nUser: b\nAssistant: B'
    })
    expect(mocks.peek).toHaveBeenCalledWith(sid)
    expect(mocks.open).not.toHaveBeenCalled()
    expect(mocks.listBySession).not.toHaveBeenCalled()
  })

  it('P2-14-30 notices do not count (PIN-02), so the auto-title refine still fires at turn 2', async () => {
    const sid = await durable([
      user(1, 'a'),
      assistant(2, 'A'),
      { type: 'notice', ts: 3, text: '<date-change>Today is 2026-10-05 (Monday).</date-change>' },
      notice(4, bg('t0', 'x')),
      user(5, bg('t', 'y')),
      assistant(6, 'ack'),
      user(7, 'b'),
      assistant(8, 'B')
    ])
    const facts = await buildTurnCompletedFacts(sid)
    expect(facts).toMatchObject({
      turnCount: 2,
      textMessageCount: 5,
      recentText: 'User: a\nAssistant: A\nAssistant: ack\nUser: b\nAssistant: B'
    })
    const when = refineWhen()
    expect(when).toBe(
      'event.titleAutoGenerated && event.turnCount == 2 && event.textMessageCount >= 3'
    )
    expect(evaluateWhen(when, { event: facts })).toBe(true)
  })

  it('P2-14-31 the titler reads the display text: markers kept, the payload never shows', async () => {
    const sid = await durable([
      user(1, 'fix PAYLOAD-X', {
        content: 'fix {{shuvixInlineToken:k}}',
        tokens: { k: { type: 'cmd', id: 'fix', displayText: '/fix', payload: 'PAYLOAD-X' } }
      }),
      assistant(2, 'ok')
    ])
    const facts = await buildTurnCompletedFacts(sid)
    expect(facts?.recentText).toBe('User: fix {{shuvixInlineToken:k}}\nAssistant: ok')
    expect(JSON.stringify(facts)).not.toContain('PAYLOAD-X')
  })

  describe('P2-14-32 missing row, missing storage, failure', () => {
    it('no row → null, and nothing is peeked', async () => {
      expect(await buildTurnCompletedFacts('tfd-missing')).toBeNull()
      expect(mocks.peek).not.toHaveBeenCalled()
      expect(mocks.listBySession).not.toHaveBeenCalled()
    })

    it('a durable row without storage → zero counts plus the title fields; never open', async () => {
      const sid = await durable([], { title: 'New Chat', settings: null })
      expect(await buildTurnCompletedFacts(sid)).toEqual({
        title: 'New Chat',
        isDefaultTitle: true,
        titleAutoGenerated: false,
        turnCount: 0,
        textMessageCount: 0,
        recentText: ''
      })
      expect(mocks.peek).toHaveBeenCalledWith(sid)
      expect(mocks.open).not.toHaveBeenCalled()
    })

    it('peek rejects → the facts reject (no zero facts are made up)', async () => {
      const sid = await durable([])
      mocks.peek.mockRejectedValue(new Error('storage corrupt'))
      await expect(buildTurnCompletedFacts(sid)).rejects.toThrow('storage corrupt')
    })

    it('the digest rejects (a stale handle) → the facts reject', async () => {
      const sid = await durable([user(1, 'a')])
      const stale = await host.peek(sid)
      await host.close(sid)
      mocks.peek.mockResolvedValue(stale)
      await expect(buildTurnCompletedFacts(sid)).rejects.toThrow(`Session ${sid} is closed`)
    })
  })
})
